### ISSUE TITLE
Regression: dotty-cps-async @ 1.3.2 fails with type mismatch

### ISSUE THREAD

**Issue by soronpo** [scala/scala3#26031]
## Compiler version

`3.9.0-RC1-bin-20260508-eb2e041-NIGHTLY` (Scala 3 mainline at commit `eb2e041`).

- **Last good**: `3.9.0-RC1-bin-20260501-0c8c581-NIGHTLY` (passed in the prior weekly).
- **First bad**: `3.9.0-RC1-bin-20260508-eb2e041-NIGHTLY`.
- **Regression window**: 55 commits — `0c8c581...eb2e041` (compare: https://github.com/scala/scala3/compare/0c8c581...eb2e041). Bisect not done yet.

## VirtusLab Open Community Build

- Failing job (2026-05-09): https://github.com/VirtusLab/community-build3/actions/runs/25584410798/job/75112762736
- Project @ ref: `dotty-cps-async/dotty-cps-async` @ tag [`1.3.2`](https://github.com/dotty-cps-async/dotty-cps-async/tree/1.3.2) (commit `636274a3`).
- Project's offending source: [`shared/src/test/scala/cps/TestEither.scala:17`](https://github.com/dotty-cps-async/dotty-cps-async/blob/1.3.2/shared/src/test/scala/cps/TestEither.scala#L17). Same shape repeats at `logic/jvm/src/test/scala/cps/monads/logic/AsyncLogicTTest.scala:56:115`.

## Minimization

```scala
trait Ctx[F[_]]

trait Mon[F[_]]:
  type Context <: Ctx[F]

object Mon:
  type Aux[F[_], C <: Ctx[F]] = Mon[F] { type Context = C }

class Wrap[F[_], C <: Ctx[F]](using val am: Mon.Aux[F, C]):
  transparent inline def apply[T](inline expr: C ?=> T): F[T] =
    inner[F, T, C](am, expr)

transparent inline def inner[F[_], T, C <: Ctx[F]](
    inline am: Mon.Aux[F, C],
    inline expr: C ?=> T
): F[T] = ???

transparent inline def doIt[F[_]](using am: Mon[F]) =
  new Wrap(using am)

class Pair[A, B]
class PairCtx[E] extends Ctx[[A] =>> Pair[E, A]]
class PairMon[E] extends Mon[[A] =>> Pair[E, A]]:
  type Context = PairCtx[E]

given pm[E]: Mon[[A] =>> Pair[E, A]] = new PairMon[E]

object Test:
  val r = doIt[[A] =>> Pair[String, A]] { 42 }
```

## Output
```
-- [E007] Type Mismatch Error: i10-cb.scala:53:40 -----
53 |  val r = doIt[[A] =>> Pair[String, A]] { 42 }
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |Found:    (contextual$1 : am$proxy1.Context)
   |Required: Wrap[[A] =>> Pair[String, A], ? <: Ctx[[A] =>> Pair[String, A]]]#C
   |---------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from i10-cb.scala:35
35 |    inner[F, T, C](am, expr)
   |                          ^
1 error found
```

## Expectation

Compiles, as it did under `3.9.0-RC1-bin-20260501-0c8c581-NIGHTLY` and earlier 3.x nightlies.

## Likely culprits in the 55-commit window

Two candidates touched implicit/inference logic that interacts with path-dependent types and given-resolution chains:

- **#25910 / `2967a995`** "Treat equivalent candidates as divergent in implicit search" — directly affects given-search through chains like `CpsMonad[F]` → derive `InferAsyncArg.Aux[F, am.Context]`. If two candidates are now flagged as divergent where they weren't before, this would surface as failed unification at the macro-expansion site.
- The closure-explicit cluster (`ad5249d2` "Make result types of some closures explicit", `ff38b04b` "Let FunctionOrMethod's extractor return the type bounds of PolyType parameters", `6b1978bb` "Revised scheme: make parameters of closure types non-inferred", `ce514aa7` "Thread correct variance through transformInferred/Explicit handovers", `3e3c2484` "Drop restriction that only polymorphic closures are explicified", `ef2c2e6a` "Make parameter types of some closures explicit (#25967)") — these affect inference of closure parameter types, including context-function parameters like the `(contextual$1: ...)` shown in the error.

## Cross-references

- [scala/scala3#13899](https://github.com/scala/scala3/issues/13899) (open since 2021-11, by `rssh` — dotty-cps-async maintainer): "Failed to bind context-depended type into Aux when matcher is inline". Same `InferAsyncArg.Aux[F, .#Context]` family. Verified to still reproduce on `eb2e041` exactly as on 3.1.x — i.e. #13899 itself is _not_ the new regression's surface, but the new regression is in the same neighbourhood.
- [scala/scala3#13903](https://github.com/scala/scala3/issues/13903) (open since 2021-11, by `rssh`): "expression is not transformed to context function when context type is path-dependent type of unknown value". Sibling.

**Comment by Gedochao** [comment]
I'm not sure about the minimization here...

With 3.9.0-RC1-bin-20260501-0c8c581-NIGHTLY I get:
```scala
  val r = doIt[[A] =>> Pair[String, A]] { 42 }
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |Found:    (Wrap_this.am : Mon.Aux[[A] =>> Pair[String, A], Wrap_this.C])
   |Required: Mon.Aux[[A] =>> Pair[String, A],
   |  Wrap[[A] =>> Pair[String, A], ? <: Ctx[[A] =>> Pair[String, A]]]#C]
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from repro.scala:11
11 |    inner[F, T, C](am, expr)
   |                   ^^
    ----------------------------------------------------------------------------
   |
   | longer explanation available when compiling with `-explain`
1 error found
Compilation failed

```

With 3.9.0-RC1-bin-20260508-eb2e041-NIGHTLY:
```scala
-- [E007] Type Mismatch Error: /Users/pchabelski/IdeaProjects/scala-cli-tests/compiler-repro/repro.scala:29:40 
29 |  val r = doIt[[A] =>> Pair[String, A]] { 42 }
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |Found:    (contextual$1 : am$proxy1.Context)
   |Required: Wrap[[A] =>> Pair[String, A], ? <: Ctx[[A] =>> Pair[String, A]]]#C
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from repro.scala:11
11 |    inner[F, T, C](am, expr)
   |                           ^
    ----------------------------------------------------------------------------
   |
   | longer explanation available when compiling with `-explain`
1 error found
Compilation failed
```

> Compiles, as it did under 3.9.0-RC1-bin-20260501-0c8c581-NIGHTLY and earlier 3.x nightlies.

As far as I can tell, it never did compile, the error just changed?
@soronpo can you reproduce the problem with the minimized snippet?

**Comment by Gedochao** [comment]
Closing this, thinking this is another case of imprecise issue minimization with an LLM, like https://github.com/scala/scala3/issues/26018
Please write issues by hand, or at the very least process the content of the issue by hand.
And again, feel free to trim down the issue requirements to make the reproduction and description clear, and then reopen (or open as a new issue).

**Comment by tanishiking** [comment]
- last good nightly: 3.9.0-RC1-bin-20260501-0c8c581-NIGHTLY
- first bad nightly: 3.9.0-RC1-bin-20260502-b264c19-NIGHTLY

and bisect found that

- last good commit: 897f0988b2 
- first bad commit: 32a04c8405

so the culprit looks like https://github.com/scala/scala3/pull/25960, actually revert that fixed the problem.

**Comment by tanishiking** [comment]
The fix https://github.com/scala/scala3/pull/26563 is merged, thanks for reporting @soronpo 🙌
