### ISSUE TITLE
NoSuchMethodError calling a method returning an opaque alias of Unit, compiled with 3.3–3.8, from 3.9.0

### ISSUE THREAD

**Issue by adamw** [scala/scala3#27140]
## Compiler version

Fails with 3.9.0 and 3.10.1-RC1-bin-20260923-4cf8dc0-NIGHTLY. Works with 3.8.1 and earlier.

## Minimized code

```scala
// lib/Lib.scala, compiled with 3.3.8
package lib

opaque type Ev = Unit
object Ev:
  def ev(): Ev = ()
```

```scala
// app/App.scala, compiled with 3.9.0 against lib
@main def app(): Unit = println(lib.Ev.ev())
```

```
scala-cli --power package -S 3.3.8 lib --library -o lib.jar
scala-cli run -S 3.8.1 --jar lib.jar app
scala-cli run -S 3.9.0 --jar lib.jar app
```

## Output

With 3.8.1: `()`. With 3.9.0:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void lib.Lib$package$Ev$.ev()'
```

When compiled with 3.3.8, `Ev.ev()` has the JVM signature `public scala.runtime.BoxedUnit ev()`. When compiled with 3.9.0, it's `public void ev()`, so the erasure changed.

## Expectation

Code compiled with 3.9.0 can call libraries compiled with earlier 3.x versions.

Found while using Ox 1.0.7 (compiled with 3.3.8) in a 3.9.0 project: `ox.resourceScope` fails because its `given noEnclosingConcurrencyScope(using NotGiven[OxUnsupervised])` returns `opaque type NoEnclosingConcurrencyScope = Unit`.

**Comment by sjrd** [comment]
This is unfortunately expected. The previous erasure rule was basically unsound. See https://github.com/scala/scala3/issues/24653 for details and for workarounds for libraries.

**Comment by adamw** [comment]
Ah, thanks. I'll use that work-around. However I didn't get anything from MiMA on the Ox side.
