### PR TITLE
Retain loading diagnostics across REPL completions

### LINKED ISSUE #18614: REPL completions hide compile error (e.g. Classfile/TASTy is broken error)
Running completions in the REPL seems to ignore any errors produced by the compiler

## Compiler version

3.3.0 (to replicate, though im sure the latest version swallows other kinds of errors)

run the repl with JDK 21 (If you use 3.3.1 im sure there is another error that can be swallowed this way)

## Minimized code

in the repl, try running completions on this line
```Scala
scala> import java.lang.reflect.ClassFileFormatVersion.<TAB>
```

then from now on java.lang.reflect.ClassFileFormatVersion is broken, and no error was printed about the broken class file.

e.g. now mysteriously ClassFileFormatVersion has no members:
```Scala
scala> java.lang.reflect.ClassFileFormatVersion.RELEASE_21
-- [E008] Not Found Error: -----------------------------------------------------
1 |java.lang.reflect.ClassFileFormatVersion.RELEASE_21
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value RELEASE_21 is not a member of object java.lang.reflect.ClassFileFormatVersion
1 error found
```

## Expectation
I expected to see the same error as if I had not done a completion:
```scala
scala> java.lang.reflect.ClassFileFormatVersion.RELEASE_21
error while loading ClassFileFormatVersion,
class file /modules/java.base/java/lang/reflect/ClassFileFormatVersion.class is broken, reading aborted with class java.lang.RuntimeException
bad constant pool index: 0 at pos: 2629
-- [E008] Not Found Error: -----------------------------------------------------
1 |java.lang.reflect.ClassFileFormatVersion.RELEASE_21
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value RELEASE_21 is not a member of object java.lang.reflect.ClassFileFormatVersion
2 errors found
```

### PR DESCRIPTION
**Pull request by bracevac**
Fixes #18614

Keep loading errors around so later REPL completions can still report them, while unrelated completion searches stay quiet.

## Have you relied on LLM-based tools in this contribution?

Yes, and I checked the output by reviewing it. 

I explored a few alternatives, and this is a simple one that at least replays the error when completing again.

The more fundamental problem is that REPL completions are side-effecting operations, but it'd require a significant amount of work to make them isolated. 

And `:dep` itself is another can of worms I dare not open this time. 

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

& manual testing using `./bin/replQ`.

### CODE REVIEW

**Review by SolalPirelli — COMMENTED** [review]
I don't understand why `RetainedSymbolLoadingFailures` is a key we use directly on the context instead of a `store` like the existing stuff, or a key on each individual symbol.

Also, is this so expensive that we shouldn't report loading failures outside of the REPL? Since it's already an error path that won't be hit by well-formed code, it should be fine to do it always and not have different behavior?

**Comment by bracevac** [comment]
> I don't understand why `RetainedSymbolLoadingFailures` is a key we use directly on the context instead of a `store` like the existing stuff, or a key on each individual symbol.

Right, I overlooked that. I changed it to use the context store. Not sure we want an extra field on Symbol just for this feature IIUC.

> Also, is this so expensive that we shouldn't report loading failures outside of the REPL? Since it's already an error path that won't be hit by well-formed code, it should be fine to do it always and not have different behavior?

It's not about cost. I was deliberately isolating it for just the REPL. Enabling this globally affects other systems, like speculative executions in the typer, presentation compiler, and scaladoc. I don't have the bandwidth to dig into those before the release cutoff.

**Review by SolalPirelli — APPROVED** [review]
OK, I guess this works for now. It'd be good to at least have a short concrete plan of what it would take to cleanly implement completions as the PR description alludes to.

**Comment by bracevac** [comment]
1. Completion should be a read-only query over an isolated copy of the REPL session. Completion may load and inspect compiler state, but none of those changes should reach the live REPL session.

2. `:dep` seems quite dangerous. Dependencies can pull in other versions of the standard library:
```scala
scala> :dep io.github.bishabosha::enhanced-string-interpolator:1.0.1
Resolved 1 dependencies (3 JARs)

scala> import scala.jdk.CollectionConverters.*

scala> def scalaLibraries = getClass.getClassLoader.getResources("scala/deriving/Mirror.class").asScala.toList
def scalaLibraries: List[java.net.URL]

scala> scalaLibraries
val res0: List[java.net.URL] = List(
  jar:file:/Users/oliver/Library/Caches/Coursier/arc/https/github.com/scala/scala3/releases/download/3.8.4/scala3-3.8.4-aarch64-apple-darwin.tar.gz/scala3-3.8.4-aarch64-apple-darwin/maven2/org/scala-lang/scala-library/3.8.4/scala-library-3.8.4.jar!/scala/deriving/Mirror.class,
  jar:file:/Users/oliver/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.4.0-RC3/scala3-library_3-3.4.0-RC3.jar!/scala/deriving/Mirror.class
)
```

That can result in some Frankenstein state of the scala package:
```scala
scala> :settings -experimental -language:experimental.captureChecking
scala> :dep org.scala-lang:scala3-library_3:3.4.0
Resolved a dependency (2 JARs)

scala> class Bad(x: () => Unit) extends scala.Pure
// defined class Bad

scala> class Checked(x: () => Unit) extends scala.caps.Pure
-- [E223] CaptureChecking Error: -----------------------------------------------
1 |class Checked(x: () => Unit) extends scala.caps.Pure
  |              ^
  |Reference `Checked.this.x` is not included in the allowed capture set {} of the self type of class Checked.
1 error found
```
The problem is that `Bad` should be rejected:
```scala
-- [E008] Not Found Error: -----------------------------------------------------
1 |class Bad(x: () => Unit) extends scala.Pure
  |                                 ^^^^^^^^^^
  |                                 type Pure is not a member of scala
1 error found
```
But it isn't, since the 3.4 library had a `Pure` class in the `scala` package. This is concerning and confusing. 

It can also lead to initializers being invoked yet again:
```scala
scala> val x = { println("initialized"); 1 }
initialized
val x: Int = 1

scala> x
val res0: Int = 1

scala> :dep com.lihaoyi::os-lib:0.11.8
Resolved 1 dependencies (5 JARs)

scala> x
initialized
val res1: Int = 1

scala> x
val res2: Int = 1
```

Can we have a well-defined semantic spec for `:dep`?

**Comment by bracevac** [comment]
CI failure is fixed by https://github.com/scala/scala3/pull/26843
