### ISSUE TITLE
compiler implicit conversion from Byte to Int is not happening

### ISSUE THREAD

**Issue by pjfanning** [scala/scala3#18068]
## Compiler version

scalac 3.3.0

## Minimized code

```Scala
def bytes(start: Byte, end: Byte): Array[Byte] = (start to end).map(_.toByte).toArray[Byte]
```

https://scastie.scala-lang.org/pjfanning/QSgepNpJQDKok9GYzN3aLQ/2

## Output

Compiles in Scala 2 but fails to compile with Scala 3.3.0.

Error says:
```
value to is not a member of Byte.
An extension method was tried, but could not be fully constructed:

    intWrapper(start)
```

## Expectation

Ideally would compile in Scala 3.

I can workaround by doing:
```
def bytes(start: Byte, end: Byte): Array[Byte] = (new scala.runtime.RichInt(start) to end).map(_.toByte).toArray[Byte]
```

**Comment by som-snytt** [comment]
I think it means, "Compiles in scala 2." Previous to 3.3.0, it claims to have tried `longWrapper` instead.

The more natural explicit expression is
```
scala> val b = 42.toByte
val b: Byte = 42

scala> b.toInt to b
val res0: scala.collection.immutable.Range.Inclusive = Range 42 to 42
```
The doc on dropping weak conformance does not mention this use case.

**Comment by He-Pin** [comment]
refs ：https://github.com/apache/incubator-pekko-connectors/pull/167

**Comment by Kordyjan** [comment]
I believe this is the same case as https://github.com/lampepfl/dotty/issues/17360. I don't think it will be improved any time soon. I would suggest `(start.toInt to end).map(_.toByte).toArray[Byte]` as a workaround.
