### PR TITLE
Do not emit Java generic signatures for trait private val setters

### LINKED ISSUE #26616: Scala 3.9.0-RC4: trait private val with type alias still generates incompatible setter signature for Java subclasses
## Compiler version

Scala 3.9.0-RC4 (also affects 3.9.0-RC3, 3.9.0-RC1)

## Minimized code

**MyTrait.scala:**
```scala
object MyTrait:
  case class Event[D](value: D)
  case class State[S, D](name: S, data: D)

trait MyTrait[S, D]:
  import MyTrait.*
  type StateT = State[S, D]
  type EventT = Event[D]
  type StateFunction = PartialFunction[EventT, StateT]
  private val handler: StateFunction = { case e => State(null.asInstanceOf[S], e.value) }

abstract class MyAbstract[S, D] extends MyTrait[S, D]
```

**MyJavaClass.java:**
```java
public class MyJavaClass extends MyAbstract<String, String> {
}
```

## Steps to reproduce

1. Compile the Scala code:
   ```
   scalac -d out MyTrait.scala
   ```
2. Compile the Java class:
   ```
   javac -cp out:$(cs fetch org.scala-lang:scala3-library_3:3.9.0-RC4 --classpath) MyJavaClass.java
   ```

## Output

```
MyJavaClass.java:1: error: MyJavaClass is not abstract and does not override abstract method
MyTrait$_setter_$MyTrait$$handler_$eq(PartialFunction<Event<String>,State<String,String>>) in MyTrait
public class MyJavaClass extends MyAbstract<String, String> {
       ^
```

## Expectation

The Java class should compile successfully, as it does with Scala 3.3.8.

## Root cause analysis

This is a residual issue related to #26372 (fixed by #26374, regression fixed by #26542).

The fix in #26542 correctly handles cases where the trait type parameter is used directly in the field type. However, when the field type is expressed through **type aliases defined inside the trait** that expand to types containing the trait's type parameters, the mixed-in setter in the abstract class still gets `Object` types instead of the class's type variables.

**Bytecode evidence (from Apache Pekko's `FSM` trait, same pattern):**

Trait `FSM[S, D]` — abstract setter uses type variables:
```
Signature: (Lscala/PartialFunction<Lorg/apache/pekko/actor/FSM$Event<TD;>;Lorg/apache/pekko/actor/FSM$State<TS;TD;>;>;)V
```

Class `AbstractFSM[S, D]` — concrete setter uses `Object`:
```
Signature: (Lscala/PartialFunction<Lorg/apache/pekko/actor/FSM$Event<Ljava/lang/Object;>;Lorg/apache/pekko/actor/FSM$State<Ljava/lang/Object;Ljava/lang/Object;>;>;)V
```

The trait declares the abstract setter with `TD`/`TS` type variables, but the mixed-in concrete implementation in `AbstractFSM` widens them to `Object`. javac sees these as incompatible signatures and reports the abstract method as unimplemented.

**Key difference from #26372:** The field type uses trait-local type aliases (`type StateFunction = PartialFunction[EventT, StateT]` where `EventT = Event[D]`, `StateT = State[S, D]`). The `mixinGenericInfos` logic in `Mixin.scala` appears to not substitute type parameters when they are reached through type alias expansion.

## Workaround

None for library authors — the trait must be restructured to avoid type aliases in private val types, which is invasive.

## Context

This blocks Apache Pekko's Scala 3.9.0-RC4 cross-compilation (apache/pekko#3303). The `FSM[S, D]` trait and `PersistentFSMBase` both use this pattern extensively.

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #26616

## Have you relied on LLM-based tools in this contribution?

No

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

### CODE REVIEW

File: tests/generic-java-signatures/26616.check [hunk 1]
```diff
@@ -0,0 +1,4 @@
+public scala.PartialFunction MyAbstract.MyTrait$$handler()
+public scala.PartialFunction MyAbstract.MyTrait$$handler()
```
Comment (SolalPirelli) [inline tests/generic-java-signatures/26616.check:2]: ~~This is still not good, we shouldn't emit a raw type here, but that's another bug~~

edit: no actually that's fine for a private val we don't need generic signatures

File: tests/generic-java-signatures/26616/Scala_1.scala [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+  case class State[S, D](name: S, data: D)
+
+trait MyTrait[S, D]:
+  import MyTrait.*
+  type StateT = State[S, D]
+  type EventT = Event[D]
+  type StateFunction = PartialFunction[EventT, StateT]
+  private val handler: StateFunction = { case e => State(null.asInstanceOf[S], e.value) }
+
+abstract class MyAbstract[S, D] extends MyTrait[S, D]
```
Comment (tanishiking) [inline tests/generic-java-signatures/26616/Scala_1.scala:12]: This implementation happens to work because both `MyTrait[S, D]` and `MyAbstract[S, D]` use `S` and `D`. But if we rename to something else like `MyAbstract[A, B]`, it doesn't work.

```suggestion
abstract class MyAbstract[A, B] extends MyTrait[A, B]
```

---

Instead of re-using the parent trait's type parameter name as is, we need to rename them (`S` and `D`) `asSeenFrom` the `MyAbstract[A, B]`.
While I fixed another regression in that way https://github.com/scala/scala3/pull/26542, it didn't cover the type aliases 😓 What do you think about renaming the entire type in `Mixin.scala` by:

```diff
-              val mixinArgs = mixin.typeParams.map(_.typeRef.asSeenFrom(cls.thisType, mixin))
-              gi.subst(mixin.typeParams, mixinArgs)
+              gi.asSeenFrom(cls.thisType, mixin)
```

?

**Review by tanishiking — CHANGES_REQUESTED** [review]

File: tests/generic-java-signatures/26616/Scala_1.scala (hunk 2 above)
Comment (SolalPirelli) [reply tests/generic-java-signatures/26616/Scala_1.scala:12]: Argh, nice catch. Indeed this fixes the problem and the original change here isn't necessary anymore. (Too bad, I found it a lot clearer, but I'm also a bit worried about the perf implications of doing subtyping on all owners...)

Comment (SolalPirelli) [reply tests/generic-java-signatures/26616/Scala_1.scala:12]: OK, that doesn't quite work as evidenced by the many CI failures, I need to look deeper

Comment (SolalPirelli) [reply tests/generic-java-signatures/26616/Scala_1.scala:12]: Seems like `asSeenFrom` is happy to give you a type private to the trait "as seen from" the deriving class, but that type is erroneous since the class can't actually see it...

Comment (SolalPirelli) [reply tests/generic-java-signatures/26616/Scala_1.scala:12]: I thought about it some more and we were following a red herring.

The goal isn't to make this specific method have a "good" generic signature; the goal is to allow interop with Java.

For a private trait val's setter, having a signature is not useful, and indeed we stopped generating a signature for the getter in #25780.

So now we also don't generate it for the setter.

I kept your proposed change because it does indeed read as a more natural way to write the code.

**Review by tanishiking — APPROVED** [review]
Good point! LGTM 💯

**Comment by He-Pin** [comment]
Could this be backported to `release-3.9.0`?

3.9.0-RC5 still hits this — Apache Pekko's CI fails when compiling Java test sources against `AbstractFSM` / `AbstractPersistentFSM` subclasses:

```
AbstractFSMActorTest.MyFSM is not abstract and does not override abstract method
FSM$_setter_$FSM$$handleEventDefault_$eq(PartialFunction<Event<String>,State<String,String>>) in FSM
```

The fix is on main but didn't make it into the release branch. Would be great to get it into RC6 so we can validate Pekko against the final 3.9.0 ahead of time.

**Comment by SolalPirelli** [comment]
Sorry, this one slipped through the cracks, nominating for backport now so it can be in RC6. cc @WojciechMazur
