### PR TITLE
Fix regression #26374: generic signatures of mixed-in trait setters

### LINKED ISSUE #26531: Generic signature replaces bounded method type parameter uses with the enclosing class type
## Compiler version

- 3.9.0-RC2
- 3.9.0-RC3
- 3.10.0-RC1-bin-20260712-f51c618-NIGHTLY

The same code works with 3.8.3 and 3.9.0-RC1, so the regression starts in 3.9.0-RC2.

## Minimized code

`Repro.scala`:

```scala
package repro

import java.util.function.Consumer

final class Builder[T] {
  def accept[M <: T](clazz: Class[M], consumer: Consumer[M]): Unit = ()
}
```

`Use.java`:

```java
package repro;

final class Use {
  interface Command {}
  static final class Create implements Command {}

  void test(Builder<Command> builder) {
    builder.accept(Create.class, (Create command) -> {});
  }
}
```

Compile with:

```shell
scala-cli compile Repro.scala -S 3.9.0-RC3 --server=false -d out
javac -cp out -d out Use.java
```

## Output

```text
Use.java:8: error: incompatible types: Class<Create> cannot be converted to Class<Command>
    builder.accept(Create.class, (Create command) -> {});
                         ^
```

`javap -p -s repro.Builder` shows that the method type parameter `M` is declared, but all of its uses are replaced with the outer type parameter `T`:

```java
public <M extends T> void accept(java.lang.Class<T>, java.util.function.Consumer<T>);
```

With 3.8.3 and 3.9.0-RC1, the generated signature is:

```java
public <M extends T> void accept(java.lang.Class<M>, java.util.function.Consumer<M>);
```

## Expectation

The method type variable `M` has upper bound `T`, but it remains a distinct type variable. Its occurrences in `Class[M]` and `Consumer[M]` must therefore be encoded as `M`, as they were before 3.9.0-RC2. Java should be able to infer `M = Create` and compile the call.

This breaks Java-facing generic APIs in [Apache Pekko PR #3303](https://github.com/apache/pekko/pull/3303), including `BehaviorBuilder[T].onMessage[M <: T]`, where valid Java method references no longer compile. The affected compiler area overlaps the generic-signature rewrite in #25880.

### LINKED ISSUE #26533: Higher-kinded type-lambda argument leaks an undeclared type variable into the Java generic signature
## Compiler version
3.9.0-RC3, 3.10.0-RC1-bin-20260713-f51c618-NIGHTLY
works with 3.9.0-RC1, so regressed somewhere later.

## Minimized code
GenericSignatures.scala:
```scala
//> using dep io.get-coursier:coursier-archive-cache_2.13:2.1.25-M26

import coursier.cache.ArchiveCache
import coursier.util.Task

class FirstList(val cache: ArchiveCache[Task])
class UsingCtor()(using cache: ArchiveCache[Task])
```

Consumer.java:
```java
public class Consumer {
  public static void main(String[] args) {
    FirstList a = new FirstList(null);
    UsingCtor b = new UsingCtor(null);
  }
}
```

## Output

```scala
[error] ./Consumer.java:3:5
[error] cannot access FirstList
[error]   bad class file: /Users/pchabelski/IdeaProjects/scala-cli-tests/390-rc3/.scala-build/.bloop/390-rc3_1e4ad03333/bloop-internal-classes/main-5uuzyU4KRJ2sj2rJsDfj4g==/FirstList.class
[error]     undeclared type variable: T
[error]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[error]     FirstList a = new FirstList(null);
[error]     ^^^^^^^^^
[error] ./Consumer.java:4:5
[error] cannot access UsingCtor
[error]   bad class file: /Users/pchabelski/IdeaProjects/scala-cli-tests/390-rc3/.scala-build/.bloop/390-rc3_1e4ad03333/bloop-internal-classes/main-5uuzyU4KRJ2sj2rJsDfj4g==/UsingCtor.class
[error]     undeclared type variable: T
[error]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[error]     UsingCtor b = new UsingCtor(null);
[error]     ^^^^^^^^^
```

## Expectation
Compiles with no errors.

### PR DESCRIPTION
**Pull request by tanishiking**
Fixes #26531
Fixes #26533

This is the fix for the regression introduced by #26374

**original issue #26372**

The original issue #26372 was, given:

```scala
trait MyTrait[S0]:
  val foo: Map[S0, String]

abstract class MyAbstract[S1] extends MyTrait[S1]
```

`Mixin` copies the setter of `MyTrait` into `MyAbstract`, and it's expected type is like `def foo_=(value: Map[S1, String]): Unit`.

However, `mixinGenericInfos` in `Mixin.scala`, construct generic information from trait as-is.
`def foo_=(value: Map[S0, String]): Unit` (insttead of `S1`), where `S0` is not declared in `MyAbstract[S1]` scope.

As a result, `GenericSignatures` tells that `S1` isn't referenceable from `MyAbstract`, and widen to it's upper bound `Any`. In the end, generic signature for generated setter for `MyTrait` became `Map<Object, String>` that isn't compatible with `MyTrait`'s setter and fails with

```java
MyJavaImpl.java:3: error: MyJavaImpl is not abstract and does not override abstract method test$MyTrait$_setter_$test$MyTrait$$myMap_$eq(scala.collection.mutable.Map<java.lang.Object,java.lang.String>) in MyTrait
public class MyJavaImpl extends MyAbstract<String> {
       ^
```

---

**How #26374 address the issue**

the fix by #26374 was "if it's a type parameter,
don't widen it, just output the name as-is" by:

```scala
if typeSym.isTypeParam then
  typeParamSig(typeSym.name)
```

result in `Map<S1, String>`

---

**Why #26374 introduced regressions**

However, in a JVM signature can only be written when the enclosing class or method actually declares tparam `S1`.

For #26533

```scala
class Wrap[A](val value: G[A]) extends AnyVal
class FirstList(val cache: Cache[Wrap])
```

`A` is declared only within `Wrap`. `FirstList` does not declare `A`. However, `A` is still type parameter and `isTypeParam` returns true. Therefore, it ended up emitting `Cache<G<TA;>>` where A isn't declared in `FirstList` scope.

For #26531

```scala
class Builder[T] { def accept[M <: T] }
```

`tp.typeSymbol` looks it's underlying/bound instead of the type parameter itself. So, `M <: T` became `T`.

---

**How this commit fix**

The real problem is in earlier on the pipeline, before `GenericSignatures`. When `Mixin` copies the setter, owner and type info as-is from parent. (`MyAbstract`'s setter still `Map[MyTrait.S, String]`, but it should be `Map[MyAbstract.S, String]`).

This time, we use `asSeenFrom` for `mixinGenericInfo` so the setter type is `MyTrait`.

## Have you relied on LLM-based tools in this contribution?

Yes, and I checked the output by review and regression tests.

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)
Covered by existing tests (this is a refactoring)

### CODE REVIEW

File: compiler/src/dotty/tools/backend/jvm/GenericSignatures.scala [hunk 1]
```diff
@@ -226,13 +226,9 @@ object GenericSignatures {
                 // value classes cannot appear as generic arguments
                 jsig(res, vcBoxing = ValueClassBoxing.Box)
           case _ =>
-            val typeSym = tp.typeSymbol
-            if typeSym.isTypeParam then
-              typeParamSig(typeSym.name)
-            else
+            boxedSig(tp.widenDealias.widenNullaryMethod)
```
Comment (tanishiking) [inline compiler/src/dotty/tools/backend/jvm/GenericSignatures.scala:229]: reverting https://github.com/scala/scala3/pull/26374

**Review by jchyb — APPROVED** [review]
LGTM! Thank you for all of the explanations!
