### ISSUE TITLE
Regression(?) in kubukoz/slick-effect - type projections in separate compilation runs

### ISSUE THREAD

**Issue by jchyb** [scala/scala3#22581]
OpenCB: https://github.com/VirtusLab/community-build3/actions/runs/13209505213/job/36881103468
## Compiler version

Working(?): 3.6.3
Broken(?): 3.6.4-RC1

## Minimized code
Has to be split into 2 modules/separate compilation runs, for simplicity let's use scala-cli:

main.scala
```Scala
package slickeffect

object Transactor {
  def fromDatabase(dbF: JdbcBackend#Database): Unit = ???
}

trait JdbcProfile {
  val backend: JdbcBackend = ??? 
}
object H2Profile extends JdbcProfile

trait JdbcBackend {
  type Database = DatabaseFactory
  val Database: DatabaseFactory = ???

  class DatabaseFactory {
    def forURL(url: String): DatabaseFactory = ???
  }
}

```
main.test.scala
```scala
package slickeffect

class TransactorTests {
  Transactor.fromDatabase(H2Profile.backend.Database.forURL("jdbc:h2:mem:"))
}
```

`scala-cli test main.scala main.test.scala`

## Output
In 3.6.4-RC1 and before - no error.
In 3.7.0-RC1-bin-20250207-d60a914-NIGHTLY:
```scala
[error] -- [E007] Type Mismatch Error: /Users/jchyb/workspace/slick-effect/transactor/src/main/scala/slickeffect/Transactor.scala:28:61 
[error] 28 |    Transactor.fromDatabase(H2Profile.backend.Database.forURL("jdbc:h2:mem:"))
[error]    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |                 Found:    slickeffect.H2Profile.backend.DatabaseFactory
[error]    |                 Required: slickeffect.JdbcBackend#Database
[error]    |
[error]    | longer explanation available when compiling with `-explain`
```

## Expectation
Not sure. Type projections like this should be unsupported in scala 3, and this error can also appear in previous compiler versions if both files are a part of the same compilation run. This leads me to believe this is more of a bugfix then regression, but I still wanted to log somewhere the OpenCB error and minimization.

**Comment by jchyb** [comment]
Errors in `melivinlou/hammer-scala` look similar https://github.com/VirtusLab/community-build3/actions/runs/13209436977/job/36880173932

**Comment by prolativ** [comment]
@jchyb Are you sure `JdbcBackend#Database` should be an illegal type projection? I'm looking at the specs https://docs.scala-lang.org/scala3/reference/dropped-features/type-projection.html and to me it's not quite clear if a trait should be considered an `abstract type`. Even if so, according to this specification and assuming I didn't miss something, changing `JdbcBackend` from a `trait` to a `class` should make this compile, but with the newest compiler this doesn't work either so IMO this is a regression anyway

**Comment by jchyb** [comment]
You are right, it also errors out with a class. What bothered me mainly was the fact that in 3.6.3 and earlier this error did appear, but only if both the type definition and method call were in the same compilation run, which led to to think the error might be correct (although, If I recall correctly, the compiler should just inform us directly if an illegal type projection is used).

**Comment by jchyb** [comment]
Same issue in `tminglei/slick-pg`: https://github.com/VirtusLab/community-build3/actions/runs/13209505213/job/36880970357
Clearer minimisation (same issue as before, has to be split into 2 compilation runs).
`main.scala`:
```scala
case class Test()(implicit proof: JdbcBackend#StreamingContext <:< JdbcBackend#Context)

class JdbcBackend:
  type Context = JdbcActionContext
  type StreamingContext = JdbcStreamingActionContext

  class JdbcStreamingActionContext extends JdbcActionContext
  class JdbcActionContext
```
`main.test.scala`:
```scala
val _ = new Test()
```

**Comment by Gedochao** [comment]
Last good release: 3.6.4-RC1-bin-20241121-5d1d274-NIGHTLY
First bad release: 3.6.4-RC1-bin-20241122-64411b6-NIGHTLY

26ecda540b93fbe1fc7be030559a78dd2db364f2 is the first bad commit

**Comment by mbovel** [comment]
Further minimized (I think?):

```scala
// a.scala
package slickeffect

def fromDatabase(dbF: JdbcBackend#Database): Unit = ???

class JdbcBackend:
  type Database = DatabaseFactory
  val Database: DatabaseFactory = ???
  class DatabaseFactory
```

```scala
// b.scala
package slickeffect

@main def main =
  val backend = JdbcBackend()
  fromDatabase(new backend.Database())
```
```
➜  ~/scala-snippets-6/22581 scala a.scala b.scala
Warning: setting /Users/mbovel/scala-snippets-6/22581 as the project root directory for this run.
Compiling project (Scala 3.5.1, JVM (21))
[error] ./b.scala:5:16
[error] Found:    backend.DatabaseFactory
[error] Required: slickeffect.JdbcBackend#Database
[error]   fromDatabase(new backend.Database())
[error]                ^^^^^^^^^^^^^^^^^^^^^^
Error compiling project (Scala 3.5.1, JVM (21))
Compilation failed
```

**Comment by prolativ** [comment]
@mbovel This seems like another issue: the reported problem is a regression from 3.6.3, while your snippet doesn't seem to compile in any version of scala 3. Just to double-check I rewrote it to something scala-2-compatible:
```scala
package slickeffect

class JdbcBackend {
  type Database = DatabaseFactory
  val Database: DatabaseFactory = ???
  class DatabaseFactory
}

object App {
  def fromDatabase(dbF: JdbcBackend#Database): Unit = ???

  def main(args: Array[String]) = {
    val backend = new JdbcBackend()
    fromDatabase(new backend.Database())
  }
}
```
This compiles in scala 2.13.16, but doesn't in any version of scala 3

**Comment by mbovel** [comment]
Thanks @prolativ for trying with other versions!

Given that my singe-file reproduction doesn't compile any version of Scala 3, I don't see why the version split in two compilation units should compile. I agree with @jchyb's analysis: maybe this should never be valid and the compiler inform us that an illegal type projection is used.

**Comment by Gedochao** [comment]
cc @odersky

**Comment by mbovel** [comment]
Running my single-file reproduction above with `--explain`:

```
sbt:scala3> scalac --explain playground.scala
[info] running (fork) dotty.tools.dotc.Main -d /Users/mbovel/dotty/compiler/../out/default-last-scalac-out.jar -classpath /Users/mbovel/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar:/Users/mbovel/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.7.1-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.7.1-RC1-bin-SNAPSHOT.jar --explain playground.scala
-- [E007] Type Mismatch Error: playground.scala:13:15 --------------------------
13 |  fromDatabase(new backend.Database())
   |               ^^^^^^^^^^^^^^^^^^^^^^
   |               Found:    backend.DatabaseFactory
   |               Required: slickeffect.JdbcBackend#Database
   |----------------------------------------------------------------------------
   | Explanation (enabled by `-explain`)
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |
   | Tree: new backend.Database()
   | I tried to show that
   |   backend.DatabaseFactory
   | conforms to
   |   slickeffect.JdbcBackend#Database
   | but none of the attempts shown below succeeded:
   |
   |   ==> backend.DatabaseFactory  <:  slickeffect.JdbcBackend#Database  = false
   |
   | The tests were made under the empty constraint
    ----------------------------------------------------------------------------
1 error found
[error] Nonzero exit code returned from runner: 1
```

**Comment by odersky** [comment]
The example compiles OK if I replace `Database` by `DatabaseFactory`.
```scala
package slickeffect

class JdbcBackend {
  type Database = DatabaseFactory
  val Database: DatabaseFactory = ???
  class DatabaseFactory
}

object App {
  def fromDatabase(dbF: JdbcBackend#DatabaseFactory): Unit = ???

  def main(args: Array[String]) = {
    val backend = new JdbcBackend()
    fromDatabase(new backend.Database())
  }
}
```
So it looks like this should compile, since type aliases should not matter for subtyping checks.

**Comment by odersky** [comment]
Since the originally reported problem has the same underlying configuration as @mbovel's minimization, I guess it worked by accident before and rightly should not work anymore. Easy workaround: Don't use type aliases in type projection, expand to the original class instead.

**Comment by Gedochao** [comment]
cc @kubukoz

**Comment by kubukoz** [comment]
Thanks :) I do like the idea of not allowing `JdbcBackend#Database` to be used at all.

**Comment by odersky** [comment]
Yes, I think we should at least issue a warning.
