### ISSUE TITLE
Incompatible TASTy version silently ignored when used in macros

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21244]
## Compiler version
All Scala versions, tested using `3.6.0-RC1-bin-20240719-af933c4-NIGHTLY`

## Minimized code

```Scala
// Published using 3.1.2-RC2
//> using dep "com.typesafe.play::play-json:2.10.0-RC6"

// Published using 3.3.1, uncomment and remove previous dependency to make it compile
// //> using dep "com.typesafe.play::play-json:2.10.0"

import play.api.libs.json.{Json, Format}
case class Foo(field: Int)

object JsonFormats:
  implicit val namespaceStatsFormat: Format[Foo] = Json.format[Foo]
```

## Output

```scala
-- [E006] Not Found Error: /Users/wmazur/projects/sandbox/src/main/scala/test.scala:10:62 
10 |  implicit val namespaceStatsFormat: Format[NamespaceStats] = Json.format[NamespaceStats]
   |                                                              ^^^^
   |                                                         Not found: Json
   |
```

## Expectation
The compiler should detect incompatible TASTy versions and print informative messages about it.

**Comment by prolativ** [comment]
Actually, this produces a compilation error from 3.4.0 until the current nightly (3.8.5-RC1-bin-20260420-a3bfb09-NIGHTLY),
crashes the compiler in 3.3.0 but compiles fine with LTS 3.3.x from 3.3.1 to the currently latest one 3.3.7

**Comment by prolativ** [comment]
Minimized without external dependencies:

build.sh:
```shell
#!/usr/bin/env bash
set -euo pipefail

# Reproducer for https://github.com/scala/scala3/issues/21244
# "Incompatible TASTy version silently ignored when used in macros"
#
# Expected: when using a macro library compiled with an older Scala version,
#           the compiler should emit a TASTy incompatibility warning.
# Actual:   the compiler silently loads the incompatible JAR and emits
#           a confusing "Field not found: Foo.field" error with no TASTy diagnostic.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCALA_VERSION="${1:-3.8.3}"   # pass a version as first arg, e.g. ./build.sh 3.6.4

cd "$SCRIPT_DIR"
rm -rf .out && mkdir -p .out

echo "=== Building macro-lib with Scala 3.1.2-RC2 ==="
scala-cli package --library --jvm 11 -f -o .out/macro-lib.jar lib

echo ""
echo "=== Compiling consumer with Scala 3.1.2-RC2 — succeeds (macro works with its own version) ==="
scala-cli compile -S 3.1.2-RC2 --jvm 11 --extra-jars .out/macro-lib.jar consumer

echo ""
echo "=== Compiling consumer with Scala $SCALA_VERSION — expect TASTy warning, but get 'Field not found' ==="
scala-cli compile -S "$SCALA_VERSION" --extra-jars .out/macro-lib.jar consumer
```

consumer/test.scala:
```scala
case class Foo(field: Int)

val enc = Lib.format[Foo]
```

lib/Lib.scala:
```scala
//> using scala 3.1.2-RC2

import scala.quoted.*
import scala.deriving.Mirror

trait Encoder[T]:
  def encode(value: T): String

object Lib:
  inline def format[T](using Mirror.ProductOf[T]): Encoder[T] = ${ formatImpl[T] }

  def formatImpl[T: Type](using Quotes): Expr[Encoder[T]] =
    import quotes.reflect.*

    @annotation.tailrec
    def elementTypes(max: Int, tpes: List[TypeRepr], ts: List[TypeRepr]): List[TypeRepr] =
      tpes.headOption match
        case Some(AppliedType(ty, a :: b :: Nil)) if ty <:< TypeRepr.of[*:] && max > 0 =>
          elementTypes(max - 1, b :: tpes.tail, a :: ts)
        case Some(AppliedType(ty, as)) if ty <:< TypeRepr.of[Tuple] && as.size <= max =>
          elementTypes(max - as.size, as ::: tpes.tail, ts)
        case Some(t) if t =:= TypeRepr.of[EmptyTuple] =>
          elementTypes(max, tpes.tail, ts)
        case Some(TypeBounds(t, _)) =>
          elementTypes(max, t :: tpes.tail, ts)
        case Some(t) =>
          elementTypes(max, tpes.tail, t :: ts)
        case _ =>
          ts.reverse

    val pof = Expr.summon[Mirror.ProductOf[T]].getOrElse(
      report.errorAndAbort(s"No Mirror.ProductOf for ${TypeRepr.of[T].show}")
    )

    val ownerSym = TypeRepr.of[T].typeSymbol

    val (labelTpes, typeTpes) = pof.asTerm.tpe match
      case Refinement(
            Refinement(_, _, TypeBounds(t1 @ AppliedType(tycon1, _), _)),
            _,
            TypeBounds(t2 @ AppliedType(tycon2, _), _)
          ) if tycon1 <:< TypeRepr.of[Product] && tycon2 <:< TypeRepr.of[Product] =>
        (t2, t1)
      case _ =>
        report.errorAndAbort(s"Unexpected Mirror shape for ${TypeRepr.of[T].show}")

    val labels = elementTypes(Int.MaxValue, List(labelTpes), List.empty)
      .collect { case ConstantType(StringConstant(n)) => n }
    val types  = elementTypes(labels.size, List(typeTpes), List.empty)

    // Reconstruct scala.TupleN type from element types (play-json's approach)
    val tupleTpr =
      if types.isEmpty then TypeRepr.of[EmptyTuple]
      else TypeRepr.typeConstructorOf(Class.forName(s"scala.Tuple${types.size}")).appliedTo(types)

    // Build field map: field name → tuple accessor (via declaredMethod)
    val fieldMap: Map[String, Symbol] = labels.zipWithIndex.flatMap { case (label, i) =>
      tupleTpr.typeSymbol.declaredMethod(s"_${i + 1}").headOption.map(label -> _)
    }.toMap

    // Validate all labels map to tuple accessors
    labels.foreach { name =>
      if !fieldMap.contains(name) then
        report.errorAndAbort(s"Field not found: ${ownerSym.name}.$name")
    }

    '{ new Encoder[T] { def encode(value: T): String = ${ Expr(labels.mkString(", ")) } } }
```
