### PR TITLE
Ignore annotations no longer on the classpath in ExtractAPI

### LINKED ISSUE #25722: Regression: Cannot extend non-static Java inner interface
I use sentry library `io.sentry:sentry-logback:8.37.1` which has `SentryOptions` class with `BeforeSendCallback` interface. If I implement the interface in Scala I get the following errors on compilation

```
[error] no member new Any . <init>
[error] value <none>: <notype> does not take parameters
[error] Internal error in the incremental compiler while compiling .../server/src/main/util/CustomCallback.scala: Unhandled type <error unspecified error> of class class dotty.tools.dotc.core.Types$UnspecifiedErrorType$
[error] three errors found
[error] (server / Compile / compileIncremental) Compilation failed
[error] Total time: 7 s, completed Apr 7, 2026, 7:32:10 PM
```

This code works fine on 3.8.1

## Compiler version

3.8.3

## Minimized code

java class

```java
public class SentryOptions {
  ...
  /** The BeforeSend callback */
  public interface BeforeSendCallback {

    /**
     * Mutates or drop an event before being sent
     *
     * @param event the event
     * @param hint the hints
     * @return the original event or the mutated event or null if event was dropped
     */
    @Nullable
    SentryEvent execute(@NotNull SentryEvent event, @NotNull Hint hint);
  }
  ...
}
```

Scala class

```scala
class CustomCallback extends SentryOptions.BeforeSendCallback {

  override def execute(event: SentryEvent, hint: Hint): SentryEvent = event
}
```

## Expectation

Scala class `CustomCallback` should inherit the Java interface.

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #25722

## How much have you relied on LLM-based tools in this contribution?

Not at all

## How was the solution tested?

Automated test

~~Manual tests because writing automated tests is impractical, described below (in detail)~~

~~See the issue, it requires compiling some Java code, then manipulating the JAR to remove one classfile...~~

### CODE REVIEW

**Comment by prolativ** [comment]
Actually, this PR https://github.com/scala/scala3/pull/12592/changes seems to contain a reference to how to write a compilation test excluding something from the classpath at a desired stage

**Comment by SolalPirelli** [comment]
Nice find! I added a test, and confirmed that the test fails without the fix

**Review by prolativ — APPROVED** [review]
