### ISSUE TITLE
Mixin forwarder signature points to a nonexistent nested class owned by the subclass

### ISSUE THREAD

**Issue by He-Pin** [scala/scala3#26532]
## Compiler version

- 3.9.0-RC1
- 3.9.0-RC2
- 3.9.0-RC3
- 3.10.0-RC1-bin-20260712-f51c618-NIGHTLY

The same code works with 3.8.3, so the regression starts in 3.9.0-RC1.

## Minimized code

`Repro.scala`:

```scala
package repro

trait Base[S, D] {
  final class Helper
  final def helper(): Helper = new Helper
}

abstract class Impl[S, D] extends Base[S, D]
```

`Use.java`:

```java
package repro;

final class Use {
  void test(Impl<String, Integer> impl) {
    impl.helper();
  }
}
```

Compile with:

```shell
scala-cli compile Repro.scala -S 3.9.0-RC3 --server=false -d out
javac -cp out -d out Use.java
```

## Output

```text
Use.java:5: error: cannot access Impl$Helper
    impl.helper();
        ^
  class file for repro.Impl$Helper not found
```

`javap -p -s repro.Impl` shows:

```java
public final repro.Impl<S, D>.Helper helper();
  descriptor: ()Lrepro/Base$Helper;
```

The descriptor correctly refers to the class that exists, `Base$Helper`, while the generic `Signature` attribute refers to nonexistent `Impl$Helper`. With 3.8.3, the method is exposed as:

```java
public final repro.Base$Helper helper();
  descriptor: ()Lrepro/Base$Helper;
```

## Expectation

`Helper` is declared in `Base`, and the only generated nested class is `Base$Helper`. A mixin forwarder's generic signature must not relocate that class to `Impl`. It should either refer to `Base[S, D]#Helper` / `Base$Helper` consistently with the descriptor, or omit a redundant signature.

This breaks Java subclasses in [Apache Pekko PR #3303](https://github.com/apache/pekko/pull/3303): the compiler emits an `AbstractFSM[S,D].TransformHelper` return signature although the actual class is `FSM$TransformHelper`, and javac fails before the Java test can run. This appears related to generic-signature work around #24619 and #25880, but those issues do not cover this nonexistent-owner case.

**Comment by Gedochao** [comment]
Last good release: 3.9.0-RC1-bin-20260526-cf3cc7a-NIGHTLY
First bad release: 3.10.0-RC1-bin-20260527-2d9fc64-NIGHTLY

the culprit is ee36dd00db (#25880)
cc @SolalPirelli @tanishiking

**Comment by He-Pin** [comment]
The pekko's current code base can compile with Scala 3.8.4.
