### ISSUE TITLE
Unexpected typer error with Scala 3.3.7

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/scala3#24165]
## Compiler version

3.3.7

## Minimized code

No minimization yet, only steps to reproduce so far:

1. Clone reproducing sbt project:
```sh
git clone --depth 1 https://github.com/plokhotnyuk/jsoniter-scala
```

2. Switch to the affected branch:
```sh
git checkout scala-3.3.7
```

3. Run the following sbt command:
```sh
sbt ++3.3.7 jsoniter-scala-macrosJVM/test
```

## Output

The following compilation error in the typer for the macro generated code:
```
[error]     |               |
[error]     |               |Error:
[error]     |               |assertion failed: Type Mismatch (while checking adapt):
[error]     |Found:    (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |  com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight) |
[error]     |  (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |    com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)
[error]     |Required: (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |  com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)
[error]     |I tried to show that
[error]     |  (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |  com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight) |
[error]     |  (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |    com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)
[error]     |conforms to
[error]     |  (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |  com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)
[error]     |but none of the attempts shown below succeeded:
[error]     |
[error]     |  ==> (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :   com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight) |   (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :     com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)  <:  (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :   com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)
[error]     |  <== (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :   com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight) |   (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :     com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)  <:  (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :   com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight) = false
[error]     |
[error]     |The tests were made under the empty constraint
[error]     |tree = if in.isNextToken(123) then
[error]     |  {
[error]     |    in.rollbackToken()
[error]     |    in.skip()
[error]     |    com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green
[error]     |  }
[error]     | else 
[error]     |  in.readNullOrTokenError[
[error]     |    
[error]     |      (com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight.Green :
[error]     |        com.github.plokhotnyuk.jsoniter_scala.macros.TrafficLight)
[error]     |    
[error]     |  ](default, 123)
```

## Expectation

No compilation errors

**Comment by tgodzik** [comment]
Thanks for reporting! Curiously, this was working in the community build https://github.com/VirtusLab/community-build3/actions/runs/18031767030/job/51309613423

So I wonder why this broke only on update to 3.3.7

**Comment by tgodzik** [comment]
Looks like it's working on Next 3.7.3, so broken only on LTS

**Comment by plokhotnyuk** [comment]
The workaround is adding an extra `.asInstanceOf[T]`, like here: 
https://github.com/plokhotnyuk/jsoniter-scala/commit/9e90a575a85a91981ce8fee0d2d23f7d62737d68#diff-2dd71e1f25e398ff5a215b7e53125b9d77f7744a1477c2f421789f29da33ccaeR2838

**Comment by tgodzik** [comment]
Looks like it was working in 2.37.11, which is why at that point the compilation passed.

**Comment by WojciechMazur** [comment]
> So I wonder why this broke only on update to 3.3.7

It might be related to new version of jsoniter. The 3.3.7-RC2 was tested [2025-09-26](https://virtuslab.github.io/community-build3/2025/09/26/3.3.7-rc2.html) using the v2.37.11 of jsoniter. 

The testing locally it successfully compiles against 2.38.1 but fails since 2.38.2 
The OpenCB is [now using](https://github.com/VirtusLab/community-build3/blob/cebda1fcc66cb9c009d562ff26796a359af46319/.github/workflows/buildConfig.json#L45179) the latest versions [2.38.3](https://index.scala-lang.org/plokhotnyuk/jsoniter-scala/artifacts/jsoniter-scala-core/2.38.3) released October 1 
Configs are updated weekly (every Friday). That's probably why it was not caught earlier.

**Comment by tgodzik** [comment]
Yeah, the change here caused the bug to surface https://github.com/plokhotnyuk/jsoniter-scala/compare/v2.38.1...v2.38.2

**Comment by plokhotnyuk** [comment]
> Yeah, the change here caused the bug to surface [plokhotnyuk/jsoniter-scala@v2.38.1...v2.38.2](https://github.com/plokhotnyuk/jsoniter-scala/compare/v2.38.1...v2.38.2)

Thanks, the regression was caught by the following change of `Ref(sym).tpe` to `sym.termRef`: 
https://github.com/plokhotnyuk/jsoniter-scala/compare/v2.38.1...v2.38.2#diff-2dd71e1f25e398ff5a215b7e53125b9d77f7744a1477c2f421789f29da33ccaeL1277

I've reverted it [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/e424dc59718ae4f59ab0592d872357eaa664ab8c#diff-2dd71e1f25e398ff5a215b7e53125b9d77f7744a1477c2f421789f29da33ccaeL1311) already
