### ISSUE TITLE
separate compilation of top level overloaded methods can't be selected

### ISSUE THREAD

**Issue by ntnj** [scala/scala3#18673]
## Compiler version

3.4.0-RC1-bin-20231006-b1ccc6a-NIGHTLY

## Minimized code

a.scala

```Scala
import language.experimental.relaxedExtensionImports
class A
extension (a: A)
  def f = "a"
```
b.scala
```Scala
import language.experimental.relaxedExtensionImports
class B
extension (b: B)
  def f = "b"
```
main.scala
```Scala
import language.experimental.relaxedExtensionImports
@main def main() =
  val a = A()
  println(a.f)
```

Replit Link: https://replit.com/@replitit1/TubbyHighlevelCoordinate

## Output

Compile error (edit: when compiled together)
```scala
[error] -- [E161] Naming Error: /home/runner/TubbyHighlevelCoordinate/b.scala:6:6 ------
[error] 6 |  def f = "b"
[error]   |  ^^^^^^^^^^^
[error]   |f is already defined as method f in /home/runner/TubbyHighlevelCoordinate/a.scala
[error]   |
[error]   |Note that overloaded methods must all be defined in the same group of toplevel definitions
[error] one error found
```

Edit: when compiled separately (a, then b, then main) - another error:
```scala
-- [E008] Not Found Error: main.scala:6:12 -------------------------------------
6 |  println(a.f)
  |          ^^^
  |        value f is not a member of example.A.
  |        An extension method was tried, but could not be fully constructed:
  |
  |            example.f(a)
  |
  |            failed with:
  |
  |                Found:    (a : example.A)
  |                Required: example.B
1 error found
```

## Expectation

```
a
```

https://github.com/lampepfl/dotty/issues/16920 fixed this issue when extension methods with same names are imported from different objects, but it doesn't seem to work when extensions are defined at top level across multiple files.

**Comment by Ichoran** [comment]
The very annoying but possible workaround is to create a third file that has all the extensions that collide in it.

Unlike the multiple-namespace situation, which has no workaround save for `relaxedExtensionImports`, this at least is possible.

**Comment by bishabosha** [comment]
I can't really call this a bug, the error is very clear: "overloaded methods must all be defined in the same group of toplevel definitions" this is more a feature request.

**Comment by bishabosha** [comment]
we can minimise further by not using extension methods at all (compiled separately:

```scala
// a.scala
class A
def f(a: A) = "a"
```

```scala
// b.scala
class B
def f(b: B) = "b"
```

```scala
// main.scala
@main def main() =
  val a = A()
  println(f(a))
```

producing

```scala
-- [E007] Type Mismatch Error: main.scala:3:12 ---------------------------------
3 |  println(f(a))
  |            ^
  |            Found:    (a : A)
  |            Required: B
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

**Comment by som-snytt** [comment]
This cannot be a bug in general. I may wish to insert my monkeypatched class at any time.

It's a bit weird that, compiling to the same output dir, it compiles fine if I switch the order.

Does the classpath implementation ingest class files in file creation order? It would at least be consistent if it were stably sorted (by name instead of time stamp). Currently, "last compiled wins" from different files.

Related issue about companionship: https://github.com/scala/scala3/issues/20510

The compiler can offer assistance to avoid obvious pitfalls (just at the class path level, aside from language-level correctness).

**Comment by som-snytt** [comment]
Arguably, the "already defined" error in joint compilation is wrong, because the definitions can happily co-exist:
```
p.a$package.f(a) // works
```
Possibly, joint compilation should warn, and under separate compilation, opening a package object `p.a$package` should require scanning all sibling package objects `p.x$package`. That is not an undue burden.

Then, use of such a "split overload" is never permitted: `p.f` is disallowed, but `p.a$package.f` is fine.

Importing doesn't work (yet):
```
8 |  import p.a$package.f
  |         ^^^^^^^^^^^
  |         value a$package is not a member of p
```
but the expectation is that if I import from both package objects, I get the handy extension overloading.

Footnote: importing from the package object must have precedence over the package-level binding, which is lowest precedence.

The difference in behavior in separate compilation (where it might pick up either method depending on compilation order or the class path implementation) is clearly just a bug. The ordinary limitation of the class path mechanism is that first resolution wins, so the strong assertion here is that inferring member `p.f` from either package object member `f` requires a guarantee that it is unique.
