### ISSUE TITLE
Cannot do a map on a Map with Scala 3, with Scala 2.l13 it works ok

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [scala/scala3#21367]
## Compiler version

- Java 21
- Scala 3.3.3 (and 3.4.2)

## Minimized code

This interactive scala-cli session shows the problem:
```
❯ scala-cli -j system --dep org.python:jython-standalone:2.7.1b3 -S 3.3.3
Welcome to Scala 3.3.3 (21.0.3, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

cala> import org.python.core.*
                                                                                                                                          
scala> import scala.jdk.CollectionConverters.*
                                                                                                                                          
scala> val p = new PyDictionary
val p: org.python.core.PyDictionary = {}

scala> p.asScala
-- [E008] Not Found Error: -----------------------------------------------------
1 |p.asScala
  |^^^^^^^^^
  |value asScala is not a member of org.python.core.PyDictionary
1 error found

cala> (p: java.util.Map[?, ?]).asScala
val res0: scala.collection.mutable.Map[?, ?] = Map()
                                                                                                                                          
scala> (p: java.util.Map[Any, Any]).asScala.map { case (k,v) => (k, v) }
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |(p: java.util.Map[Any, Any]).asScala.map { case (k,v) => (k, v) }
  | ^
  | Found:    (p : org.python.core.PyDictionary)
  | Required: java.util.Map[Any, Any]
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

Comparison with Scala 2.13.14:

```
 scala-cli -j system --dep org.python:jython-standalone:2.7.1b3 -S 2.13.14
Welcome to Scala 2.13.14 (OpenJDK 64-Bit Server VM, Java 21.0.3).
Type in expressions for evaluation. Or try :help.

scala> import org.python.core._
import org.python.core._

scala> import scala.jdk.CollectionConverters._
import scala.jdk.CollectionConverters._

scala> val p = new PyDictionary
val p: org.python.core.PyDictionary = {}

scala> p.asScala
val res0: scala.collection.concurrent.Map[_, _] = Map()

scala> p.asScala.map{case(k,v) => (k,v) }
val res1: scala.collection.mutable.Map[Object,Object] = HashMap()
```

## Output

Error compiles

## Expectation

Code does compile o error message can be unsderstood.
With Scala 2.13.14 it compiles.

In addition, with Scala 2.13 I don't need a type adscription to Map.

## Notes:

PyDictionary is defined like this:
```Java
public class PyDictionary extends AbstractDict implements ConcurrentMap, Traverseproc {
   ...
}
```

```Java
public interface ConcurrentMap<K,V> extends Map<K,V> {
   ...
}
```

**Comment by DavidPerezIngeniero** [comment]
A workaorund is to define an intermediate variable:
```Scala
val p2 = (p: Map[?, ?]).asScala
p2.map { case (k, v) => (k, v) }
````

**Comment by SethTisue** [comment]
> A consider a bug to behave differently just for defining an intermediate variable

That's an incorrect expectation, at least in general. It can perhaps be defended in specific cases, but it has to specifically defended, you can't just point at the general principle and be done, since the general principle does not exist,. Type inference in Scala 3 processes entire expressions. It's normal that the overall result might be different if you first give the type checker only part of the expression to work with, forcing it to decide on an answer based on partial information, and then only later give it the rest.

**Comment by SethTisue** [comment]
Is the reproducible without involving an external dependency...?

**Comment by DavidPerezIngeniero** [comment]
> Is the issue reproducible without involving an external dependency...?

I don't know, but the code I've shown it is quite simple and reduced.

**Comment by DavidPerezIngeniero** [comment]
> > A consider a bug to behave differently just for defining an intermediate variable
> 
> That's an incorrect expectation, at least in general. It can perhaps be defended in specific cases, but it has to specifically defended, you can't just point at the general principle and be done, since the general principle does not exist. Type inference in Scala 3 processes entire expressions. It's normal that the overall result might be different if you first give the type checker only part of the expression to work with, forcing it to decide on an answer based on partial information, and then only later give it the rest.

At least I don´t expect different results if I split an expression using an intermediate variable.

**Comment by SethTisue** [comment]
> I don't know, but the code I've shown it is quite simple and minimalistic.

Regardless, reproducing it without an external dependency is considered the standard for bug reporting.

**Comment by prolativ** [comment]
Minimized in 2 variants, compiled with scala 2.13.14 and 3.8.3.
Interestingly, when we compile java first and scala after that, that indeed compiles successfully for scala 2 and reports and error for scala 3. However, when compiled together, that's a compilation error for scala 2 and a compiler crash for scala 3.
Using scala-cli's test scope to enforce separate compilation

build.sh:
```shell
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCALA3_VERSION="${SCALA_VERSION:-3.8.3}"

cd "$SCRIPT_DIR"

# Scenario 1: Java in main scope, Scala in test scope (Main.test.scala)
# Scala 2.13.14 → success; Scala 3 → compile error
echo "--- Scala 2.13.14, test scope (expect: success) ---"
scala-cli compile --test -S 2.13.14 RawMap.java Main.test.scala

echo "--- Scala $SCALA3_VERSION, test scope (expect: compile error) ---"
scala-cli compile --test -S "$SCALA3_VERSION" RawMap.java Main.test.scala || true


# Scenario 2: Java + Scala in main scope
# Scala 2.13.14 → compile error; Scala 3 → compiler crash
echo "--- Scala 2.13.14, main scope (expect: compile error) ---"
scala-cli compile -S 2.13.14 RawMap.java Main.scala || true

echo "--- Scala $SCALA3_VERSION, main scope (expect: compiler crash) ---"
scala-cli compile -S "$SCALA3_VERSION" RawMap.java Main.scala || true
```

Main.scala:
```scala
import scala.jdk.CollectionConverters._

object Test {
  // i21367: asScala not available on raw Java ConcurrentMap implementors in Scala 3; works in Scala 2.13
  def test(m: RawMap): Unit =
    m.asScala.map { case (k, v) => (k, v) }
}
```

Main.test.scala:
```scala
import scala.jdk.CollectionConverters._

object Test {
  // i21367: asScala not available on raw Java ConcurrentMap implementors in Scala 3; works in Scala 2.13
  def test(m: RawMap): Unit =
    m.asScala.map { case (k, v) => (k, v) }
}
```

RawMap.java:
```java
import java.util.*;
import java.util.concurrent.ConcurrentMap;

// Raw (unparameterized) ConcurrentMap — mirrors PyDictionary which implements ConcurrentMap (raw)
public class RawMap extends AbstractMap implements ConcurrentMap {
    public Set entrySet() { return Collections.emptySet(); }
    public Object putIfAbsent(Object key, Object value) { return null; }
    public boolean remove(Object key, Object value) { return false; }
    public boolean replace(Object key, Object oldValue, Object newValue) { return false; }
    public Object replace(Object key, Object value) { return null; }
}
```

<details>
--- Scala 2.13.14, test scope (expect: success) ---
Warning: setting /Users/mpalka/Projects/scala3/local/repro/i21367/github as the project root directory for this run.
--- Scala 3.8.3, test scope (expect: compile error) ---
Warning: setting /Users/mpalka/Projects/scala3/local/repro/i21367/github as the project root directory for this run.
Compiling project (test, Scala 3.8.3, JVM (25))
[error] ./Main.test.scala:6:5
[error] value asScala is not a member of RawMap
[error]     m.asScala.map { case (k, v) => (k, v) }
[error]     ^^^^^^^^^
Error compiling project (test, Scala 3.8.3, JVM (25))
Compilation failed
--- Scala 2.13.14, main scope (expect: compile error) ---
Warning: setting /Users/mpalka/Projects/scala3/local/repro/i21367/github as the project root directory for this run.
Compiling project (Scala 2.13.14, JVM (25))
[error] ./Main.scala:6:5
[error] value asScala is not a member of RawMap
[error]     m.asScala.map { case (k, v) => (k, v) }
[error]     ^^^^^^^^^
Error compiling project (Scala 2.13.14, JVM (25))
Compilation failed
--- Scala 3.8.3, main scope (expect: compiler crash) ---
Warning: setting /Users/mpalka/Projects/scala3/local/repro/i21367/github as the project root directory for this run.
Compiling project (Scala 3.8.3, JVM (25))
[error] ./RawMap.java:5:14
[error] bad parameter reference RawMap.this.V at typer
[error] the parameter is type V in trait ConcurrentMap but the prefix (RawMap.this : RawMap)
[error] does not define any corresponding arguments.
[error] idx = 1, args = ,
[error] constraint =  uninstantiated variables:
[error]  constrained types:
[error]  bounds:
[error]  ordering:
[error]  co-deps:
[error]  contra-deps:
[error] public class RawMap extends AbstractMap implements ConcurrentMap {
[error]              ^

  exception occurred while checkingJava /Users/mpalka/Projects/scala3/local/repro/i21367/github/RawMap.java

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: /Users/mpalka/Projects/scala3/local/repro/i21367/github/RawMap.java
        during phase: typer
                mode: Mode(ImplicitsEnabled)
     library version: version 3.8.3
    compiler version: version 3.8.3
            settings: -bootclasspath /Users/mpalka/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.8.3/scala3-library_3-3.8.3.jar:/Users/mpalka/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/3.8.3/scala-library-3.8.3.jar -classpath /Users/mpalka/Projects/scala3/local/repro/i21367/github/.scala-build/.bloop/github_4b3f755af1-eb053adb5c/bloop-internal-classes/main-e-bivzgxSEamIjphCtWoDQ==:/Users/mpalka/Projects/scala3/local/repro/i21367/github/.scala-build/github_4b3f755af1-eb053adb5c/classes/classes-empty-github_4b3f755af1-eb053adb5c -d /Users/mpalka/Projects/scala3/local/repro/i21367/github/.scala-build/.bloop/github_4b3f755af1-eb053adb5c/bloop-internal-classes/main-e-bivzgxSEamIjphCtWoDQ== -sourceroot /Users/mpalka/Projects/scala3/local/repro/i21367/github

Error compiling project (Scala 3.8.3, JVM (25))
Error: dotty.tools.dotc.ast.Trees$UnAssignedTypeException: type of TypeTree is not assigned
        at dotty.tools.dotc.ast.Trees$Tree.tpe(Trees.scala:77)
        at dotty.tools.dotc.typer.Checking$.checkAppliedTypesIn(Checking.scala:172)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:15)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1771)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1778)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1775)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1683)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1685)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1784)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.typer.JavaChecks$.check(JavaChecks.scala:25)
        at dotty.tools.dotc.typer.TyperPhase.javaCheck$$anonfun$1(TyperPhase.scala:58)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:533)
        at dotty.tools.dotc.typer.TyperPhase.javaCheck(TyperPhase.scala:59)
        at dotty.tools.dotc.typer.TyperPhase.$anonfun$6(TyperPhase.scala:108)
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:495)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:597)
        at scala.collection.immutable.List.prependedAll(List.scala:159)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.IterableOps$WithFilter.map(Iterable.scala:906)
        at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:107)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at dotty.tools.dotc.Run.showProgress(Run.scala:482)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:432)
        at dotty.tools.dotc.Run.compileSources(Run.scala:319)
        at dotty.tools.dotc.Run.compile(Run.scala:304)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:148)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$9(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:73)
        at bloop.tracing.NoopTracer$.trace(BraveTracer.scala:53)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:72)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$8(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:71)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1750)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1742)
        at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1659)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

Error: Unexpected error when compiling github_4b3f755af1-eb053adb5c: dotty.tools.dotc.ast.Trees$UnAssignedTypeException: type of TypeTree is not assigned
        at dotty.tools.dotc.ast.Trees$Tree.tpe(Trees.scala:77)
        at dotty.tools.dotc.typer.Checking$.checkAppliedTypesIn(Checking.scala:172)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:15)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1771)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1778)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1775)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1819)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1683)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1685)
        at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1784)
        at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1820)
        at dotty.tools.dotc.typer.JavaChecks$AppliedTypeChecker$.traverse(JavaChecks.scala:19)
        at dotty.tools.dotc.typer.JavaChecks$.check(JavaChecks.scala:25)
        at dotty.tools.dotc.typer.TyperPhase.javaCheck$$anonfun$1(TyperPhase.scala:58)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:533)
        at dotty.tools.dotc.typer.TyperPhase.javaCheck(TyperPhase.scala:59)
        at dotty.tools.dotc.typer.TyperPhase.$anonfun$6(TyperPhase.scala:108)
        at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:495)
        at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:597)
        at scala.collection.immutable.List.prependedAll(List.scala:159)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.IterableOps$WithFilter.map(Iterable.scala:906)
        at dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:107)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:380)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1324)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:373)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$2(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1$$anonfun$adapted$1(Run.scala:420)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at dotty.tools.dotc.Run.showProgress(Run.scala:482)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:420)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:432)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:432)
        at dotty.tools.dotc.Run.compileSources(Run.scala:319)
        at dotty.tools.dotc.Run.compile(Run.scala:304)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:148)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$9(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:73)
        at bloop.tracing.NoopTracer$.trace(BraveTracer.scala:53)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:72)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$8(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:71)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1750)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1742)
        at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1659)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

Compilation failed
</details>
