### PR TITLE
ClassfileParser: Compute permitted symbols lazily to avoid cyclic refs

### LINKED ISSUE #27108: `Cyclic reference involving` error in REPL
## Compiler version

- 3.10.1-RC1-bin-20260918-035a05a-NIGHTLY
- 3.10.0-RC2
- 3.9.0

### A.java

```java
package example;

public final class A implements C, D {}
```

### B.java

```java
package example;

public final class B {
  public final class E implements C, D {
  }
}
```

### C.java

```java
package example;

public sealed interface C permits A, B.E {
}
```

### D.java

```java
package example;

public sealed interface D permits A, B.E {
}
```

### build.sbt

```scala
scalaVersion := "3.9.0"
```

### project/build.properties

```properties
sbt.version=1.13.0
```

## Output

```
Welcome to Scala 3.9.0 (21.0.12, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                            
scala> classOf[example.A]
exception caught when loading trait D: Cyclic reference involving class E

 Run with -explain-cyclic for more details.
exception caught when loading class E: Cyclic reference involving class E

 Run with -explain-cyclic for more details.
exception caught when loading trait C: Cyclic reference involving class E

 Run with -explain-cyclic for more details.
exception caught when loading class A: Cyclic reference involving class E

 Run with -explain-cyclic for more details.
-- [E008] Not Found Error: -----------------------------------------------------
1 |classOf[example.A]
  |        ^^^^^^^^^
  |        type A is not a member of example
1 error found
```

## Expectation

no error.

## Note

- https://github.com/scala/bug/issues/13175#issuecomment-5739701205

no error

- Scala 3.3.8
- Scala 3.8.4

```
Welcome to Scala 3.8.4 (21.0.12, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                            
scala> classOf[example.A]
val res0: Class[example.A] = class example.A
```

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #27108

## Have you relied on LLM-based tools in this contribution?

No

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

### CODE REVIEW

**Review by Florian3k — APPROVED** [review]
LGTM
Just out of curiosity, do we know when this was introduced? (Since it was working in 3.8.4)

**Comment by SolalPirelli** [comment]
Not sure, I assumed it was the overall `sealed` PR but apparently not?
