### ISSUE TITLE
Missing outer accessor instead of error for export and ctor proxy

### ISSUE THREAD

**Issue by som-snytt** [scala/scala3#24879]
## Compiler version

3.8.1-RC1-bin-SNAPSHOT-nonbootstrapped
at 32e416e3c9f3377b4a03296caa1a80a573eb69fb 

## Minimized code

```Scala
class C:
  class D

class Baz:
  val c = new C
  export c.*

@main def Test =
  println:
    Baz().D()
```

## Output (click arrow to expand)

during erasure...

<details>

```scala
Exception in thread "main" java.lang.AssertionError: assertion failed: missing outer accessor in the top-level definitions in package <empty>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:10)
        at dotty.tools.dotc.transform.ExplicitOuter$.dotty$tools$dotc$transform$ExplicitOuter$$$outerParamAccessor(ExplicitOuter.scala:234)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.loop$1(ExplicitOuter.scala:458)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.path$extension(ExplicitOuter.scala:467)
        at dotty.tools.dotc.ast.tpd$.followOuterLinks(tpd.scala:520)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:492)
        at dotty.tools.dotc.ast.tpd$.singleton(tpd.scala:526)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.outerArg$1(ExplicitOuter.scala:413)
        at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.args$extension(ExplicitOuter.scala:421)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:823)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3790)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3884)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3971)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3976)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:4087)
        at dotty.tools.dotc.transform.Erasure$Typer.$anonfun$7(Erasure.scala:826)
        at dotty.tools.dotc.core.Decorators$.zipWithConserve(Decorators.scala:160)
        at dotty.tools.dotc.transform.Erasure$Typer.typedApply(Erasure.scala:826)
```
</details>

## Expected

as on `3.8.0-RC4`
```
25 |    Baz().D()
   |    ^^^^^^^^^
   |(Baz#c : C) is not a valid class prefix, since it is not an immutable path
   |
   | longer explanation available when compiling with `-explain`
1 error found
Compilation failed
```

**Comment by som-snytt** [comment]
Regression in https://github.com/scala/scala3/pull/24570 (which is not on `3.8.0-RC5`) where post-typer normally flags the prefix. But it's the same problem with stable prefix:
```
  class C() extends Object() {
    class D() extends Object() {}
  }
  class Baz() extends Object() {
    val c: C = new C()
    export this.c.*
    final type D = Baz.this.c.D
  }
  final lazy module val i15944$package: i15944$package = new i15944$package()
  final module class i15944$package() extends Object() {
    this: i15944$package.type =>
    @main def Test: Unit =
      {
        val baz: Baz = new Baz()
        println(new baz.D()) // was: new baz.c.D()
      }
  }
```
where at `explicitOuter`
```
    class D() extends Object() {
      private[this] val $outer: C
      final def C$D$$$outer: C = D.this.$outer
    }
```
and at `erasure`
```
new C.this.D(baz.c())
```
If it's not a "trivial" fix, I'd prefer using an attachment to solve the issue addressed on the previous PR.

Actually in the failing case, at refchecks
```
        val baz: Baz = new Baz()
        println(new Baz.this.D())
```
