### ISSUE TITLE
Wrong compiler error when no given was found for intersection type

### ISSUE THREAD

**Issue by road21** [scala/scala3#22846]
## Compiler version

3.3.5, 3.6.3

## Minimized code

```scala
trait TCl[A]
trait TCl2[A]

type Ctx

given [R]: TCl[R & Ctx] = null
//given [R]: TCl2[R & Ctx] = null // compiles ok when this line is uncommented

def lol[A: TCl: TCl2](foo: Unit = ()): Any = () // default argument is important (without it it doesn't reproduce)

lol[Int & Ctx]()
```

## Output

Compiler error:

```scala
Found:    Playground.TCl[R & Ctx]
Required: Playground.TCl[Int & Ctx]
```

## Expectation

Compiler error:

```scala
No given instance of type TCl2[Int & Ctx] was found
```

**Comment by som-snytt** [comment]
Currently fixed. (There were a few fixes around supplying implicits and defaults.)
```
➜  snips scala-cli compile --server=false -S 3.7.0-RC1 i22846.scala
-- [E172] Type Error: /home/amarki/snips/i22846.scala:13:18 --------------------
13 |  lol[Int & Ctx]()
   |                  ^
   |No given instance of type TCl2[Int & Ctx] was found for a context parameter of method lol
1 error found
Compilation failed
```

**Comment by Gedochao** [comment]
Let's see if this gets fixed when 3.7 stuff gets backported to the LTS.
Currently broken on 3.3.5 and 3.3.6-RC1-bin-20250319-2b41273-NIGHTLY
Works fine on 3.7 Next, as noted.
cc @tgodzik
