### ISSUE TITLE
doc fails to read scala.scalajs.js.Promise.then symbol

### ISSUE THREAD

**Issue by MartinHH** [scala/scala3#20476]
This seems similar to #14143, but the affected scala versions are much newer and the bug does not occur when downgrading to scala 3.3.1:

## Compiler version

scala 3.3.3 ; 3.4.0 ;  3.4.1 ; 3.4.2

scala-js 1.16.0
sbt 1.10.0

## Minimized code

```Scala
package demo

import scala.scalajs.js

def bar: js.Promise[Int] = js.Promise.resolve(()).`then`(_ => 1)

```

```Scala
# plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.16.0")

```

```Scala
# build.sbt
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "3.3.3" // or any of 3.4.0 to 3.4.2

lazy val root = (project in file("."))
  .enablePlugins(ScalaJSPlugin)
  .settings(
    name := "doc_bug_report"
  )
```

## Output

```
[IJ]doc
[info] compiling 1 Scala source to /redacted/doc_bug_report/target/scala-3.3.3/classes ...
[info] done compiling
[info] Main Scala API documentation to /redacted/doc_bug_report/target/scala-3.3.3/api...
-- Error: src/main/scala/demo/demo.scala:5:27 ----------------------------------
5 |def bar: js.Promise[Int] = js.Promise.resolve(()).`then`(_ => 1)
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |undefined: $1$.then # -1: TermRef(TermRef(NoPrefix,val $1$),then) at readTasty
1 error found
[info] Main Scala API documentation successful.
[success] Total time: 0 s, completed 27.05.2024, 10:08:40
```

## Expectation

No error occurs (as with scala 3.3.1).

**Comment by Gedochao** [comment]
Reproduction with Scala CLI:
```
//> using platform js
//> using scala 3.3.2
import scala.scalajs.js
def bar: js.Promise[Int] = js.Promise.resolve(()).`then`(_ => 1)
```

Last good stable version: 3.3.1
First breaking stable version: 3.3.2

**Comment by Florian3k** [comment]
Bisect:
Last good release: 3.3.2-RC1-bin-20230615-916d4e7-NIGHTLY
First bad release: 3.3.2-RC1-bin-20230619-a68568c-NIGHTLY

Reverting https://github.com/scala/scala3/pull/18989 seems to fix this (on LTS branch at least)

**Comment by keynmol** [comment]
@WojciechMazur is it too late to backport this to LTS?

**Comment by WojciechMazur** [comment]
> @WojciechMazur is it too late to backport this to LTS?

We'll see, we might try backporting that in 3.3.5-RC2. 
The mentioned PR that fixed it was problematic - it needed to be reverted once becouse of introduced regression so wee need to be careful here

**Comment by davesmith00000** [comment]
@WojciechMazur Just to add that I seem to have the same (or a related) issue with Scala 3.6.2 and Scala.js 1.18.1:

```
-- Error: tyrian/src/main/scala/tyrian/TyrianApp.scala:145:4 -------------------
145 |    documentReady.`then`(_ => launch[F](appDirectory))
    |    ^^^^^^^^^^^^^^^^^^^^rtifacts 0s
    |undefined: documentReady.then # -1: TermRef(TermRef(NoPrefix,val documentReady),then) at readTasty
-- Error: tyrian/src/main/scala/tyrian/http/Http.scala:61:6 --------------------
61 |      fetch(request.url, requestInit)
   |      ^
   |undefined: $1$.then # -1: TermRef(TermRef(NoPrefix,val $1$),then) at readTasty
62 |        .`then`(response => callback(Right(response)))
-- Error: tyrian/src/main/scala/tyrian/http/Http.scala:70:6 --------------------
70 |      domResponse
   |      ^
   |undefined: $2$.then # -1: TermRef(TermRef(NoPrefix,val $2$),then) at readTasty
71 |        .text()
72 |        .`then`(text => callback(Right(text)))
```

**Comment by keynmol** [comment]
Seems like this was forgotten among backports – it's still broken on 3.3.7, works on 3.6.3 and above.

Please reconsider backporting it to 3.3 LTS for libraries' sake

**Comment by Gedochao** [comment]
cc @tgodzik

**Comment by tgodzik** [comment]
Ach, I think I didn't manage to backport this fix. If it's important I can retry it
