### ISSUE TITLE
Context function parameter name leaks into scope

### ISSUE THREAD

**Issue by mbovel** [scala/scala3#24375]
@Sporarum mentioned this in https://users.scala-lang.org/t/using-context-function-parameter-by-name-and-not-by-type/10658.

## Compiler version

3.4..3.7.3

## Minimized code

```scala
def foo(f: (x: Int) ?=> Int) = f(using 0)
@main def Main = println(foo(x))
```

## Output

Compiles successfully, with `x` referring to the argument of the context function:

```scala
$ scala -S 3.4 ../test.scala
Compiling project (Scala 3.4.3, JVM (17))
Compiled project (Scala 3.4.3, JVM (17))
0
```

## Expectation

`x` should be not found, as in `< 3.4`:

```scala
$ scala -S 3.3 ../test.scala
Compiling project (Scala 3.3.7, JVM (17))
[error] /localhome/bovel/test.scala:2:30
[error] Not found: x
[error] @main def Main = println(foo(x))
[error]                              ^
Error compiling project (Scala 3.3.7, JVM (17))
Compilation failed
```

**Comment by mbovel** [comment]
```scala
$ scala -S 3.7.3 -Xprint:typer ../test.scala
Compiling project (Scala 3.7.3, JVM (17))
[[syntax trees at end of                     typer]] // /localhome/bovel/test.scala
package <empty> {
  final lazy module val test$package: test$package = new test$package()
  final module class test$package() extends Object() {
    this: test$package.type =>
    def foo(f: (x: Int) ?=> Int): Int = f.apply(using 0)
    @main def Main: Unit = println(foo((using x: Int) => x))
  }
...
```

**Comment by mbovel** [comment]
Bisected to f2aa33c3643655fd9a48a1e448d7d79e6e52ea79 from #18463:

```
$ scala project/scripts/bisect.scala -- --should-fail compile ../test.scala
...
f2aa33c3643655fd9a48a1e448d7d79e6e52ea79 is the first bad commit
commit f2aa33c3643655fd9a48a1e448d7d79e6e52ea79
Author: odersky <...>
Date:   Sat Aug 26 19:18:07 2023 +0200

    Take names of synthesized contextual functions from expected type
    
    If expected type has parameter names, use them for the generated contextual closure.

 compiler/src/dotty/tools/dotc/ast/Desugar.scala | 13 ++++++++-----
 compiler/src/dotty/tools/dotc/typer/Typer.scala |  5 ++++-
 2 files changed, 12 insertions(+), 6 deletions(-)
bisect found first bad commit
...
```

**Comment by Sporarum** [comment]
If I remember correctly, this post was a reaction to someone asking a question on the user forum assuming this behavior to be a normal feature.
I was not able to find that question.

This means there is a real possibility this behavior is used in some projects !
(We should not leave it in however, as it is both a footgun and [unsound?](https://users.scala-lang.org/t/using-context-function-parameter-by-name-and-not-by-type/10658/5?u=sporarum))

**Comment by Sporarum** [comment]
Here is the original question:
https://users.scala-lang.org/t/type-a-parameter-as-either-a-contextual-function-null/10618

**Comment by odersky** [comment]
https://github.com/scala/scala3/commit/f2aa33c3643655fd9a48a1e448d7d79e6e52ea79 gave the context function parameters the names of the parameters of the expected type. That leads to nicer error messages, but does indeed risk that the name is leaked into the scope. Previously, we generated names wih `$`s in them, which are supposed not to be used in programs.

**Comment by som-snytt** [comment]
I proposed a fix that embeds the param name when synthesizing the context function. The original name is extracted when printing a diagnostic message.

The tree prints as `val f1: (x: Show[String]) ?=> String = (using xcontextual$1: Show[String]) => ...`

I might have preferred `(using contextual$x)` since the names must be unique, that is, the name instead of an index.

**Comment by Sporarum** [comment]
> [f2aa33c](https://github.com/scala/scala3/commit/f2aa33c3643655fd9a48a1e448d7d79e6e52ea79) gave the context function parameters the names of the parameters of the expected type. That leads to nicer error messages, but does indeed risk that the name is leaked into the scope. Previously, we generated names wih `$`s in them, which are supposed not to be used in programs.

Instead I think it would be worthwhile to have a system which tries to de-mangle names when printing error messages.
This would allow us to keep using safer mangled names internally, while exposing users to friendlier un-mangled names.
It wouldn't be worth it for just this feature, but there are multiple ways to get mangled names in error messages, which to me justifies the investment.

There is also precedent for something similar with the `Where T¹ is ... Where T² is ...` from typing errors

**Comment by odersky** [comment]
@Sporarum We already unmangle semantic names. It's in the toString function of `Name`:

```scala
 final case class DerivedName(override val underlying: TermName, override val info: NameInfo) extends TermName:
   ...

   protected def computeToString: String = info.mkString(underlying)
```
I agree we should use the `info.mkString` function instead of patching the code elsewhere.

**Comment by som-snytt** [comment]
@Sporarum Thanks for the hint. I'll follow up along those lines. (Assuming no one already has a branch.)

**Comment by NPCRUS** [comment]
a bit late to the party, but yes it was used in the projects. From the comments i don't get whether it's still possible to refer to each individual parameter from the tuple by some sort of name, or is it only possible with `summon[Param1]` now?

**Comment by Sporarum** [comment]
@NPCRUS 
What you are saying doesn't seem to match what this issue was about 
(for example there is no mention of tuples before your post)

Could you explain a bit more what you mean ?

**Comment by NPCRUS** [comment]
@Sporarum sorry, in my head i was referencing my usecase,
```
def f1(m: (a: String, b: String) ?=> Unit) = m(using "a", "b")

f1 {
  println(a)
}
```
is there any way in such example to refer to `a` or `b`?

**Comment by mbovel** [comment]
> is there any way in such example to refer to `a` or `b`?

Not directly. Typically, people use either [`summon`](https://docs.scala-lang.org/scala3/reference/contextual/using-clauses.html#class-context-parameters), or an intermediate getter function that returns the implicit evidence, as `getA` in the following example:

```scala
def getA(using a: String): String = a
def f(m: String ?=> Unit) = m(using "a")

@main def main =
  f:
    println(summon[String])
    println(getA)
```

https://scastie.scala-lang.org/MjYj6VJfTYihk8FRFQfmZg
