### ISSUE TITLE
`Tuple` `toList` method and friends with unusable signatures (MT application to singleton types)

### ISSUE THREAD

**Issue by irfanstract** [scala/scala3#26817]
the `Tuple` `toList` method (and a few more) have unusable signature -- issue appears on eg `toList` called on stable paths.

this has been reported in #24214 #22022 .
the return-type of `toList` is an application of a match-type to a singleton type. #20015 . this means that Tuple `toList` is effectively unusable with path(s) (stable names like `a.b.c`, where `.type` is legal).

## Compiler version

any version where the fix for #19746 (in #20015) lands in. it's `3.5` ... `3.8`, `3.9.0-RC*`.
`3.3.*` remains unaffected because the fix didn't land there.

**1**

```scala

import util.chaining.{*}


(3, 3).pipe { _.toList }

```

**Output**

```scala
Found:    List[Tuple.Union[(_$1 : (Int, Int))]]
Required: List[Int]

Note: a match type could not be fully reduced:

  trying to reduce  Tuple.Union[(_$1 : (Int, Int))]
  trying to reduce  Tuple.Fold[(_$1 : (Int, Int)), Nothing, [x, y] =>> x | y]
  failed since selector (_$1 : (Int, Int))
  does not uniquely determine parameters h, t in
    case h *: t => h | Tuple.Fold[t, Nothing, [x, y] =>> x | y]
  The computed bounds for the parameters are:
    h <: Int
    t <: Int *: EmptyTuple.type
```

**2**

```scala
val pt1 = (3, 3)
val pt2 = (7, 2)

extension (v: (Int, Int) )

  def strfPt( )
  =
    v
    .toList
    .map { (_: Int).toDouble }
    .mkString("(point at ", ", ", ")")

println { pt1.strfPt() }

println { pt2.strfPt() }

println(s"done.")

```

**Output**

```scala
Found:    Int => Double
Required: Tuple.Union[(v : (Int, Int))] => Double

Note: a match type could not be fully reduced:

  trying to reduce  Tuple.Union[(v : (Int, Int))]
  trying to reduce  Tuple.Fold[(v : (Int, Int)), Nothing, [x, y] =>> x | y]
  failed since selector (v : (Int, Int))
  does not uniquely determine parameters h, t in
    case h *: t => h | Tuple.Fold[t, Nothing, [x, y] =>> x | y]
  The computed bounds for the parameters are:
    h <: Int
    t <: Int *: EmptyTuple.type
```

Had `(_: Int).toDouble` been `_.toDouble` instead, one will get rather vague error with no explanation:

```scala
value toDouble is not a member of Tuple.Union[(v : (Int, Int))]
// that's it
```

The return-type of `toList` is an application of a match-type to a singleton type TermRef to `this`/receiver. In this case `List[Union[this.type]]`.

> Term refs that reference term parameters can be substituted later by more precise one…
> #20015

```scala

  /** Creates a copy of this tuple as a List. */
  inline def toList: List[Union[this.type]] =
    this.productIterator.toList
      .asInstanceOf[List[Union[this.type]]]

```

all methods with MT application to singleton types: `toList` (above), `map` (`Map[this.type, F]`), `++` (`This ++ that.type`), and `i`-taking methods like `apply` `take` `drop`.

```scala

  /** Returns a new tuple by concatenating `this` tuple with `that` tuple.
   *  This operation is O(this.size + that.size)
   */
  inline def ++ [This >: this.type <: Tuple](that: Tuple): This ++ that.type =
    runtime.Tuples.concat(this, that).asInstanceOf[This ++ that.type]
```

This will definitely baffle developers of Tuple-heavy libraries upgrading to `3.9`.

compare with the corresponding `NamedTuple` `toList` op under `NamedTupleDecomposition`:

```scala
/* `NamedTuple` extension methods */
inline def toList: List[Tuple.Union[V]] = x.toTuple.toList
```

## Expectation

given all of them defined in the stdlib and available out-of-the-box (and yet unusable), many developers will find this unacceptable.

## Notes

most other methods take `[This >: this.type <: Tuple]`s, unaffected by (and unfortunately hides) the problem.

deserves fixing before `3.10` is out - see also #26851

same problem with `NamedTuple` ops failing on singleton types in #20453 (with a `does not match  case` instead of a `does not uniquely determine parameters` tagline).

apart from that, most of `NamedTuple` methods operate on tparam(s) exclusively, avoiding the problem.

MT (match types) and CC (capture-checking) don't play well (#26815). 

The error message should atleast be revamped eg

```diff
  value toDouble is not a member of Tuple.Union[(v : (Int, Int))]
+ Note: a match type couldn't be fully reduced:
```

**Comment by Gedochao** [comment]
If we treat it as a regression, it bisects same as https://github.com/scala/scala3/issues/22022

Last good release: 3.5.0-RC1-bin-20240403-ece87c3-NIGHTLY
First bad release: 3.5.0-RC1-bin-20240404-a7f00e2-NIGHTLY
Bisect points at https://github.com/scala/scala3/commit/0bf43b2fbb1ad0faa64cd1da97a9682b02724c49

**Comment by SethTisue** [comment]
question at core meeting: can `toList` be changed to somehow be more inference-friendly? (without breaking binary or TASTy compatibility?) at present we don't know, it hasn't been tried
