### ISSUE TITLE
Match type reduction does not fail even if selector matches none of the cases

### ISSUE THREAD

**Issue by NovaMage** [scala/scala3#23822]
## Compiler version

3.6.2, 3.7.1

## Minimized code

```scala
object MatchTypes {

  type ConstituentPartOf[A] = A match {
    case BigInt => Int
    case String => Char
  }

  def lastPartOf[A](thing: A): ConstituentPartOf[A] = thing match {
    case number: BigInt => (number % 10).toInt
    case string: String => string.charAt(string.length - 1)
  }

  def main(args: Array[String]): Unit = {
    val lastPartOfSomethingElse = lastPartOf(BigDecimal("10"))
    println(lastPartOfSomethingElse)
  }
}
```

## Output

Program compiles succesfully (which it shouldn't), and throws an exception at runtime:

```scala
Exception in thread "main" scala.MatchError: 10 (of class scala.math.BigDecimal)
	at MatchTypes$.lastPartOf(MatchTypes.scala:10)
	at MatchTypes$.main(MatchTypes.scala:14)
	at MatchTypes.main(MatchTypes.scala)
```

## Expectation

It should throw a compilation error as it does in scala 3.3.6

<img width="764" height="154" alt="Image" src="https://github.com/user-attachments/assets/535d3b80-5a88-4076-b63b-eded8ee698cd" />

**Comment by Gedochao** [comment]
Last good release: 3.5.0-RC1-bin-20240326-43ed9fd-NIGHTLY
First bad release: 3.5.0-RC1-bin-20240327-c251f36-NIGHTLY
c251f36f155b81e039b3b5d72a99edebffcae182 is the first bad commit
cc @odersky

**Comment by odersky** [comment]
I reverted https://github.com/scala/scala3/commit/c251f36f155b81e039b3b5d72a99edebffcae182 locally but it's still the same behavior. Investigation shows that this error was downgraded to a warning and the warning commented out altogether. The only point were the error message shows up is in TypeComparer.matchCases, here:
```scala
      case Nil =>
        /* TODO warn ? then re-enable warn/12974.scala:26
        val noCasesText = MatchTypeTrace.noMatchesText(scrut, cases)
        report.warning(reporting.MatchTypeNoCases(noCasesText), pos = ???)
        */
        MatchTypeTrace.noMatches(scrut, cases)
        NoType
```
In fact it _is_ dubious that this example should be rejected. An unreducible match type is just that, meaning we simply leave it as is, and don't reduce it. It is nowhere specced that this is an error.

@EugeneFlesselle you were the last to touch this code, what is your opinion?

**Comment by EugeneFlesselle** [comment]
> In fact it _is_ dubious that this example should be rejected. An unreducible match type is just that, meaning we simply leave it as is, and don't reduce it. It is nowhere specced that this is an error.
> 
> [@EugeneFlesselle](https://github.com/EugeneFlesselle) you were the last to touch this code, what is your opinion?

That is correct! The match type rightfully does not reduce, and irreducible match types should not generate a type error (note that the match type trace would still be reported if reduction was necessary for subtyping).
Before #19954, match types that were irreducible specifically because none of the cases matched were reported as an error; but this was changed for consistency.

The runtime error here follows from the inexhaustive match expression, independently of it being assigned a match type.
Note that before the changes of #19954, the program could also be made to type-check by changing the inferred type argument to `lastPartOf[Any](BigDecimal("10"))`. In that case, we also obtained an irreducible match type, but of kind that was never treated as a type error.

**Comment by EugeneFlesselle** [comment]
It would be sensible to emit a _warning_ for these kinds of irreducible match types. 
But this is another instance of a situation where we have no srcPos from the type expression..
(Which is why I left the commented code there.)

**Comment by odersky** [comment]
I agree a warning would be useful here.

**Comment by EugeneFlesselle** [comment]
> I agree a warning would be useful here.

Is there a way to work around the lack of source position?
This used to rely on `ErrorType`s, but there is no equivalent for warnings AFAIK.

**Comment by bishabosha** [comment]
Context has the current tree no?

**Comment by NovaMage** [comment]
> It would be sensible to emit a _warning_ for these kinds of irreducible match types. But this is another instance of a situation where we have no srcPos from the type expression.. (Which is why I left the commented code there.)

> I agree a warning would be useful here.

Talking purely from a business perspective, a warning would also solve my issues, as we normally program with "-Werror" enabled (we heavily favor inexhaustive match expressions being reported as errors, they are bugs basically 100% of the time) and as Eugene said, the runtime error is in fact caused by the inexhaustive match later at runtime. 

If you open another issue to create said warning, please reference this issue so I can follow with the status of what's going on

**Comment by dancewithheart** [comment]
While working on #24753 I noticed that restoring the `MatchTypeNoCases`
warning also surfaces the example from this issue.

PR #25470 restores the warning emission in `TypeComparer.matchCases`.
With this change, the example here now produces a warning instead of
compiling silently.

If I understand the discussion correctly, this should resolve this issue as well.
