### ISSUE TITLE
StackOverflowError involving dotty.tools.dotc.core.Types$TypeSizeAccumulator

### ISSUE THREAD

**Issue by abosshard** [scala/scala3#25216]
## Compiler version

3.8.1

## Minimized code

```Scala
//> using scala 3.8.1

trait X[A]

given [A <: X[B], B <: A] => A => B = ???

type Z = {
  val v: Int
}

def f(z: Z) = z.v
```

## Output (click arrow to expand)

<details>

```scala
stackoverflow % scala compile --server=false example.scala

  Exception while compiling /stackoverflow/example.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: <no file>
        during phase: parser
                mode: Mode()
     library version: version 3.8.1
    compiler version: version 3.8.1
            settings: -classpath /opt/sdkman/candidates/scala/current/maven2/org/scala-lang/scala3-library_3/3.8.1/scala3-library_3-3.8.1.jar:/opt/sdkman/candidates/scala/current/maven2/org/scala-lang/scala-library/3.8.1/scala-library-3.8.1.jar -d /stackoverflow/.scala-build/stackoverflow_50e153b563-8443620b74/classes/main -sourceroot /stackoverflow

Exception in thread "main" java.lang.StackOverflowError
        at scala.collection.mutable.ArrayBuffer.clear(ArrayBuffer.scala:128)
        at dotty.tools.dotc.core.TypeComparer.init(TypeComparer.scala:56)
        at dotty.tools.dotc.core.Contexts$.comparer(Contexts.scala:873)
        at dotty.tools.dotc.core.TypeComparer$.bounds(TypeComparer.scala:3505)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7119)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7108)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6978)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7129)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7108)
        at dotty.tools.dotc.core.Types$TypeAccumulator.op$proxy28$1(Types.scala:6961)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$3(Types.scala:6961)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6965)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7113)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7108)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6996)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7129)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7121)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7108)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6978)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7129)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7108)
        at dotty.tools.dotc.core.Types$TypeAccumulator.op$proxy28$1(Types.scala:6961)
        
        ... elided due to message-size limits ...

        at dotty.tools.dotc.core.Types$TypeAccumulator.op$proxy28$1(Types.scala:6961)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldArgs$3(Types.scala:6961)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6965)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7113)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7108)
        at dotty.tools.dotc.core.Types$TypeAccumulator.foldOver(Types.scala:6996)
        at dotty.tools.dotc.core.Types$TypeSizeAccumulator.apply(Types.scala:7129)
Compilation failed
stackoverflow % 
```
</details>

**Comment by Binayak490-cyber** [comment]
Hi @abosshard,
I tried to reproduce this on current main, but I wasn’t able to trigger the StackOverflowError locally so far.

I added the minimized example as a compiler test, but it does not seem to crash the compiler on main.

Can you confirm whether this still reproduces on current main, or whether it was fixed recently?

**Comment by abosshard** [comment]
Hi @Binayak490-cyber,
I'm still getting the error using `scala compile -S 3.nightly`, which resolves to `Scala 3.8.3-RC1-bin-20260209-c5506bd-NIGHTLY`.

**Comment by som-snytt** [comment]
I did not bisect, but it goes back to 3.8.0-RC1 and there have been changes in that area of the code.

**Comment by Binayak490-cyber** [comment]
okk, that helps. I wasn’t able to reproduce this via the compiler test harness on current main, but since it still reproduces via Scala CLI nightly, I’ll try to narrow down what difference in invocation or code path triggers it, or attempt a local bisect.

**Comment by Gedochao** [comment]
Last good release: 3.8.0-RC1-bin-20250919-dfacd3f-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250920-834e8e9-NIGHTLY
Bisect points at 834e8e9b711f668e8ac5984d6293eb46c95becbb as the first bad commit, but that doesn't feel right... and it's the last commit in this range 😕 (cc @SethTisue)

Before that it did not crash, and instead failed compilation with
```scala
-- [E007] Type Mismatch Error: /Users/pchabelski/IdeaProjects/scala-cli-tests/compiler-repro/repro.scala:6:14 
6 |def f(z: Z) = z.v
  |              ^
  |              Found:    (z : Z)
  |              Required: Selectable | Dynamic
  |
  |              The following import might fix the problem:
  |
  |                import scala.reflect.Selectable.reflectiveSelectable
  |
  |
  | longer explanation available when compiling with `-explain`
1 error found
Compilation failed
```

`import scala.reflect.Selectable.reflectiveSelectable` fixes the compilation, even after the regression/crash got introduced.

**Comment by WojciechMazur** [comment]
The referenced commit might be related to these 2 regressions: 
- https://github.com/scala/scala3/issues/24007 (used for reproduction, most likely first bad nightly, bisect points to TypeAcumulator changes)
- https://github.com/scala/scala3/issues/24134 (last good release)

Also, the bisect might have been flaky due to changes in project naming (`scala3-bootstrapped` -> `scala3-bootstrapped-new` -> `scala3-bootstrapped`), it possible it could have classified some revisions as false-negative

**Comment by eejbyfeldt** [comment]
It makes sense that https://github.com/scala/scala3/pull/20459 can have caused it, as it made the recursive guard only be checked for `LazyRef` and when the type is checked in TypeSizeAccumulator there seems to be no `LazyRef` when the overflow occurs. So I guess the question is if there should a `LazyRef`?

**Comment by som-snytt** [comment]
@eejbyfeldt I did a quickie to revert that but it still failed. I haven't tried more.

**Comment by eejbyfeldt** [comment]
I think it might have been too quick. Or at least when I manually reverted the change (my memory of it), the error when away.
