### ISSUE TITLE
compiler error with automatic derivation when switching to scala 3.8.2

### ISSUE THREAD

**Issue by rolman243** [scala/scala3#25417]
## Compiler version

scala 3.8.2

## other library versions

cats 2.13.0
circe 0.14.15
iron 3.3.0

## Minimized code

[scastie](https://scastie.scala-lang.org/5GTRylgrR4WjEi8oqkeizA.js)

```scala
import cats.Show
import cats.derived.*
import io.circe.Codec
import io.github.iltotore.iron.*
import io.github.iltotore.iron.cats.given
import io.github.iltotore.iron.circe.given
import io.github.iltotore.iron.constraint.string.Blank

type Foo = Foo.T

object Foo extends RefinedType[String, Not[Blank]]

final case class Bar(
  foo: Foo
) derives Codec, Show
```

## Output

```scala
[error] -- Error: /home/rmanfrah/devel/obi/frozen/frozen-shared/foundation-lib/core/src/main/scala/Bug382.scala:15:10 
[error]  15 |) derives Codec, Show
[error]     |          ^
[error]     |         cannot reduce summonFrom with
[error]     |          patterns :  case given decodeA @ _:io.circe.Decoder[Foo.T]
[error]     |                      case given m @ _:scala.deriving.Mirror.Of[Foo.T]
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:67
[error]      ---------------------------------------------------------------------------
[error] -- [E172] Type Error: /home/rmanfrah/devel/obi/frozen/frozen-shared/foundation-lib/core/src/main/scala/Bug382.scala:15:17 
[error] 15 |) derives Codec, Show
[error]    |                 ^
[error]    |Could not derive Show for Bar.
[error]    |Make sure it satisfies one of the following conditions:
[error]    |  * case class where all fields form Show
[error]    |  * sealed trait where all subclasses form Show
[error]    |  * enum where all variants form Show.
[error]    |I found:
[error]    |
[error]    |    cats.derived.DerivedShow.given_DerivedShow_A[Bar](
[error]    |      {
[error]    |        val Kind_this: shapeless3.deriving.K0.type = shapeless3.deriving.K0
[error]    |        val gen$proxy1:
[error]    |          
[error]    |            scala.deriving².Mirror.Product{
[error]    |              type MirroredMonoType = Bar; type MirroredType = Bar;
[error]    |                type MirroredLabel = ("Bar" : String);
[error]    |                type MirroredElemTypes = Foo *: EmptyTuple.type;
[error]    |                type MirroredElemLabels = ("foo" : String) *: EmptyTuple.type
[error]    |            }
[error]    |          
[error]    |         =
[error]    |          Bar.$asInstanceOf[
[error]    |            
[error]    |              scala.deriving².Mirror.Product{
[error]    |                type MirroredMonoType = Bar; type MirroredType = Bar;
[error]    |                  type MirroredLabel = ("Bar" : String);
[error]    |                  type MirroredElemTypes = Foo *: EmptyTuple.type;
[error]    |                  type MirroredElemLabels = ("foo" : String) *: EmptyTuple.type
[error]    |              }
[error]    |            
[error]    |          ]
[error]    |        shapeless3.deriving.internals.ErasedProductInstances1.apply[
[error]    |          (Kind_this : shapeless3.deriving.K0.type),
[error]    |          
[error]    |            shapeless3.deriving.OrElse[cats.Show[Bar],
[error]    |              shapeless3.deriving.Derived[cats.Show[Bar]]]
[error]    |          
[error]    |        ](gen$proxy1,
[error]    |          {
[error]    |            scala.compiletime.summonInline[
[error]    |              
[error]    |                shapeless3.deriving.OrElse[cats.Show[Foo],
[error]    |                  shapeless3.deriving.Derived[cats.Show[Foo]]]
[error]    |              
[error]    |            ]
[error]    |          }:Any
[error]    |        ):
[error]    |          shapeless3.deriving.internals.ErasedProductInstances[
[error]    |            (Kind_this : shapeless3.deriving.K0.type),
[error]    |            
[error]    |              shapeless3.deriving.OrElse[cats.Show[Bar],
[error]    |                shapeless3.deriving.Derived[cats.Show[Bar]]]
[error]    |            
[error]    |          ]
[error]    |        :
[error]    |          Kind_this.ProductInstances[
[error]    |            
[error]    |              [x] =>>
[error]    |                shapeless3.deriving.OrElse[cats.Show[x],
[error]    |                  shapeless3.deriving.Derived[cats.Show[x]]]
[error]    |            ,
[error]    |          Bar]
[error]    |      },
[error]    |    ???)
[error]    |
[error]    |But given instance mkProductInstances in trait Kind does not match type shapeless3.deriving.K0.ProductInstances[
[error]    |  cats.Show |: shapeless3.deriving.Derived, Bar]
[error]    |
[error]    |where:    deriving  is a package in package shapeless3
[error]    |          deriving² is a package in package scala
[error]    |.
[error]    |
[error]    |One of the following imports might make progress towards fixing the problem:
[error]    |
[error]    |  import cats.derived.DerivedShow.Strict.coproduct
[error]    |  import cats.derived.DerivedShow.Strict.product
[error]    |  import shapeless3.deriving.K0.Generic.fromMirror
[error]    |  import shapeless3.deriving.K1.Generic.fromMirror
[error]    |  import shapeless3.deriving.K11.Generic.fromMirror
[error]    |  import shapeless3.deriving.K2.Generic.fromMirror
[error]    |
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from DerivedShow.scala:20
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from DerivedShow.scala:20
[error]     ----------------------------------------------------------------------------
```

## Expectation

Code compiles without any error with scala 3.8.2 as it does with scala 3.8.1

**Comment by rolman243** [comment]
@xuwei-k added link to scastie script

**Comment by xuwei-k** [comment]
I think we'd like it minimized without the external dependency.

**Comment by Gedochao** [comment]
```scala
//> using dep org.typelevel::cats-core:2.13.0
//> using dep org.typelevel::kittens:3.5.0
//> using dep io.circe::circe-core:0.14.15
//> using dep io.github.iltotore::iron:3.3.0
//> using dep io.github.iltotore::iron-cats:3.3.0
//> using dep io.github.iltotore::iron-circe:3.3.0

import cats.Show
import cats.derived.*
import io.circe.Codec
import io.github.iltotore.iron.*
import io.github.iltotore.iron.cats.given
import io.github.iltotore.iron.circe.given
import io.github.iltotore.iron.constraint.string.Blank

type Foo = Foo.T

object Foo extends RefinedType[String, Not[Blank]]

final case class Bar(
  foo: Foo
) derives Codec, Show
```
(unminimized) repro with all the deps on Scala CLI

**Comment by ivan-klass** [comment]
@xuwei-k @Gedochao I think I've simplified and minimized that to no-dependency in #25427

**Comment by Gedochao** [comment]
@ivan-klass seems like it, it bisects to the same.

Last good stable release: 3.8.1
First bad stable release: 3.8.2

Last good nightly release: 3.8.3-RC1-bin-20260127-4931fcd-NIGHTLY
First bad nightlyrelease: 3.8.3-RC1-bin-20260128-3882481-NIGHTLY
2d7eaa17b034397cac93bff703bcbd21a0285533 is the first bad commit (https://github.com/scala/scala3/pull/24817)
cc @tanishiking 

What is somewhat interesting is that https://github.com/scala/scala3/pull/24817 is milestoned at 3.8.3... and the bisection indeed points at 3.8.3 nightlies.
But we can reproduce it with 3.8.2 (but can't with 3.8.2-RC1-bin-20260121-137f1c8-NIGHTLY).

Last good Scala 3.8.2 RC: [3.8.2-RC1](https://github.com/scala/scala3/releases/tag/3.8.2-RC1)
First bad Scala 3.8.2 RC: [3.8.2-RC2](https://github.com/scala/scala3/releases/tag/3.8.2-RC2)
I can't see https://github.com/scala/scala3/pull/24817 being listed as a backport here... so I wonder if it's caused by smth else? cc @WojciechMazur

**Comment by Gedochao** [comment]
Note: https://github.com/scala/scala3/pull/24817 was backported to 3.3 LTS at https://github.com/scala/scala3-lts/pull/737
And so, I can reproduce the problem at 3.3.8-RC1-bin-20260227-17a0d72-NIGHTLY 
cc @tgodzik

**Comment by WojciechMazur** [comment]
> What is somewhat interesting is that https://github.com/scala/scala3/pull/24817 is milestoned at 3.8.3... and the bisection indeed points at 3.8.3 nightlies.
But we can reproduce it with 3.8.2 (but can't with 3.8.2-RC1-bin-20260121-137f1c8-NIGHTLY). 

#24817 was merged 27 January
#25026 effectivelly starting 3.8.3-nightlies was merged 21 January 
The release 3.8.2 branch / tag 3.8.2 does not have any of these changes 
There is no changes related to mentioned PR in the [3.8.2 tree for Erasure ](https://github.com/scala/scala3/commits/3.8.2/compiler/src/dotty/tools/dotc/transform/Erasure.scala)

**Comment by Gedochao** [comment]
Some extra suspicions.
It's easy to confirm the nightly versions were correct, but maybe the bisect script points to the wrong commit.
There are 2 PRs in the 4931fcd..3882481 range which were also ported to 3.8.2-RC2:
#25110 (cc @lrytz) and #25111 (cc @mbovel)
Both were ported to 3.3 LTS, as well, and so they are likely culprits.

**Comment by tanishiking** [comment]
I was looking into this issue, and this is indeed caused by https://github.com/scala/scala3/pull/25111.

With that change, in @ivan-klass’s example,
- `summonInline[MyEvidence[Scope.T]]` does implicit search
- finds `Scope.given_MyEvidence_T`, (it's typed like `Scope.type{type T = String}#given_MyEvidence_T`)
- then inlines that and adapts it to the expected result type. (`(Scope.given_MyEvidence_T : => Scope.given_MyEvidence_T)`)

In 3.8.2, `target.widenIfUnstable` widens the result type to something like `Scope.given_MyEvidence_T`, and as a result, `inlined.ensureConforms(resultType)` does not insert a cast, so the resulting tree still has type `Scope.type{type T = String}#given_MyEvidence_T`.

As a result, the RHS of `summonInlineNoOpProxy` remains typed as `Scope.type{type T = String}#given_MyEvidence_T`, which does not conform to the expected type, and causes the compilation error because of type mismatch. 🤔 


```scala
//> using scala 3.8.2
import scala.compiletime.summonInline

trait MyEvidence[T]

object Scope:
  opaque type T = String
  inline given MyEvidence[T] with {}

inline def summonInlineNoOpProxy: MyEvidence[Scope.T] = summonInline[MyEvidence[Scope.T]]

@main def test = println:
  (
    summonInline[MyEvidence[Scope.T]],
    summonInlineNoOpProxy // ok in 3.8.1, compilation error in 3.8.2,
  )
```

**Comment by tanishiking** [comment]
So the problem is
- **target** = `(Scope.given_MyEvidence_T : => Scope.given_MyEvidence_T`
- **inlined.tpe** = `Scope.type{type T = String}#given_MyEvidence_T` 
- `(Scope.given_MyEvidence_T : => Scope.given_MyEvidence_T` is `widenIfUnstable` to `Scope.given_MyEvidence_T` = **resultType**
- **inlined.tpe** = `Scope.type{type T = String}#given_MyEvidence_T` <: `Scope.given_MyEvidence_T` = **resultType**
- Therefore, `inlined.ensureConforms(resultType)` does not insert cast, because inlined conforms resultType.

As a result, `summonInline`ed tree type is like `Scope.type{type T = String}#given_MyEvidence_T`, (which is seens as `MyEvidence[String]`). This doesn't match with  `MyEvidence[Scope.T]` because the former one lost the path dependence information?

I made a fix https://github.com/scala/scala3/pull/25448 by making sure we insert a cast when adaptation is needed, but not very sure this is the right approach.

~edit: Hmm? with  https://github.com/scala/scala3/pull/25448  `inline.ensureConforms(target)` wouldn't insert cast? because it's already conform~
