### ISSUE TITLE
Crash: `val _ = <MethodHandle>` causes cyclic reference

### ISSUE THREAD

**Issue by fwbrasil** [scala/scala3#26646]
## Compiler version

3.9.0-RC4. Reproduces on JDK 21 and 25.

## Minimized code

```scala
//> using scala 3.9.0-RC4

import java.lang.invoke.MethodHandle

object M:
    def h: MethodHandle = ???
    val _ = h
```
## Output (click arrow to expand)

<details>

```scala
exception caught when loading class ClassSpecializer: Cyclic reference involving class ClassSpecializer
exception caught when loading class SpeciesData: Cyclic reference involving class ClassSpecializer

  unhandled exception while running MegaPhase{protectedAccessors, extmethods, uncacheGivenAliases, checkStatic, elimByName, hoistSuperArgs, forwardDepChecks, specializeApplyMethods, tryCatchPatterns, patternMatcher} on Repro.scala

  An unhandled exception was thrown in the compiler.

     while compiling: Repro.scala
        during phase: MegaPhase{protectedAccessors, extmethods, uncacheGivenAliases, checkStatic, elimByName, hoistSuperArgs, forwardDepChecks, specializeApplyMethods, tryCatchPatterns, patternMatcher}
                mode: Mode(ImplicitsEnabled)
     library version: version 3.9.0-RC4
    compiler version: version 3.9.0-RC4

Exception in thread "main" dotty.tools.dotc.core.CyclicReference: Cyclic reference involving class ClassSpecializer
Compilation failed
```
</details>

**Comment by fwbrasil** [comment]
I was able to work it around by not using `val _` so it's not critical for Kyo.

**Comment by SethTisue** [comment]
perhaps the same as #18392? I chose to close that one and keep this one open, since this one has a minimal reproducer

I wonder what's special about `ClassSpecializer`

**Comment by Gedochao** [comment]
Last good release: 3.9.0-RC1-bin-20260506-0de5613-NIGHTLY
First bad release: 3.9.0-RC1-bin-20260507-b8210ea-NIGHTLY
The first bad commit is 420470084b5d49863c44be19522f6808ddb49af0 (#25788) 
cc @lalala194 @SolalPirelli @Florian3k 

Reproduces with JDK 19+, works fine on JDK 17 & 18.

**Comment by Gedochao** [comment]
Note: what's interesting, 3.3 LTS doesn't seem to be affected, even though #25788 was ported back in https://github.com/scala/scala3-lts/pull/1009
Tested with 3.3.9-RC1-bin-20260728-7f5a323-NIGHTLY and compiles fine.

**Comment by SolalPirelli** [comment]
Indeed, reverting that commit fixes the issue, interesting.

> Tested with 3.3.9-RC1-bin-20260728-7f5a323-NIGHTLY and compiles fine.

Just to make sure, you tested with JDK 21+, right? (I initially tried to repro this on main without changing my default JDK of 17 and it compiles fine there too)

**Comment by SolalPirelli** [comment]
Looks like ClassSpecializer and SpeciesData are part of some kind of magic inside the JVM involving generating classes/methods at runtime? There are public bug reports vaguely alluding to problems the JDK itself has had with it. But we can't look into the source code for licensing reasons. (like "concatenating strings causes a stack overflow"... [ouch](https://bugs.openjdk.org/browse/JDK-8222895))

I wonder if a simple rule of "pretend `java.lang.invoke` has no `sealed` types" is reasonable here.

**Comment by Gedochao** [comment]
> Just to make sure, you tested with JDK 21+, right? (I initially tried to repro this on main without changing my default JDK of 17 and it compiles fine there too)

With JDK 19+, specifically.

It's probably easiest to just
```bash
scala-cli compile repro.scala --server=false --jvm 19 -S 3.3.9-RC1-bin-20260728-7f5a323-NIGHTLY
```

**Comment by jchyb** [comment]
jdk version-independent minimisation:
(best to compile with javac, when passed to scalac for joint compilation it will fail earlier, also incorrectly)
```java
// CyclicSignature.java
class CyclicSignature<S extends CyclicSignature<S>.Nested> {
    class Nested {}
}
```
`javac -d . CyclicSignature.java `
```scala
// Main.scala
object Main:
  val a: CyclicSignature = ???
```
`scalac -cp . Main.scala`

```
exception caught when loading class CyclicSignature: Cyclic reference involving class CyclicSignature

 Run with -explain-cyclic for more details.
-- [E046] Cyclic Error: test1.scala:4:9 ----------------------------------------
4 |  val a: CyclicSignature = ???
  |         ^
  |         Cyclic reference involving class CyclicSignature
  |
  |          Run with -explain-cyclic for more details.
  |
  | longer explanation available when compiling with `-explain`
```
(the underlying issue with loading signatures was always there, it's just more recently something like this must have been added to jdk and only recently we needed to load it when looking at fields of MethodHandle). On a related note, this also fails:
```scala
import java.lang.invoke.ClassSpecializer
object M:
    val a: ClassSpecializer = ???
```

**Comment by SolalPirelli** [comment]
Nice find, I was too deferential to the magic aspect of MethodHandle...

FWIW, Vulpix supports `JAVA_ONLY` in filenames to not run Scala's Java parser at all, so you can have a test folder with:

`Cyclic_JAVA_ONLY_1.java`:
```java
class Cyclic_JAVA_ONLY_1<S extends Cyclic_JAVA_ONLY_1<S>.Nested> {
  class Nested {}
}
```

`Use_2.scala`:
```scala
object Main:
  val c: Cyclic_JAVA_ONLY_1 = ???
```
