### ISSUE TITLE
3.9.0 regression: new Cyclic reference error in the code that worked before

### ISSUE THREAD

**Issue by MateuszKubuszok** [scala/scala3#26959]
## Compiler version

3.9.0

## Minimized code

`lib.scala`:

```scala
package repro

trait Outer {
  trait InnerSupport { this: Companion.type =>
    def foo: Unit = ()
  }
  val Companion: CompanionTrait
  trait CompanionTrait extends InnerSupport { this: Companion.type => }
}
```

`user.test.scala`:

```scala
package repro
class User(c: Outer)
```

```
scala-cli compile --test --scala 3.9.0 .   # Cyclic reference involving trait CompanionTrait
scala-cli compile --test --scala 3.8.4 .   # Compiles fine
```

## Output

```scala
Compiling project (test, Scala 3.9.0, JVM (22))
Error compiling project (test, Scala 3.9.0, JVM (22))
Error: Unexpected error when compiling repro-final_088de9e3c3-test: dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details.

Compilation failed
```

## Expectation

```scala
Compiling project (Scala 3.9.0, JVM (22))
Compiled project (Scala 3.9.0, JVM (22))
Compiling project (test, Scala 3.9.0, JVM (22))
Compiled project (test, Scala 3.9.0, JVM (22))
```

Context: I bumped Scala 3 version to 3.9.0 on Kindlings in [this PR](https://github.com/kubuszok/kindlings/actions/runs/33441333942/job/99650012215?pr=213). The code worked before, as far as I can tell it is correct - if I compile the macro, I can run it against 3.9.0 (e.g. I bumped Chimney to use that newer version of Hearth yesterday, and moved Chimney to 3.9.0 and it works). Kindlings however fails, and apparently it fails in its macro-extensions definition. This is minimization of
the pattern that occurs there which should work since 3.3.8 till 3.8.4 and fail on 3.9.0.

**Comment by belamenso** [comment]
Bisecting the reproduction (needs two-pass separate compilation: compile `lib.scala` first, then `user.test.scala` against its TASTy), I found that
- on 3.9.0 it was introduced in e8b3e2de75 (backport of https://github.com/scala/scala3/pull/26252)
- on main it was introduced in #26252 and disappeared (first clean commit) on 3adfcbd32a

The "fix" from 3adfcbd32a seems accidental.

**Comment by Gedochao** [comment]
Thanks for the bisection!

**Comment by Gedochao** [comment]
as https://github.com/scala/scala3/commit/3adfcbd32a00cb078db0d80ec4f147309e59895a is a part of #26156, I don't think it's realistic that we'd fix this during standard back ports to 3.9.1, BTW. 
So this will need a dedicated fix or a targeted, narrow port. cc @tgodzik

**Comment by Gedochao** [comment]
As far as I can tell, we can't really port the fix from https://github.com/scala/scala3/commit/3adfcbd32a00cb078db0d80ec4f147309e59895a
Tried a targeted fix at https://github.com/scala/scala3/pull/27010

**Comment by Gedochao** [comment]
...so as I was porting the anti-regression tests, I realised that while this used to be fixed in Scala Next/3.10, it no longer is.
It compiles with Scala 3.10.0-RC1, but breaks with 3.10.0-RC2.
So I was late with porting the test, we regressed it a second time. 🤡 

<details>

```scala
dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details. while traversing repro.Outer
dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details. while traversing c: repro.Outer
dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details. while traversing def <init>(c: repro.Outer): Unit =
  {
    super()
    ()
  }
dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details. while traversing  extends Object {
  def <init>(c: repro.Outer): Unit =
    {
      super()
      ()
    }
}
dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details. while traversing @SourceFile("user.test.scala") class User extends Object {
  def <init>(c: repro.Outer): Unit =
    {
      super()
      ()
    }
}
dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details. while traversing package repro {
  @SourceFile("user.test.scala") class User extends Object {
    def <init>(c: repro.Outer): Unit =
      {
        super()
        ()
      }
  }
}

  unhandled exception while running MegaPhase{lambdaLift, elimStaticThis, countOuterAccesses} on /Users/pchabelski/IdeaProjects/scala-cli-tests/26959/user.test.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Xno-enrich-error-messages.


     while compiling: /Users/pchabelski/IdeaProjects/scala-cli-tests/26959/user.test.scala
        during phase: MegaPhase{lambdaLift, elimStaticThis, countOuterAccesses}
                mode: Mode(ImplicitsEnabled)
     library version: version 3.10.0-RC1-bin-20260609-b34a019-NIGHTLY
    compiler version: version 3.10.0-RC1-bin-20260609-b34a019-NIGHTLY-git-b34a019
            settings: -classpath /Users/pchabelski/Library/Caches/Coursier/v1/https/repo.scala-lang.org/artifactory/maven-nightlies/org/scala-lang/scala3-library_3/3.10.0-RC1-bin-20260609-b34a019-NIGHTLY/scala3-library_3-3.10.0-RC1-bin-20260609-b34a019-NIGHTLY.jar:/Users/pchabelski/Library/Caches/Coursier/v1/https/repo.scala-lang.org/artifactory/maven-nightlies/org/scala-lang/scala-library/3.10.0-RC1-bin-20260609-b34a019-NIGHTLY/scala-library-3.10.0-RC1-bin-20260609-b34a019-NIGHTLY.jar:/Users/pchabelski/IdeaProjects/scala-cli-tests/26959/.scala-build/26959_4b6553e934/classes/main:/Users/pchabelski/IdeaProjects/scala-cli-tests/26959/.scala-build/26959_4b6553e934/classes/main -d /Users/pchabelski/IdeaProjects/scala-cli-tests/26959/.scala-build/26959_4b6553e934/classes/test -sourceroot /Users/pchabelski/IdeaProjects/scala-cli-tests/26959

Exception in thread "main" dotty.tools.dotc.core.CyclicReference: Cyclic reference involving trait CompanionTrait

 Run with -explain-cyclic for more details.
Compilation failed
```

</details>

So, re-regression bisect comes to:

Last good release: 3.10.1-RC1-bin-20260905-8163579-NIGHTLY
First bad release: 3.10.1-RC1-bin-20260909-69251c8-NIGHTLY
The culprit is https://github.com/scala/scala3/commit/63666da6f6484c5f146bb1d75dd92d7b0e12e8d7 (https://github.com/scala/scala3/pull/26842, as back ported to 3.10.0-RC2 just yesterday...)
