### ISSUE TITLE
export of members annotated with a class missing from the classpath fails with "undefined: new ..." or crashes PostTyper

### ISSUE THREAD

**Issue by jozanek** [scala/scala3#27138]
## Compiler version

3.7.4 and 3.9.0. Also reproduces on 3.3.6 and 3.2.1 (only the phase named in the message differs).

## Minimized code

Three files, compiled separately so that the annotation class is on the classpath of the library but not of the consumer (the situation when a library declares its annotation dependency as `Provided`):

```scala
// A.scala
package lib
class ann(msg: String) extends scala.annotation.StaticAnnotation
```

```scala
// B.scala
package lib
object B { @ann("x") def foo: Int = 1 }
```

```scala
// C.scala
object C { export lib.B.* }
```

```
scalac -d out-ann A.scala
scalac -cp out-ann -d out-b B.scala
scalac -cp out-b C.scala                 # crash
scalac -cp out-b -Xsemanticdb C.scala    # error
```

(Run through scala-cli 1.17.1 with `--server=false`, which invokes the plain compiler with these settings.)

## Output

With `-Xsemanticdb`:

```
-- Error: B.scala:4:2
4 |  @ann("x")
  |  ^^^^^^^^
  |undefined: new lib.ann # -1: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object lib),ann),<init>) at parser
```

Without it, the compiler crashes:

```
undefined: new lib.ann # -1: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object lib),ann),<init>) at unrollDefs

  unhandled exception while running posttyper on C.scala

Exception in thread "main" java.lang.ClassCastException: class dotty.tools.dotc.core.Types$NoType$ cannot be cast to class dotty.tools.dotc.core.Types$MethodType
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:409)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transformAnnotTree(PostTyper.scala:202)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.dotty$tools$dotc$transform$PostTyper$PostTyperTransformer$$transformAnnot(PostTyper.scala:211)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.processMemberDef$$anonfun$1(PostTyper.scala:224)
	at scala.collection.immutable.List.mapConserve(List.scala:473)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.transformAnnotations(SymDenotations.scala:249)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.processMemberDef(PostTyper.scala:224)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.processValOrDefDef(PostTyper.scala:273)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transform(PostTyper.scala:488)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1301)
	at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1301)
	at dotty.tools.dotc.transform.PostTyper$PostTyperTransformer.transformStats(PostTyper.scala:609)
	...
```

The error is reported against the library's source position (`B.scala:4`), i.e. the annotation tree copied from TASTy onto the export forwarder. The `undefined: ...` text is the fallback branch of `ErrorReporting.takesNoParamsMsg`.

Using the members directly compiles fine with the same classpath:

```scala
object D { import lib.B.*; val x: Int = foo }
```

and so does the export once `out-ann` is added to the classpath.

## Expectation

Either the export compiles (the forwarder could drop or stub annotations whose class is missing, as ordinary references to `foo` already tolerate it), or a regular error such as "class lib.ann is missing from the classpath" instead of the `undefined: ... # -1` fallback message and the PostTyper crash.

Real-world trigger: `export zio.test.Gen.*` with zio-test <= 2.0.17, whose `@silent` annotation class (silencer-lib) was a `Provided` dependency. Reported against Bloop as scalacenter/bloop#1883, where the first phase to hit it was `extractSemanticDB`.
