### ISSUE TITLE
cannot call extension methods on `transparent inline def` alias(es)

### ISSUE THREAD

**Issue by irfanstract** [scala/scala3#26656]
cannot call extension methods on `transparent inline def` alias(es) to `val`/`object`s.
cannot call extension methods on `transparent inline def` alias(es) specifically.

```scala
transparent inline def Parser: Parser1.type = Parser1

/* implementation detail; subject to being renamed */
object Parser1
type   Parser1 [+A, +Node, +Mode, -Input, +ParseMode, PredefinedIdents, ... ]


extension (C: Parser1.type)
    def gc(): Unit = { }
```

```scala
myLibrary.Parser.gc()
```

```scala
value gc is not a member of object
  (Playground.Trithon.ParsingIntra.ImmutLexerFlow :
    Playground.Trithon.ParsingIntra.ImmutLexerFlowModule){type NvriImpl = String
    }#Parser1
```
## Compiler version

`3.9.0-RC4`
`3.8`

works on `3.7.4`

## Minimized code

```scala

object Trithon {

object ParsingIntra {

// object ImmutLexerFlow {
val ImmutLexerFlow: ImmutLexerFlowModule = new AnyRef with ImmutLexerFlowModule ; trait ImmutLexerFlowModule {

opaque type NvriImpl >: String <: String = String
// type NvriImpl >: String <: String

// inline def Parser: Parser1.type = Parser1
transparent inline def Parser: Parser1.type = Parser1
// val Parser: Parser1.type = Parser1

/* subject to being renamed */
object Parser1
type   Parser1 [+A, +Node]

extension (C: Parser1.type)
    def gc(): Unit = { }

} // ImmutLexerFlowModule#

} // ParsingIntra.

object Parsing {

def gcRules()
= locally[Unit]:
    // Trithon.ParsingIntra.ImmutLexerFlow.gc(Trithon.ParsingIntra.ImmutLexerFlow.Parser ) ()
    Trithon.ParsingIntra.ImmutLexerFlow.Parser.gc()
    // Trithon.ParsingIntra.ImmutLexerFlow.Parser1.gc()

} // Parsing.

} // Trithon

```

**Output**

```scala
value gc is not a member of object
  (Playground.Trithon.ParsingIntra.ImmutLexerFlow :
    Playground.Trithon.ParsingIntra.ImmutLexerFlowModule){type NvriImpl = String
    }#Parser1
```

- **there must at-least be one `opaque type` in order for it to happen (here, `opaque type NvriImpl`) (see "inline proxies")**

- **changing the declaration of `Parser` (`transparent inline def Parser`) to `val` fixed the problem.**
  - changing to `/* deferred */ inline def` did it too in this case (see "inline proxies"); however, doing so breaks different things.
  - **changing to `val Parser1 = new AnyRef` made no difference. neither did changing `extension (C: Parser1.type)` to any other type.**

- changing the call `Parser.gc()` to `Parser1.gc()`, or desugaring the whole call (to `lib.gc(Parser) ()`), hides the problem.
  - unfortunately, **either `Parser1` or `lib` could've been an internal implemt-detail, subject to rename or being moved**, and to figure `lib` out and type it down might not be practical

- changing `ImmutLexerFlow` into `object` makes the problem go away; **unfortunately, this is not always possible**.
- changing `opaque type NvriImpl >: String <: String = String` to `type NvriImpl >: String <: String` hides the problem. again, **this breaks things**.

- downgrading to `3.7.4` fixed the problem

**Expectation**: no difference in behaviour to that in `3.7.4`; for it to behave identically like it did then

**Comment by tgodzik** [comment]
Also fails in 3.3.8 (not 3.3.7), so most likely this was a change that was ported to LTS 3.3

**Comment by Gedochao** [comment]
Last good release: 3.8.0-RC1-bin-20250917-f031eab-NIGHTLY
First bad release: 3.8.0-RC1-bin-20250918-5109a15-NIGHTLY
~d96bf104318ac486fd5e198479933865cb49e177 (#23927) is the first bad commit~
The bisect initially pointed to d96bf104318ac486fd5e198479933865cb49e177, but it seems the real culprit is c6245ed4 (#23792)
cc @jchyb
