### ISSUE TITLE
Compiler crash with annotation on main method

### ISSUE THREAD

**Issue by lrytz** [scala/scala3#22364]
```scala
//> using scala 3.6.2

import util.chaining.*

class ann(x: Int = 1, y: Int) extends annotation.Annotation

@ann(y = 22.tap(println)) @main def main = ()
```

```
Error: scala.MatchError: Block(List(ValDef(y$1,TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)],Apply(TypeApply(Select(Apply(TypeApply(TypedSplice(Ident(scalaUtilChainingOps)),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)])),List(Literal(Constant(22)))),tap),List(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit)])),List(Block(List(DefDef($anonfun,List(List(ValDef(x,TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any)],EmptyTree))),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Unit)],Apply(TypedSplice(Ident(println)),List(TypedSplice(Ident(x)))))),Closure(List(),TypedSplice(Ident($anonfun)),EmptyTree))))), ValDef(x$1,TypeTree[AnnotatedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Int),ConcreteAnnotation(Apply(Select(New(TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class unchecked)),class uncheckedVariance)]),<init>),List())))],Select(TypedSplice(Ident(ann)),$lessinit$greater$default$1))),Apply(Select(New(TypedSplice(Ident(ann))),<init>),List(TypedSplice(Ident(x$1)), NamedArg(y,TypedSplice(Ident(y$1)))))) (of class dotty.tools.dotc.ast.Trees$Block)
	at dotty.tools.dotc.typer.Namer.typedAheadAnnotationClass(Namer.scala:1774)
	at dotty.tools.dotc.typer.Namer$Completer.addAnnotations$$anonfun$1(Namer.scala:883)
```

**Comment by mbovel** [comment]
Not a crash anymore (probably following my fixes for default arguments):

```
bovel@laraserver4:/localhome/bovel/scala3$ scala -S 3.7.nightly tests/pos/22364.scala
Downloading Scala 3.7.0-RC1-bin-20250207-d60a914-NIGHTLY compiler
Downloading Scala 3.7.0-RC1-bin-20250207-d60a914-NIGHTLY bridge
Compiling project (Scala 3.7.0-RC1-bin-20250207-d60a914-NIGHTLY, JVM (17))
[error] ./tests/pos/22364.scala:5:10
[error] cannot infer type; expected type <?> is not fully defined
[error] @ann(y = 22.tap(println)) @main def main = ()
[error]          ^^^^^^
Error compiling project (Scala 3.7.0-RC1-bin-20250207-d60a914-NIGHTLY, JVM (17))
Compilation failed
```

But it should also not be an error.

**Comment by mbovel** [comment]
The essential ingredients here are `@main` and a type parameter:

```scala
def id[T](x: T): T = x

class ann(x: Int) extends annotation.Annotation

@ann(id(22)) @main def main = ()
```

**Comment by mbovel** [comment]
The root problem is how we copy annotations when we generate the `@main` proxy in 

https://github.com/scala/scala3/blob/049308f7c134d78d72cbaa61a3f1fc0ce991564d/compiler/src/dotty/tools/dotc/ast/MainProxies.scala#L101-L111

This logic was introduced in https://github.com/scala/scala3/pull/13858.
