### ISSUE TITLE
Ambigious instances of `collection.Factory`  for `Array` and `IArray`

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#26418]
Based on the Open CB failure in avokka/avokka   - [build logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/avokka/avokka/builds/scheduled_3.10.0-RC1-bin-20260626-20f6657-NIGHTLY/logs)

The introduced `Factory` instance for `IArray` might clash with `Array` definition - previously `Array` was the only instance available by default.  

## Compiler version

3.10.0-RC-nighlties 

Caused by 46599ab44d714cc06ac2e9718b16fea02d09c70b 

## Minimized code

```scala
import scala.collection.Factory

enum Result[+A]:
  case Successful(value: A)
  case Failure(cause: String)

def collect[F[_]](using f: Factory[Int, F[Int]]): Result[F[Int]] =
  Result.Successful(f.fromSpecific(Nil))

@main def test(): Unit =
  collect match
    case Result.Successful(result) => result
    case Result.Failure(cause)     => cause
```

## Output

```scala
scala compile test.scala -S 3.nightly
Compiling project (Scala 3.10.0-RC1-bin-20260627-e449094-NIGHTLY, JVM (25))
[error] ./test.scala:13:10
[error] Ambiguous given instances: both method arrayFactory in object Factory and given instance IArrayFactory in object Factory match type scala.collection.Factory[Int, F[Int]] of parameter f of method collect
[error]   collect match
[error]          ^
[error] ./test.scala:14:39
[error] Not found: result
[error]     case Result.Successful(result) => result
[error]                                       ^^^^^^
[error] ./test.scala:15:39
[error] Not found: cause
[error]     case Result.Failure(cause)     => cause
[error]                                       ^^^^^
Error compiling project (Scala 3.10.0-RC1-bin-20260627-e449094-NIGHTLY, JVM (25))
Compilation failed

```

## Workaround 

Use explicit factory with a type hint, eg `collect[IArray]`, `collect[Array]`

## Expectation

We can either: 
- assume it's a wont fix - user is required to explicityl select the Factory 
- move `IArray` instance to trait so that `Array` instance is still selected by default (well known strategy to setup priority of implicits via inheritence rules)

**Comment by bishabosha** [comment]
its wild that this worked at all i mean its purely a fluke that there was aparently only one factory in the Factory companion object then, theres not even an expected type in `collect` so its semantic is "pick whichever is the first one",

and our policy is not source compatibility

**Comment by WojciechMazur** [comment]
> its wild that this worked at all i mean its purely a fluke that there was aparently only one factory in the Factory companion  

Agree, that's why I don't classify it as a regression 

> and our policy is not source compatibility

For this one I cannot fully agree. In this particual case (new minor) I can agree, but within a patch releases source compatibility should be preserved (since by definition patch release should be both forwards and backward compatible with other releases within the same minor) 

There seems to be more issues found in the community, here's another related issues spotted in `scalikejdbc/scalikejdbc` 

```scala
import scala.collection.Factory

class SQLBatch[C[_]](params: Seq[Seq[Any]]):
  def apply()(using factory: Factory[Int, C[Int]]): C[Int] =
    factory.fromSpecific(Nil)

def batch[C[_]](params: Seq[Any]*): SQLBatch[C] =
  new SQLBatch(params.toSeq)

@main def test(): Unit =
  val params: Seq[Seq[Any]] = (1 to 3).map(i => Seq(i, "name" + i))
  batch(params*).apply()
```

**Comment by bishabosha** [comment]
well i guess the supertrait as you suggested is a small price if it avoids churn :)

**Comment by sjrd** [comment]
Break it. This change needs a minor release anyway.

**Comment by Gedochao** [comment]
I guess we should close this as intentional behaviour... should we have a better error/warning?

**Comment by bishabosha** [comment]
```scala
def batch[C[_]](params: Seq[Any]*): SQLBatch[C] =
  new SQLBatch(params.toSeq)

@main def test(): Unit =
  val params: Seq[Seq[Any]] = (1 to 3).map(i => Seq(i, "name" + i))
  batch(params*).apply()
```
i mean again `batch(...).apply(): Unit` with nothing to guide what should be the result type is surely begging for ambiguity

**Comment by WojciechMazur** [comment]
FYI: @gbicou @xuwei-k
