### PR TITLE
Fix regression: more frequently cast the result of transparent inline

### LINKED ISSUE #26656: cannot call extension methods on `transparent inline def` alias(es)
cannot call extension methods on `transparent inline def` alias(es) to `val`/`object`s.
cannot call extension methods on `transparent inline def` alias(es) specifically.

```scala
transparent inline def Parser: Parser1.type = Parser1

/* implementation detail; subject to being renamed */
object Parser1
type   Parser1 [+A, +Node, +Mode, -Input, +ParseMode, PredefinedIdents, ... ]


extension (C: Parser1.type)
    def gc(): Unit = { }
```

```scala
myLibrary.Parser.gc()
```

```scala
value gc is not a member of object
  (Playground.Trithon.ParsingIntra.ImmutLexerFlow :
    Playground.Trithon.ParsingIntra.ImmutLexerFlowModule){type NvriImpl = String
    }#Parser1
```
## Compiler version

`3.9.0-RC4`
`3.8`

works on `3.7.4`

## Minimized code

```scala

object Trithon {

object ParsingIntra {

// object ImmutLexerFlow {
val ImmutLexerFlow: ImmutLexerFlowModule = new AnyRef with ImmutLexerFlowModule ; trait ImmutLexerFlowModule {

opaque type NvriImpl >: String <: String = String
// type NvriImpl >: String <: String

// inline def Parser: Parser1.type = Parser1
transparent inline def Parser: Parser1.type = Parser1
// val Parser: Parser1.type = Parser1

/* subject to being renamed */
object Parser1
type   Parser1 [+A, +Node]

extension (C: Parser1.type)
    def gc(): Unit = { }

} // ImmutLexerFlowModule#

} // ParsingIntra.

object Parsing {

def gcRules()
= locally[Unit]:
    // Trithon.ParsingIntra.ImmutLexerFlow.gc(Trithon.ParsingIntra.ImmutLexerFlow.Parser ) ()
    Trithon.ParsingIntra.ImmutLexerFlow.Parser.gc()
    // Trithon.ParsingIntra.ImmutLexerFlow.Parser1.gc()

} // Parsing.

} // Trithon

```

**Output**

```scala
value gc is not a member of object
  (Playground.Trithon.ParsingIntra.ImmutLexerFlow :
    Playground.Trithon.ParsingIntra.ImmutLexerFlowModule){type NvriImpl = String
    }#Parser1
```

- **there must at-least be one `opaque type` in order for it to happen (here, `opaque type NvriImpl`) (see "inline proxies")**

- **changing the declaration of `Parser` (`transparent inline def Parser`) to `val` fixed the problem.**
  - changing to `/* deferred */ inline def` did it too in this case (see "inline proxies"); however, doing so breaks different things.
  - **changing to `val Parser1 = new AnyRef` made no difference. neither did changing `extension (C: Parser1.type)` to any other type.**

- changing the call `Parser.gc()` to `Parser1.gc()`, or desugaring the whole call (to `lib.gc(Parser) ()`), hides the problem.
  - unfortunately, **either `Parser1` or `lib` could've been an internal implemt-detail, subject to rename or being moved**, and to figure `lib` out and type it down might not be practical

- changing `ImmutLexerFlow` into `object` makes the problem go away; **unfortunately, this is not always possible**.
- changing `opaque type NvriImpl >: String <: String = String` to `type NvriImpl >: String <: String` hides the problem. again, **this breaks things**.

- downgrading to `3.7.4` fixed the problem

**Expectation**: no difference in behaviour to that in `3.7.4`; for it to behave identically like it did then

### PR DESCRIPTION
**Pull request by jchyb**
Fixes #26656
In the issue minimisation (that I included in the PR in a slightly adjusted form, for readability), the `Parser` method would expand into:
```scala
{
  val $proxy1:
    
      (ParsingIntra.ImmutLexerFlow : ParsingIntra.ImmutLexerFlowModule){
        type NvriImpl = String}
    
   =
    ParsingIntra.ImmutLexerFlow.$asInstanceOf[
      
        (ParsingIntra.ImmutLexerFlow : ParsingIntra.ImmutLexerFlowModule){
          type NvriImpl = String}
      
    ]
  val ImmutLexerFlowModule_this:
    
      ($proxy1 :
        (ParsingIntra.ImmutLexerFlow : ParsingIntra.ImmutLexerFlowModule){
          type NvriImpl = String}
      )
    
   = $proxy1
  ImmutLexerFlowModule_this.Parser1:ImmutLexerFlowModule_this.Parser1.type
}
```
of type 
```scala
(ParsingIntra.ImmutLexerFlow : ParsingIntra.ImmutLexerFlowModule){type NvriImpl = String}#Parser1
```
This passed the check `(ParsingIntra.ImmutLexerFlow : ParsingIntra.ImmutLexerFlowModule){type NvriImpl = String}#Parser1 <:<  (ParsingIntra.ImmutLexerFlow.Parser :=> ParsingIntra.ImmutLexerFlow.Parser1.type)`, which later caused problems with implicit resolution as due to the more complex prefix with a RefinedType, the extension method would not be found. Since we already reconstruct the alias-less result type (like used in the check above), we now forcefully cast to it more frequently, skipping the subtype check also more frequently (in favor of type shape equality check).

Worth noting - since we now return `{...}.asInstanceOf(...) `more frequently I somewhat expect there to be issues with libraries with macros that rely on transparent inline defs returning certain shape. Ultimately, I can't think of any better solution, so affected libraries might need to update, and that's something we also did in the past so I think it's fine.

## Have you relied on LLM-based tools in this contribution?

No

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala [hunk 1]
```diff
@@ -650,14 +650,17 @@ object Inlines:
           if inlinedMethod.is(Transparent) then
             val unpacked = unpackProxiesFromResultType(inlined)
             val withAdjustedThisTypes = if call.symbol.is(Macro) then fixThisTypeModuleClassReferences(unpacked) else unpacked
-            (call.tpe & withAdjustedThisTypes, withAdjustedThisTypes != unpacked)
+            (call.tpe & withAdjustedThisTypes, withAdjustedThisTypes != inlined.tpe)
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/inlines/Inlines.scala:653]: Do I understand correctly that, we compare against `inlined.tpe` instead of `call.tpe` because a transparent inline’s result type is the type of the inlined expansion?

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala [hunk 2]
```diff
@@ -650,14 +650,17 @@ object Inlines:
...
         // see https://github.com/scala/scala3/issues/25091
         val resultType = target.widenIfUnstable
         if forceCast then
-          // we need to force the cast for issues with ThisTypes, as ensureConforms will just
-          // check subtyping and then choose not to cast, leaving the previous, incorrect type
+          // We might need to force the cast for various issues, as a subtype check/ensureConform
+          // will leave out the previous type which might not be correct, e.g.:
+          //  * fixes for nonsense ThisTypes that expose opaque types would fall through any subtype check
+          //  * RefinedTypes are skipped when looking for implicits, so we want to avoid
+          //    the ones with generated RefinedType prefixes if we can
```
Comment (tanishiking) [inline compiler/src/dotty/tools/dotc/inlines/Inlines.scala:663]: So, previously, we forceCast only for macros that produced incorrect `ThisTypes` (we can't bring `ThisType` out to call-site), and this change also forceCast when opaque proxies introduce refinements whose shape differs from the type on the inlined tree (we need to cast, because refined type is subtype of target...)

**Review by tanishiking — APPROVED** [review]
LGTM :+1:

> Ultimately, I can't think of any better solution,

Agree, and I feel `forceCast`ing to seal the compiler-generated opaque proxy refinement is pretty natural.

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala (hunk 1 above)
Comment (jchyb) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala:653]: Yes, but it's good to think of it as "have any of the 2 operations adjusted the type", since `unpackProxiesFromResultType` will by default return `inlined.tpe`, so this is essentially what we are starting with.

File: compiler/src/dotty/tools/dotc/inlines/Inlines.scala (hunk 2 above)
Comment (jchyb) [reply compiler/src/dotty/tools/dotc/inlines/Inlines.scala:663]: Yes, we have the [opaque proxy reverse mapping] and [ThisType fixes], and if any of those 2 adjust the type in some way, we cast. I previously thought we didn't need to do that for unpackProxiesFromResultType, since the difference in the actual type should be caught by a subtype check, and users can't really access the exposed opaque types from prefixes, but I hadn't considered how this would affect the implicit resolution.
