### ISSUE TITLE
-language:strictEquality conflicts with -Wunused:locals

### ISSUE THREAD

**Issue by vandmo** [scala/scala3#25432]
`-Wunused:locals` doesn't seem to recognize that `given CanEqual[StatusCode, StatusCode] = CanEqual.derived` is needed when `-language:strictEquality` is enabled.

## Compiler version

3.8.2

## Minimized code
X.scala
```scala
class StatusCode(val code: Int) extends AnyVal
val Ok = StatusCode(200)

def amethod =
  given CanEqual[StatusCode, StatusCode] = CanEqual.derived
  Ok match
    case Ok =>
      "ok"
    case other =>
      "other"
```

Y.scala
```scala
class StatusCode(val code: Int) extends AnyVal
val Ok = StatusCode(200)

def amethod =
  Ok match
    case Ok =>
      "ok"
    case other =>
      "other"
```

run.bash
```bash
#!/usr/bin/env bash
set -eu -o pipefail

scala -version
scala compile X.scala -language:strictEquality -Wunused:locals || true
scala compile Y.scala -language:strictEquality -Wunused:locals || true
```

## Output

```
Scala code runner version: 1.12.2
Scala version (default): 3.8.2
[warn] ./X.scala:5:9
[warn] unused local definition
[warn]   given CanEqual[StatusCode, StatusCode] = CanEqual.derived
[warn]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compiling project (Scala 3.8.2, JVM (21))
[error] ./Y.scala:6:10
[error] Values of types StatusCode and StatusCode cannot be compared with == or !=
[error]     case Ok =>
[error]          ^^
Error compiling project (Scala 3.8.2, JVM (21))
Compilation failed
```

## Expectation

When compiling X.scala I am expecting to not get a warning.

**Comment by vandmo** [comment]
Same issue with `-Wunused:imports`

**Comment by vandmo** [comment]
Seems to work with 3.7.4

**Comment by som-snytt** [comment]
The fix for the linked ticket covers local definitions as well. It arrives in 3.8.3.

The fix was to lint after pattern matching. (It already works for explicit `==`.)

Thanks for the report. It could use a regression test for locals.
