### ISSUE TITLE
ScalaJS macro regression: Cannot resolve delambdafy target method

### ISSUE THREAD

**Issue by TomasMikula** [scala/scala3#25198]
## Compiler version

|  | JVM   | JS |
| --- | --- | --- |
| Scala 3.7.4 | ✅ | ✅ |
| Scala 3.8.1 | ✅ | ❌ |

## Minimized code

`Macros.scala`

```scala
import scala.quoted.*

object Macros:
  transparent inline def foo: String => String =
    ${ fooImpl }

  // Synthesizes x => x
  private def fooImpl(using Quotes): Expr[String => String] =
    import quotes.reflect.*

    val methSym =
      Symbol.newMethod(
        Symbol.spliceOwner,
        name = "fooImpl",
        tpe = MethodType(List("x"))(
          _ => List(TypeRepr.of[String]),
          _ => TypeRepr.of[String],
        ),
      )

    val meth =
      DefDef(
        methSym,
        rhsFn = { argss =>
          val List(List(x)) = argss
          Some(x.asInstanceOf[Term])
        }
      )

    Block(
      List(meth),
      Closure(Ident(methSym.termRef), tpe = None),
    ).asExprOf[String => String]
```

`Main.scala`

```scala
//> using scala 3.8.1
//> using js-version 1.20.2

object Main:
  val f: String => String =
    Macros.foo

  @main def go =
    println(f("Hello"))
```

## Output

```
% scala -Xcheck-macros --js Main.scala Macros.scala
Warning: setting /Users/tomas/tmp/scala3-js-macro-regression as the project root directory for this run.
Compiling project (Scala 3.8.1, Scala.js 1.20.2)
Error: Cannot resolve delambdafy target method fooImpl at Main.scala:5
Error compiling project (Scala 3.8.1, Scala.js 1.20.2)
Compilation failed
```

## Expectation

Should compile and run on ScalaJS just like on the JVM, or like on Scala 3.7.4 (JVM or JS).

**Comment by Gedochao** [comment]
Last good release: 3.8.0-RC1-bin-20251007-71fcd1a-NIGHTLY
First bad release: 3.8.0-RC1-bin-20251008-6194563-NIGHTLY
Bisect marks 512b5c73c28a4db1b634ed92f913b955cf3c145c as the first bad commit (cc @hamzaremmal), which seems relevant
- https://github.com/scala/scala3/pull/24115

Tagging cc @sjrd for good measure.

**Comment by sjrd** [comment]
This works:
```diff
     val methSym =
       Symbol.newMethod(
         Symbol.spliceOwner,
-        name = "fooImpl",
+        name = "$anonfun$fooImpl",
         tpe = MethodType(List("x"))(
           _ => List(TypeRepr.of[String]),
           _ => TypeRepr.of[String],
         ),
       )
```
@jchyb Is it expected that `Closure(...)` lets one reference non-anonymous functions? Could we mandate that only methods whose name starts with `$anonfun` are allowed in `Closure`? That's an invariant that the compiler upholds, but apparently macros are not subject to that restriction.

**Comment by jchyb** [comment]
I suspect this was overlooked before, adding an additional assertion there should not be an issue (outside of that possibly breaking some existing libraries, but if we do it under `-Xcheck-macros`, it should be fine).
