### PR TITLE
Avoid forcing ctors & parents which caused cycles

### LINKED ISSUE #15177: Spurious 'type is not a member'
## Compiler version

3.0.0 - 3.2.0-RC1-bin-20220511-7c446ce-NIGHTLY

## Minimized code

```Scala
trait DomainIdProvider[T] {
  type Id = List[T]
}
object Country extends DomainIdProvider[Country]
case class Country(
    id: Country.Id,
) 
```

## Output

```
type Id is not a member of object Country
```

## Explanation
This always compiles fine on 2.13 and sometimes on 3. I couldn't find the exact rule when it compiles and when it doesn't.
In the example above it would compile fine if i move case class definition before object, but in other cases this doesn't help.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #15177

The current class completion eagerly completes the constructor before finishing.  This means that any reference within the constructor that ends up referencing that class would fail as "cyclic" even though the actual classes aren't cyclic.  With the change in #16664 "Disallow constructor params from appearing in parent types for soundness", I thought perhaps that was the motivation for the completion, so with that motivation going away we could fix this code.  It turns out that DerivedFromParamTree perhaps was at the centre of this.  Without changing that scheme, I allowed for the necessary indexing to occur on the constructor for successful compilation, deferring the rest of the constructor completion for later.

It seems this has impacted a number of users, it used to work in Scala 2, and there's nothing wrong with it compiling, so I think we find a way to make it.

### CODE REVIEW

**Comment by dwijnand** [comment]
Added comments to the changes and added detail to the PR description.

File: compiler/src/dotty/tools/dotc/typer/Namer.scala [hunk 1]
```diff
@@ -986,15 +995,18 @@ class Namer { typer: Typer =>
...
      *  yet completed. Test case is pos/i10967.scala.
      */
     override def needsCompletion(symd: SymDenotation)(using Context): Boolean =
       val owner = symd.owner
       !owner.exists
       || owner.is(Touched)
       || {
-        owner.ensureCompleted()
+        // Only complete the owner if it's a type (eg. the class that owns a type parameter)
+        // This avoids completing primary constructor methods while completing the type of one of its type parameters
```
Comment (SethTisue) [inline compiler/src/dotty/tools/dotc/typer/Namer.scala:1007]: maybe include a bug number here?

File: compiler/src/dotty/tools/dotc/core/Types.scala [hunk 2]
```diff
@@ -196,7 +196,9 @@ object Types extends TypeUtils {
      */
     def isRef(sym: Symbol, skipRefined: Boolean = true)(using Context): Boolean = this match {
       case this1: TypeRef =>
-        this1.info match { // see comment in Namer#TypeDefCompleter#typeSig
+        // avoid forcing symbol if it's a class, not a type alias
```
Comment (SethTisue) [inline compiler/src/dotty/tools/dotc/core/Types.scala:199]: perhaps include a bug number here?

**Comment by dwijnand** [comment]
@odersky Can I do anything to assist in reviewing and merging this?

**Review by odersky — COMMENTED** [review]
It's difficult for me to review this because the change set is large and the issues are very subtle. Would it be possible to split this in two commits? The first commit should only refactor things and move code around (it seems there's quite a bit of that). The second commit should then change the logic.

**Comment by dwijnand** [comment]
Yep absolutely.

**Review by odersky — APPROVED** [review]
It's complicated, but i think I get it. Looks good to me!

**Comment by dwijnand** [comment]
Thank you Martin.
