### ISSUE TITLE
Given definition is no longer resolved to in mapped function usage site.

### ISSUE THREAD

**Issue by sageserpent-open** [scala/scala3#24192]
## Compiler version

3.3.7 (also seen in 3.7.3)

## Minimized code

```scala
//> using scala 3.3.7
//> using options -Wall -Werror

case class MergeResult[Element: Eq] private (segments: Seq[Segment[Element]]):

  def fuseWith(another: MergeResult[Element])(
      elementFusion: (Element, Element) => Option[Element]
  ): Option[MergeResult[Element]] =
    if segments.size != another.segments.size then None
    else
      Traverse[Seq]
        .traverse(segments.zip(another.segments))(_.fuseWith(_)(elementFusion))
        .map(MergeResult.apply)
        //               ^^^^^ Can't find the given for Eq[Any], despite there
        //                     being an Eq[Element] available.
```

## Output

```
No given instance of type cats.kernel.Eq[Any] was found for a context parameter of method apply in object MergeResult
        .map(MergeResult.apply)
```

## Expectation

This used to build under 3.3.6, now fails because the given for `Eq[Element]` is not used, rather a search for `Eq[Any]` takes place.

My expectation was that the explicit return type of `Option[Element]` should have forced the correct resolution of the given.

NOTE: changing the function application to `MergeResult.apply[Element]` works around this problem.

**Comment by Gedochao** [comment]
When posting compiler bugs, please include the dependencies and imports alongside the code.

I managed to guess that we're likely missing something along the lines of:
```scala
//> using dep org.typelevel::cats-core:2.13.0
import cats.kernel.Eq
import cats.Traverse
import cats.syntax.traverse.*
```
but I still can't figure out where's `Segment` from.
@sageserpent-open please edit the issue description with a self-contained snippet.

(not to mention that we'll likely need to minimize this outside of depending on `cats-core`, but that's the next step)

**Comment by sageserpent-open** [comment]
@Gedochao Oops - was in the middle of something else, completely forgot to make the Cats dependency explicit.

No, I don't use the Scala CLI - I build with SBT / IntelliJ. I did try using `scala-cli`, but was rewarded with:

```
Starting compilation server
Error: bloop.rifle.FailedToStartServerExitCodeException: Server failed with exit code 1
For more details, please see '.../scratches/.scala-build/stacktraces/1760693332-6033940442433224837.log'
Running
  scala-cli bloop output
might give more details.
```

I think one additional problem at a time is enough for me, please excuse the fast-and-loose approach. 😬 

Ah, yes, `Segment` is missing too. To be honest I was hoping it would be obvious to you folks just looking at the error and shape of the code, but it's completely reasonable to expect something that builds, so here's a minimised example:

```scala
//> using dep org.typelevel::cats-core::2.9.0
//> using dep org.scala-lang.modules::scala-collection-contrib::0.4.0

import cats.{Eq, Traverse}

object ParameterisedWithTypeClassConstraint:
  enum Segment[Element: Eq]:
    case Resolved(elements: Seq[Element])(using eq: Eq[Element])
  end Segment

  given segmentEquality[Element](using
      elementEquality: Eq[Element]
  ): Eq[Segment[Element]] = ???
end ParameterisedWithTypeClassConstraint

case class ParameterisedWithTypeClassConstraint[Element: Eq] private (
    segments: Seq[ParameterisedWithTypeClassConstraint.Segment[Element]]
):

  def thisFailsToCompile: Option[ParameterisedWithTypeClassConstraint[Element]] =
    // This import seems to trigger the failure...
    import scala.collection.decorators.*

    Traverse[Seq]
      .sequence(
        Seq.empty[Option[ParameterisedWithTypeClassConstraint.Segment[Element]]]
      )
      .map(ParameterisedWithTypeClassConstraint.apply)

  def thisCompilesSuccessfully: Option[ParameterisedWithTypeClassConstraint[Element]] =
    // ... but only when the traversal is inlined.
    import scala.collection.decorators.*

    val intermediateExpression = Traverse[Seq].sequence(
      Seq.empty[Option[ParameterisedWithTypeClassConstraint.Segment[Element]]]
    )

    intermediateExpression
      .map(ParameterisedWithTypeClassConstraint.apply)
  end thisCompilesSuccessfully

  def thisAlsoCompilesSuccessfully: Option[ParameterisedWithTypeClassConstraint[Element]] = {
    // No import, no problem.
    Traverse[Seq]
      .sequence(
        Seq.empty[Option[ParameterisedWithTypeClassConstraint.Segment[Element]]]
      )
      .map(ParameterisedWithTypeClassConstraint.apply)
  }

  def thisCompilesSuccessfullyToo
  : Option[ParameterisedWithTypeClassConstraint[Element]] =
    // An explicit type on the constructor application also fixes this.
    import scala.collection.decorators.*

    Traverse[Seq]
      .sequence(
        Seq.empty[Option[ParameterisedWithTypeClassConstraint.Segment[Element]]]
      )
      .map(ParameterisedWithTypeClassConstraint.apply[Element])
    //                                               ^^^^^^^^^
  end thisCompilesSuccessfullyToo

end ParameterisedWithTypeClassConstraint
```

I'm glad I did miminise this, because it shows some kind of interplay between the import of the decorators and the Cats traversal. Why this also depends on whether or not the Cats traversal is inlined or bound to a local variable is beyond me.

Again, this wasn't present in Scala 3.3.6 but is in 3.3.7. 

@tgodzik had a theory about this on the discussion over here: https://users.scala-lang.org/t/mapping-with-a-function-that-takes-a-using-argument-in-scala-3-3-7/12076/7

**Comment by sageserpent-open** [comment]
> (not to mention that we'll likely need to minimize this outside of depending on `cats-core`, but that's the next step)

I did try substituting an equivalently typed expression instead of the Cats traversal, but failed to duplicate the error. Given that inlining the traversal expression seems to be connected, I imagine you'll either have to stick with Cats for the time being or substitute with an equivalent expression.

I'll leave the latter choice as an exercise to the reader.

**Comment by Gedochao** [comment]
> No, I don't use the Scala CLI - I build with SBT / IntelliJ. I did try using `scala-cli`, but was rewarded with:
>
> ```
> Starting compilation server
> Error: bloop.rifle.FailedToStartServerExitCodeException: Server failed with exit code 1
> For more details, please see '.../scratches/.scala-build/stacktraces/1760693332-6033940442433224837.log'
> Running
>   scala-cli bloop output
> might give more details.
> ```

@sageserpent-open Feel free to raise it at https://github.com/VirtusLab/scala-cli/issues / https://github.com/scalacenter/bloop/issues and we can debug it there, of course, but for a fast and loose approach...
When in doubt, you can always skip Bloop with `--server=false`:
```bash
scala-cli . --server=false
```

**Comment by sageserpent-open** [comment]
> [@sageserpent-open](https://github.com/sageserpent-open) Feel free to raise it at https://github.com/VirtusLab/scala-cli/issues / https://github.com/scalacenter/bloop/issues and we can debug it there, of course, but for a fast and loose approach...
> When in doubt, you can always skip Bloop with `--server=false`:

For the sake of completeness, I tried that and encountered an error regarding Java 21 being an invalid choice. That made me think about the provenance of `scala-cli` on my machine and it turned out to be quite an old version, 1.0.0.

Upgrading to 1.9.1 fixed *that* problem, so Scala CLI reproduces the reported bug. I've golfed the code down slightly and edited the comment above to reflect that.

**Comment by Gedochao** [comment]
> That made me think about the provenance of scala-cli on my machine and it turned out to be quite an old version, 1.0.0.

...yeah, that's somewhat expected if you were running such an old version 😅

**Comment by Gedochao** [comment]
Last good 3.3 LTS release: 3.3.7-RC1-bin-20250726-068c6c7-NIGHTLY
First bad 3.3 LTS release release: 3.3.7-RC1-bin-20250729-e9954cc-NIGHTLY
(the bisect script isn't very useful for finding the exact backported commit because of #24220)

Last good release: 3.7.3-RC1-bin-20250717-fb66af2-NIGHTLY
First bad release: 3.7.3-RC1-bin-20250718-42fdd76-NIGHTLY
45f7ef6e5d1f9a3b45b77b933470de43760b0c72 is the first bad commit (https://github.com/scala/scala3/pull/23532)
cc @odersky

**Comment by odersky** [comment]
It would be good to minimize this further without external dependencies. The bisected commit is reasonable in that it makes type inference work in a case that should obviously compile and did compile in Scala 2, but not in Scala 3. The example here is at the moment too complicated to be able to say whether it should obviously work or not.

**Comment by sageserpent-open** [comment]
@odersky The code has been minimised down to an individual short method. 

In addition, you have three versions of that method to show contributory factors - namely the use of a sub expression written inline within a more complex expression, versus using a named binding instead of the subexpression, as well as sticking with the inlined form but avoiding the import.

You may well argue that the use of the import renders the intent of the code inscrutable (it was actually used elsewhere in the original code and is irrelevant to the snippet that doesn’t compile), but the lack of consistency between the inlined and named binding is surely a bug in its own right.

I should add that there is a fourth variation, namely using an explicit type parameterisation on the call to `ParameterisedWithTypeClassConstraint.apply` in the final mapping. This also removes the compilation error, even in the presence of the import and with an inlined subexpression.

I think at this point, especially when you also have the commit that caused the problem, you should have enough information in a sufficiently constrained context to analyse this.

I’m reporting this on the assumption that the team would like to be informed, but it’s not holding me back right now. Whether you choose to do so or what its priority should be is of course down to you folks.

Thanks.

**Comment by odersky** [comment]
That's not how it works. Type inference is affected by a lot of factors. It's entirely possible that an inline function and a normal method behave differently. And it's entirely possible that the root cause does not come rom the code shown but from a dependency. To be able to spend my time on this I need a minimized example without external dependencies first.

**Comment by sageserpent-open** [comment]
> That's not how it works. Type inference is affected by a lot of factors. It's entirely possible that an inline function and a normal method behave differently.

Let's be clear - the reduced example I posted above shows an *expression*, namely:

```scala
Traverse[Seq]
      .sequence(
        Seq.empty[Option[ParameterisedWithTypeClassConstraint.Segment[Element]]]
      )
```

being **substituted directly** into a larger expression in the failing case, and being captured in a named binding and then substituted in the same larger expression via its name. I did use the word 'inline', but I meant this loosely, and I think you would have picked up on that nuance.

Are you saying that referential transparency should not apply here?



> And it's entirely possible that the root cause does not come rom the code shown but from a dependency.

Yet the code does compile with the (actually irrelevant) dependency on Scala Collections Contrib in some cases. The semantics of the compiled code are pretty clear.


> To be able to spend my time on this I need a minimized example without external dependencies first.

Your reluctance is duly noted.

Let's see, we have from the import:

```scala
package object decorators {

  implicit def iteratorDecorator[A](it: Iterator[A]): IteratorDecorator[A] =
    new IteratorDecorator[A](it)

  implicit def iterableDecorator[C](coll: C)(implicit it: IsIterable[C]): IterableDecorator[C, it.type] =
    new IterableDecorator(coll)(it)

  implicit def seqDecorator[C](coll: C)(implicit seq: IsSeq[C]): SeqDecorator[C, seq.type] =
    new SeqDecorator(coll)(seq)

  implicit def mapDecorator[C](coll: C)(implicit map: IsMap[C]): MapDecorator[C, map.type] =
    new MapDecorator(coll)(map)

  implicit def bitSetDecorator[C <: BitSet & BitSetOps[C]](bs: C): BitSetDecorator[C] =
    new BitSetDecorator(bs)

  implicit def mutableBitSetDecorator(bs: mutable.BitSet): MutableBitSetDecorator =
    new MutableBitSetDecorator(bs)

}
```

As for `Traverse.sequence`, this has a type signature of:

```scala
trait Traverse[F[_]] extends Functor[F] with Foldable[F] with UnorderedTraverse[F] { self =>

  def traverse[G[_]: Applicative, A, B](fa: F[A])(f: A => G[B]): G[F[B]]
```

I'm confident you could work with this, these dependencies are easy to access in an SBT or Scala CLI project, or you could just look through them yourself (I did, but nothing jumped out as significant).

It's your choice; I'm not holding this over your head.



In closing, I've edited the reduced example I posted above to include that fourth variation, in case anyone is interested at some point in the future.

**Comment by tanishiking** [comment]
Thanks @sageserpent-open !
One step further removing dependency:

```scala
//> using scala 3.3.7

trait IsMap[Repr]
trait Eq[A]
trait Applicative[F[_]]

trait MyTraverse[F[_]]:
  def sequence[G[_]: Applicative, A](fga: F[G[A]]): G[F[A]] = ???

object MyTraverseSeq extends MyTraverse[Seq]

object ParameterisedWithTypeClassConstraint:
  enum Segment[Element: Eq]:
    case Resolved(elements: Seq[Element])(using eq: Eq[Element])
  end Segment

  given segmentEquality[Element](using
      elementEquality: Eq[Element]
  ): Eq[Segment[Element]] = ???

end ParameterisedWithTypeClassConstraint

case class ParameterisedWithTypeClassConstraint[Element: Eq] private (
    segments: Seq[ParameterisedWithTypeClassConstraint.Segment[Element]]
):
  import ParameterisedWithTypeClassConstraint.Segment

  def thisFailsToCompile: Option[ParameterisedWithTypeClassConstraint[Element]] =
    implicit def mapDecorator[C](coll: C)(implicit map: IsMap[C]): Map[C, map.type] = ???

    MyTraverseSeq
      .sequence(
        Seq.empty[Option[ParameterisedWithTypeClassConstraint.Segment[Element]]]
      ).map(ParameterisedWithTypeClassConstraint.apply)

end ParameterisedWithTypeClassConstraint
```

**Comment by tanishiking** [comment]
Ah, @WojciechMazur made an minimum reproducible example in https://github.com/scala/scala3/issues/24255, I reduce the example a bit further from there:

```scala
//> using scala 3.3.7

// https://github.com/scala/scala-collection-contrib/blob/main/src/main/scala/scala/collection/decorators/package.scala
object decorators {
  trait IsMap[A]
  implicit def mapDecorator[C](coll: C)(implicit map: IsMap[C]): Map[C, map.type] = ???
}
import decorators.mapDecorator // unused, required to reprouce

trait Eq[T]
trait Applicative[F[_]]
given Applicative[Option] = ???

trait Traverse[F[_]]:
  // context bound required to reproduce
  def sequence[G[_]: Applicative, A](fga: F[G[A]]): G[F[A]] = ???

object Traverse:
  def apply[F[_]]: Traverse[F] = ???

trait Segment[Element: Eq]

case class MergeResult[Element: Eq] private (segments: Seq[Segment[Element]]):
  def thisFailsToCompile(): Option[MergeResult[Element]] =
    Traverse[Seq]
      .sequence(Seq.empty[Option[Segment[Element]]])
      .map(MergeResult.apply) // error
```

**Comment by odersky** [comment]
Thanks @tanishiking! I can reproduce it.

**Comment by tgodzik** [comment]
We decided to revert this change for 3.3.8, but it would require considerable effort to fix in Scala Next

**Comment by sageserpent-open** [comment]
> We decided to revert this change for 3.3.8, but it would require considerable effort to fix in Scala Next

I’m glad it’s fixed (kinda) in the 3.3 series. To be honest I’d much rather stick with that as long as possible anyway. Consider this a vote for Scala 3.3 being the next 2.13. 😀

**Comment by som-snytt** [comment]
The linked PR uses the minimization. It explains the "unused import" noted on the test.

Probably I wanted to exercise the fix more thoroughly? I can try it against the `cats` example. It does demonstrate that an "approximate" reproduction is rarely sufficient, and a self-contained minimization is immensely helpful.

Maybe with more work and experience (which are good things in themselves) I could invent more tests.

**Comment by sageserpent-open** [comment]
>  It does demonstrate that an "approximate" reproduction is rarely sufficient, and a self-contained minimization is immensely helpful.

Perhaps there was some behind-the-scenes activity involving the original bug reproduction I submitted, and this failed to yield fruit? Was this actually tried? Not sure what ‘demonstrate’ connotes here…

I really don’t want to harp on sourly over this, especially when the bug has been fixed, but I’m not yet convinced of the pushback on this earlier on the ticket that seems to be echoed here. Was the expectation for end users to write internal example tests? I *can* understand folks’ desire not to involve third party dependencies in the build of the compiler, as it sets up a kind of circular dependency, but this is a bug report.

Anyway, thanks to everyone for going that extra bit further with the bug reproduction and for the bug fix, including @WojciechMazur’s effort with the CB failure. It’s appreciated. 👏

**Comment by som-snytt** [comment]
@sageserpent-open Apologies, I didn't intend to harp. My connotation was that there was a reason I hadn't linked my PR to the ticket, namely that I would have higher confidence after adding focused tests. (I must have looked at the ticket casually and then forgotten about it.)

My reading of the earlier comments on the ticket is not that the bug report fails to meet criteria for acceptance.

It's also true that the little steps toward a minimized test do grease the wheels.

I would argue for "agile" bug reporting, because the reporter doesn't want to invest in a ticket that is marked duplicate. Sometimes a stack trace is sufficient for that.

As an illustration, I just closed https://github.com/scala/scala3/issues/23293 and my PR from May as a duplicate where my PR from August (improved last week to address the Odersky review that I hadn't figured out what was going on) fixes it better. I don't think improving the minimization on the first ticket would have helped, as I had a unit test. But only after the second ticket (and a nudge) did it progress.

Note that the PR for this ticket has two lines, the fix and a tweak. I just spent quite some time to understand the tweak, which was something I knew the history of. Now I'll address the fix and its tests. Probably I should vibe code the tests.

**Comment by sageserpent-open** [comment]
> Apologies, I didn't intend to harp.

@som-snytt No bother, I'm the harpist (or it harpy - maybe sourpuss?) here. 😀 Appreciate your thoughtful response.

> Probably I should vibe code the tests.

Now, that is something topical for me: https://github.com/sageserpent-open/americium/issues/255. But I digress...
