### PR TITLE
Delay hard argument comparisons

### LINKED ISSUE #19999: No longer able to extract a type from an intersection
## Compiler version

*Does not* compile on 3.4.0 (or 3.0.0, 3.1.0, 3.2.0, 3.3.0)

*Does* compile in 2.13.12

## Minimized code

```scala
sealed trait InIntersection[I, A] {
    type R // Remaining types in the intersection Int
}

object InIntersection {
    implicit def derived[A, R0]: InIntersection[A & R0, A] = new InIntersection[A & R0, A] {
        type R = R0
    }
}

implicitly[InIntersection[Int & String, Int]]
```

## Output

```scala
[error] No given instance of type IntersectionBug$_.this.InIntersection[Int & String, Int] was found for parameter e of method implicitly in object Predef.
[error] I found:
[error] 
[error]     this.InIntersection.derived[A, R0]
[error] 
[error] But method derived in object InIntersection does not match type IntersectionBug$_.this.InIntersection[Int & String, Int].
[error] implicitly[InIntersection[Int & String, Int]]
[error]                                              ^
Error compiling project (Scala 3.4.0, JVM (17))
Compilation failed

```

## Expectation

I would expect it to compile. It does compile with scala 2.13.12 (if I change the `&` to `with`).

### PR DESCRIPTION
**Pull request by odersky**
When comparing arguments of two applied types, perform hard comparisons after easy ones. A comparison is hard if it entails a subtype test A <: B where A is an AndType or B is an OrType. Such comparisons need to perform an either, which might lose solutions.

Fixes #19999

### CODE REVIEW

**Comment by odersky** [comment]
We could possibly generalize this, delaying hard comparisons in more conjunctive tests, not just type in arguments. But it is hard in general to identify a conjunctive subsequence of tests when doing a subtype traversal.

**Comment by dwijnand** [comment]
Interesting!  I've had a case that required this defer too.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 1]
```diff
@@ -1683,19 +1683,43 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
         val tparam = tparams2.head
         val v = tparam.paramVarianceSign
 
+        /** An argument test is hard if it implies a comparison A <: B where
+         *  A is an AndType or B is an OrType. In these cases we need to run an
+         *  either, which can lose solutions if there are type variables involved.
+         *  So we defer such tests to run last, on the chance that some other argument
+         *  comparison will instantiate or constrain type variables first.
+         */
+        def isHard(arg1: Type, arg2: Type): Boolean =
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1716]: Using the word `hard` here might lead to confuse with hard unions since OrTypes are also involved. Maybe we could call this `isIncomplete` instead?

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 2]
```diff
@@ -1683,19 +1683,43 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
+          val arg1d = arg1.stripped
+          val arg2d = arg2.stripped
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1718]: Should we use `strippedDealias` to be more robust?
```suggestion
          val arg1d = arg1.strippedDealias
          val arg2d = arg2.strippedDealias
```

**Review by smarter — APPROVED** [review]
Otherwise LGTM.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala (hunk 2 above)
Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1718]: I tried that but it does not work since `strippedDealias` forces LazyTypes and that makes some tests fail.

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1718]: Concretely we got an infinite subtype recursion in one of the tests. I believe this is because black hole detection worked with a LazyType not expanded but failed when it was expanded.

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 3]
```diff
@@ -1683,19 +1683,43 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
     /** The bounds of parameter `tparam`, where all references to type paramneters
      *  are replaced by corresponding arguments (or their approximations in the case of
      *  wildcard arguments).
      */
     def paramBounds(tparam: Symbol): TypeBounds =
       tparam.info.substApprox(tparams2.asInstanceOf[List[Symbol]], args2).bounds
 
-    def recurArgs(args1: List[Type], args2: List[Type], tparams2: List[ParamInfo]): Boolean =
-      if (args1.isEmpty) args2.isEmpty
+    /** Test all arguments. Hard argument tests (according to isHard) are deferred in
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1694]:
```suggestion
    /** Test all arguments. Incomplete argument tests (according to isIncomplete) are deferred in
```

File: compiler/src/dotty/tools/dotc/core/TypeComparer.scala [hunk 4]
```diff
@@ -1781,10 +1805,26 @@ class TypeComparer(@constructorOnly initctx: Context) extends ConstraintHandling
...
                 else isSameType(arg2, arg1)
 
-        isSubArg(args1.head, args2.head)
-      } && recurArgs(args1.tail, args2.tail, tparams2.tail)
+        val arg1 = args1.head
+        val arg2 = args2.head
+        val rest1 = args1.tail
+        if !canDefer
+            || rest1.isEmpty && deferred1.isEmpty
+                // skip the hardness test if this is the last argument and no previous arguments were hard
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/TypeComparer.scala:1813]:
```suggestion
                // skip the incompleteness test if this is the last argument and no previous argument tests were incomplete
```

**Review by smarter — APPROVED** [review]
