### PR TITLE
Fix generic signatures for inherited inner classes

### LINKED ISSUE #26532: Mixin forwarder signature points to a nonexistent nested class owned by the subclass
## Compiler version

- 3.9.0-RC1
- 3.9.0-RC2
- 3.9.0-RC3
- 3.10.0-RC1-bin-20260712-f51c618-NIGHTLY

The same code works with 3.8.3, so the regression starts in 3.9.0-RC1.

## Minimized code

`Repro.scala`:

```scala
package repro

trait Base[S, D] {
  final class Helper
  final def helper(): Helper = new Helper
}

abstract class Impl[S, D] extends Base[S, D]
```

`Use.java`:

```java
package repro;

final class Use {
  void test(Impl<String, Integer> impl) {
    impl.helper();
  }
}
```

Compile with:

```shell
scala-cli compile Repro.scala -S 3.9.0-RC3 --server=false -d out
javac -cp out -d out Use.java
```

## Output

```text
Use.java:5: error: cannot access Impl$Helper
    impl.helper();
        ^
  class file for repro.Impl$Helper not found
```

`javap -p -s repro.Impl` shows:

```java
public final repro.Impl<S, D>.Helper helper();
  descriptor: ()Lrepro/Base$Helper;
```

The descriptor correctly refers to the class that exists, `Base$Helper`, while the generic `Signature` attribute refers to nonexistent `Impl$Helper`. With 3.8.3, the method is exposed as:

```java
public final repro.Base$Helper helper();
  descriptor: ()Lrepro/Base$Helper;
```

## Expectation

`Helper` is declared in `Base`, and the only generated nested class is `Base$Helper`. A mixin forwarder's generic signature must not relocate that class to `Impl`. It should either refer to `Base[S, D]#Helper` / `Base$Helper` consistently with the descriptor, or omit a redundant signature.

This breaks Java subclasses in [Apache Pekko PR #3303](https://github.com/apache/pekko/pull/3303): the compiler emits an `AbstractFSM[S,D].TransformHelper` return signature although the actual class is `FSM$TransformHelper`, and javac fails before the Java test can run. This appears related to generic-signature work around #24619 and #25880, but those issues do not cover this nonexistent-owner case.

### PR DESCRIPTION
**Pull request by tanishiking**
Rebind inner-class prefixes to their declaring owner so mixin forwarders cannot reference nonexistent subclass-owned classes.

This is a fix for regression by https://github.com/scala/scala3/pull/25880 It accidently removed `pre.baseType(sym.owner)` with `needsJavaSig` check, but we shouldn't remove rebinding `pre`,
that is an old scala/bug fix for https://github.com/scala/bug/issues/2585

Fixes #26532

## Have you relied on LLM-based tools in this contribution?

No

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

### CODE REVIEW

File: compiler/src/dotty/tools/backend/jvm/GenericSignatures.scala [hunk 1]
```diff
@@ -235,7 +235,16 @@ object GenericSignatures {
               boxedSig(tp.widenDealias.widenNullaryMethod)
         }
 
-      pre.widenDealias match {
+      // when generating a java generic signature that includes
+      // a selection of an inner class p.I, (p = `pre`, I = `cls`) must
+      // rewrite to p'.I, where p' refers to the class that directly defines
+      // the nested class I. see:
```
Comment (tanishiking) [inline compiler/src/dotty/tools/backend/jvm/GenericSignatures.scala:241]: Comment copied from scala/scala

https://github.com/scala/scala/blob/e2bf3551286f729b4f2bec78b36e3f890fccfd80/src/reflect/scala/reflect/internal/transform/Erasure.scala#L84-L87

File: tests/generic-java-signatures/i26532.check [hunk 2]
```diff
@@ -0,0 +1 @@
+public final i26532.Base<S, D>$Helper i26532.Impl.helper()
```
Comment (tanishiking) [inline tests/generic-java-signatures/i26532.check:1]: instead of `Impl...$Helper`

**Review by jchyb — APPROVED** [review]
LGTM!
