### ISSUE TITLE
Missing given instance for EitherT using type alias

### ISSUE THREAD

**Issue by jorolicht** [scala/scala3#20519]
## Compiler version
val scala3Version = "3.3.3"
with cats core library
libraryDependencies += "org.typelevel" %% "cats-core" % "2.12.0"

```Scala
import scala.concurrent.{ Future, ExecutionContext }
import scala.concurrent.ExecutionContext.Implicits.global
import cats.data.EitherT
import cats.syntax.all._

type FuEiErr[T] = Future[Either[Error, T]]

case class Error(msg: String)
def fA(x:Int): FuEiErr[Int] = Future(Right(x)) 
def fB(x:Int): FuEiErr[Int] = Future(Right(x))  

@main def TestEitherT(): Unit = 
  (for 
    a  <- EitherT(fA(7))
    b  <- EitherT(fB(42))
  yield a+b).value.map {
    case Left(err)  => println(s"Error: ${err.msg}")
    case Right(res) => println(s"Result: ${res}")
  }
```

## Output

```scala
[error] -- [E172] Type Error: ...src/main/scala/Main.scala:16:11 
[error] 16 |  yield a+b).value.map {
[error]    |           ^
[error]    |No given instance of type cats.Functor[[X0] =>> scala.concurrent.Future[Either[Error, X0] | X0]] was found for parameter F of method map in class EitherT
```

## Expectation
No compilation error, works in version 2.13

**Comment by Gedochao** [comment]
The same repro with Scala CLI:
```scala
//> using dep org.typelevel::cats-core:2.12.0
import scala.concurrent.{ Future, ExecutionContext }
import scala.concurrent.ExecutionContext.Implicits.global
import cats.data.EitherT
import cats.syntax.all._

type FuEiErr[T] = Future[Either[Error, T]]

case class Error(msg: String)
def fA(x:Int): FuEiErr[Int] = Future(Right(x))
def fB(x:Int): FuEiErr[Int] = Future(Right(x))

@main def TestEitherT(): Unit =
  (for
    a  <- EitherT(fA(7))
    b  <- EitherT(fB(42))
  yield a+b).value.map {
    case Left(err)  => println(s"Error: ${err.msg}")
    case Right(res) => println(s"Result: ${res}")
  }
```

**Comment by Gedochao** [comment]
We need to minimize this without the `cats-core` dependency.
@jorolicht would you be able to help?

**Comment by jorolicht** [comment]
> We need to minimize this without the `cats-core` dependency. @jorolicht would you be able to help?

well, try to do so

**Comment by jorolicht** [comment]
Have to add/copy some code from the cats library, hope this helps:
```Scala
import scala.concurrent.{ Future, ExecutionContext }
import scala.concurrent.ExecutionContext.Implicits.global

type FuEiErr[T] = Future[Either[Error, T]]

case class Error(msg: String)
def fA(x:Int): FuEiErr[Int] = Future(Right(x)) 
def fB(x:Int): FuEiErr[Int] = Future(Right(x))  

implicit def monadInstancesForFuture(implicit ec: ExecutionContext): Monad[Future] =
  new Monad[Future] {
    def pure[A](x: A): Future[A] = Future.successful(x)
    def flatMap[A, B](fa: Future[A])(f: A => Future[B]): Future[B] = fa.flatMap(f)
  }  

implicit def functorInstancesForFuture(implicit ec: ExecutionContext): Functor[Future] =
  new Functor[Future] { def map[A, B](fa: Future[A])(f: A => B): Future[B] = fa.map(f) }  
  
object EitherUtil:
  def leftCast[A, B, C](right: Right[A, B]): Either[C, B] =
    right.asInstanceOf[Either[C, B]]
  def rightCast[A, B, C](left: Left[A, B]): Either[A, C] =
    left.asInstanceOf[Either[A, C]]
  val unit = Right(())

trait FlatMap[F[_]]:
  def flatMap[A, B](fa: F[A])(f: A => F[B]): F[B]

trait Functor[F[_]] { self =>
  def map[A, B](fa: F[A])(f: A => B): F[B]
}

trait Monad[F[_]] extends FlatMap[F]: 
  def map[A, B](fa: F[A])(f: A => B): F[B] = flatMap(fa)(a => pure(f(a)))
  def pure[A](x: A): F[A]  
  
final case class EitherT[F[_], A, B](value: F[Either[A, B]]):
  def flatMap[AA >: A, D](f: B => EitherT[F, AA, D])(implicit F: Monad[F]): EitherT[F, AA, D] =
    EitherT(F.flatMap(value) {
      case l @ Left(_) => F.pure(EitherUtil.rightCast(l))
      case Right(b)    => f(b).value
    })   
  def map[D](f: B => D)(implicit F: Functor[F]): EitherT[F, A, D] = bimap(identity, f)  
  def bimap[C, D](fa: A => C, fb: B => D)(implicit F: Functor[F]): EitherT[F, C, D] =
    EitherT(
      F.map(value) {
        case Right(b) => Right(fb(b))
        case Left(a)  => Left(fa(a))
      }
    )  


@main def TestEitherT(): Unit = 
  (for 
    a  <- EitherT(fA(21))  // EitherT[Future,Error,Int](fA(21))  //ok
    b  <- EitherT(fB(21))  // EitherT[Future,Error,Int](fB(21))  //ok
  yield a+b).value.map {
    case Left(err)  => println(s"Error: ${err.msg}")
    case Right(res) => println(s"Answer: ${res}")
  }
```

**Comment by jorolicht** [comment]
cleaner code for demo:
```Scala
import scala.concurrent.{ Future, ExecutionContext }
import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.{Either, Left, Right}


type FuEiErr[T] = Future[Either[String, T]]
def fA(x:Int): FuEiErr[Int] = Future.successful(Right(x)) 
def fB(x:Int): FuEiErr[Int] = Future.successful(Right(x))  

case class EitherT[F[_], A, B](value: F[Either[A, B]]):
  def map[C](f: B => C)(using functor: Functor[F]): EitherT[F, A, C] = {
    EitherT(functor.map(value)(_.map(f)))
  }

  def flatMap[C](f: B => EitherT[F, A, C])(using monad: Monad[F]): EitherT[F, A, C] = 
    EitherT(monad.flatMap(value) {
      case Left(a) => monad.pure(Left(a))
      case Right(b) => f(b).value
    })

  def fold[C](fa: A => C, fb: B => C)(using functor: Functor[F]): F[C] = 
    functor.map(value) {
      case Left(a) => fa(a)
      case Right(b) => fb(b)
    }

  def isLeft(using functor: Functor[F]): F[Boolean] = functor.map(value)(_.isLeft)
  def isRight(using functor: Functor[F]): F[Boolean] = functor.map(value)(_.isRight)


trait Functor[F[_]]:
  def map[A, B](fa: F[A])(f: A => B): F[B]

trait Monad[F[_]] extends Functor[F]:
  def pure[A](a: A): F[A]
  def flatMap[A, B](fa: F[A])(f: A => F[B]): F[B]
  def map[A, B](fa: F[A])(f: A => B): F[B] = flatMap(fa)(a => pure(f(a)))


// Example instances for Future and Option
given futureMonad(using ec: ExecutionContext): Monad[Future] = new Monad[Future] {
  def pure[A](a: A): Future[A] = Future.successful(a)
  def flatMap[A, B](fa: Future[A])(f: A => Future[B]): Future[B] = fa.flatMap(f)
}

given optionMonad: Monad[Option] = new Monad[Option]:
  def pure[A](a: A): Option[A] = Some(a)
  def flatMap[A, B](fa: Option[A])(f: A => Option[B]): Option[B] = fa.flatMap(f)


@main def TestEitherT(): Unit = 
  (for 
    a  <- EitherT(fA(21))  // error
    b  <- EitherT(fB(21))  // error
    // a  <- EitherT[Future,String,Int](fA(21))  //ok
    // b  <- EitherT[Future,String,Int](fB(21))  //ok
  yield a+b).value.map {
    case Left(msg)  => println(s"Error: ${msg}")
    case Right(res) => println(s"Answer: ${res}")
  }
``

**Comment by road21** [comment]
We have faced with similar issue when trying to use syntax for `F[Either[..]]`.
The example above can be reduced to:

```scala
trait TCl[F[_]]

extension [F[_], A](e: F[Option[A]]) def boo(using ev: TCl[F]): Unit = ()

type Result[F[_], A] = F[Option[A]]

given t: TCl[Option] = new TCl[Option] {}

val b: Result[Option, Int] = None
b.boo // No given instance of type Playground.TCl[[X0] =>> Option[Option[X0] | X0]] was found for parameter ev of method ```
scastie: https://scastie.scala-lang.org/road21/6dblHcs1RpSrkK4JrnEPAQ

Also I want to note that:
1) Similar code works in scala 2
```scala
trait TCl[F[_]]

implicit class Stx[F[_], A](e: F[Option[A]]) {
  def boo(implicit ev: TCl[F]): Unit = ()
}

type Result[F[_], A] = F[Option[A]]

implicit val t: TCl[Option] = new TCl[Option] {}

val b: Result[Option, Int] = None 
b.boo // ok
```
scastie: https://scastie.scala-lang.org/road21/6dblHcs1RpSrkK4JrnEPAQ/5

2) As ugly workaround the following works:
```scala
```

**Comment by mbovel** [comment]
I could reproduce the above minimization. It indeed passes with 2.13 but fails with 3.6.2:

```scala
package issue20519

object Main {
  trait TCl[F[_]]

  implicit class Stx[F[_], A](e: F[Option[A]]) {
    def boo(implicit ev: TCl[F]): Unit = ()
  }

  type Result[F[_], A] = F[Option[A]]

  implicit val t: TCl[Option] = new TCl[Option] {}

  def main(args: Array[String]): Unit = {
    val b: Result[Option, Int] = None 
    b.boo // ok

    // works without the alias:
    val b2: Option[Option[Int]] = None
    b2.boo // ok
  }
}
```

```
➜  ~/scala-snippets-6 scala -S 2.13 issue20519.scala
Compiling project (Scala 2.13.15, JVM (21))
Compiled project (Scala 2.13.15, JVM (21))
➜  ~/scala-snippets-6 scala -S 3.6.2 issue20519.scala
Compiling project (Scala 3.6.2, JVM (21))
[error] ./issue20519.scala:16:10
[error] No given instance of type issue20519.Main.TCl[[X0] =>> Option[Option[X0] | X0]] was found for parameter ev of method boo in class Stx.
[error] I found:
[error] 
[error]     t
[error] 
[error] But Found:    (issue20519.Main.t : issue20519.Main.TCl[Option])
[error] Required: issue20519.Main.TCl[[X0] =>> Option[Option[X0] | X0]].
[error]     b.boo // ok
[error]          ^
Error compiling project (Scala 3.6.2, JVM (21))
Compilation failed
```

**Comment by mbovel** [comment]
Same with the Scala 3 version:

```scala
package issue20519_3

trait TCl[F[_]]

extension [F[_], A](e: F[Option[A]]) def boo(using ev: TCl[F]): Unit = ()

type Result[F[_], A] = F[Option[A]]

given t: TCl[Option] = new TCl[Option] {}

def main =
  val b: Result[Option, Int] = None
  b.boo
```

```
➜  ~/scala-snippets-6 scala -S 3.6.2 issue20519_3.scala 
Compiling project (Scala 3.6.2, JVM (21))
[error] ./issue20519_3.scala:13:3
[error] value boo is not a member of Result[Option, Int].
[error] An extension method was tried, but could not be fully constructed:
[error] 
[error]     boo[[X0] =>> Option[Option[X0] | X0], A](b)(t)
[error] 
[error]     failed with:
[error] 
[error]         No given instance of type TCl[[X0] =>> Option[Option[X0] | X0]] was found for parameter ev of method boo.
[error]         I found:
[error]         
[error]             t
[error]         
[error]         But given instance t does not match type TCl[[X0] =>> Option[Option[X0] | X0]].
[error]   b.boo
[error]   ^^^^^
Error compiling project (Scala 3.6.2, JVM (21))
Compilation failed
```

**Comment by mbovel** [comment]
Here are the generated constraints for the non-alias and alias cases.

### Without alias

```scala
class Box[T](val value: T)

def boo[F[_], A](e: F[Box[A]]): Unit = ()

type Result[G[_], B] = G[Box[B]]

def main =
  val b: Option[Box[Int]] = ???
  boo(b)
  // boo[[X0] =>> Option[X0]](b)
```

```
added constraint F :> Option to
 uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Option
     A
 ordering:
 co-deps:
 contra-deps:
 = true

added constraint A <: Int to
 uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Option
     A <: Int
 ordering:
 co-deps:
 contra-deps:
 = true

added constraint A :> Int to
 uninstantiated variables: F
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Option
     A := Int
 ordering:
 co-deps:
 contra-deps:
 = true

committing TS[8X, 1, 0] to TS[1, 0], fromConstr =  uninstantiated variables: F
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Option
     A := Int
 ordering:
 co-deps:
 contra-deps:
, toConstr =  uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1]
     A
 ordering:
 co-deps:
 contra-deps:
```

### With alias

```scala
class Box[T](val value: T)

def boo[F[_], A](e: F[Box[A]]): Unit = ()

type Result[G[_], B] = G[Box[B]]

def main =
  val b: Result[Option, Int] = ???
  boo(b)
  // boo[[X0] =>> Option[Box[X0] | X0]](b)
```

```
added constraint F :> [B] =>> Result[Option, B] to
 uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, B]
     A
 ordering:
 co-deps:
 contra-deps:
 = true

added constraint F :> Option to
 uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, X0] | Option[X0]
     A
 ordering:
 co-deps:
 contra-deps:
 = true

added constraint A <: Int to
 uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, X0] | Option[X0]
     A <: Int
 ordering:
 co-deps:
 contra-deps:
 = true

added constraint A :> Int to
 uninstantiated variables: F
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, X0] | Option[X0]
     A := Int
 ordering:
 co-deps:
 contra-deps:
 = true

CUT - prefer  uninstantiated variables: F
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, X0] | Option[X0]
     A := Int
 ordering:
 co-deps:
 contra-deps:
 over  uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, B]
     A
 ordering:
 co-deps:
 contra-deps:

committing TS[8X, 1, 0] to TS[1, 0], fromConstr =  uninstantiated variables: F
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Result[Option, X0] | Option[X0]
     A := Int
 ordering:
 co-deps:
 contra-deps:
, toConstr =  uninstantiated variables: F, A
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1]
     A
 ordering:
 co-deps:
 contra-deps:

added constraint F :> [X0] =>> Option[Box[X0] | X0] to
 uninstantiated variables: F
 constrained types: [F[_$1], A](e: F[Box[A]]): Unit
 bounds:
     F[_$1] >: Option[Box[X0] | X0]
     A := Int
 ordering:
 co-deps:
 contra-deps:
 = true
```

**Comment by mbovel** [comment]
Considering this snippet:

```scala
class Box[T](val value: T)

def boo[F[_]](e: F[Box[Int]]): Unit = ()
type Result[G[_], X] = G[Box[X]]

def main =
  val b: Result[Option, Int] = ???
  boo(b)
  // boo[[X0] =>> Option[Box[X0] | X0]](b)
```

Mixing traces and printing, here is a summary of where the `F :> [X] =>> Result[Option, X]` constraint originates from:

```scala
==> isSubType (b : Result[Option, Int]) <:< F[Box[Int]] 
  TypeComparer.thirdTry$1(TypeComparer.scala:643)
    TypeComparer.compareAppliedType2$1(TypeComparer.scala:1442)
      TypeComparer.canInstantiate$1(TypeComparer.scala:1392)
        TypeComparer.appOK$1(TypeComparer.scala:1386)
          TypeComparer.compareAppliedTypeParamRef$1(TypeComparer.scala:1248)
            TypeComparer.directionalIsSubType$1(TypeComparer.scala:1220)
              ==> isSubType [X] =>> Result[Option, X] <:< F?
                ==> isSubType [X] =>> Result[Option, X] <:< F frozen?
                <== isSubType [X] =>> Result[Option, X] <:< F frozen = false
                adding constraint F :> [X] =>> Result[Option, X]
                ==> isSubType [X] =>> Result[Option, X] <:< [_] =>> Any?
                <== isSubType [X] =>> Result[Option, X] <:< [_] =>> Any = true
                added constraint F :> [X] =>> Result[Option, X]
              <== isSubType [X] =>> Result[Option, X] <:< F = true
```

This is a consequence of the "partial unification" algorithm described here:

https://github.com/scala/scala3/blob/a50a1e49a3475ddef205aac05cd7c67827b0dae5/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L1163-L1217

**Comment by mbovel** [comment]
@smarter noted that there actually is a bug in `compareAppliedTypeParamRef`. The constraints are not properly rolled back when the call `directionalIsSubType` returns `true` but the call to `directionalRecur` returns `false`. #22339 fixes that.
