### ISSUE TITLE
Dotty Type Erasure for Scala 2 is wrong for `Array[Null]` and `Array[Nothing]`

### ISSUE THREAD

**Issue by hamzaremmal** [scala/scala3#22515]
## Compiler version

3.0.0-3.6.3

## Minimized code

```scala
//> using scala 3.6.3
@main def Test = Foo.a
```

```scala
//> using scala 2.13.16
object Foo {
    def a: Array[scala.Nothing] = ???
}
```

## Output

```scala
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.runtime.Nothing$[] Foo$.a()'
	at playground$package$.Test(playground.scala:1)
	at Test.main(playground.scala:1)
```

## Expectation

Work at runtime. The issue was introduced by https://github.com/scala/scala3/pull/11846

## Notes
Same if we have in the return type `Array[scala.Null]`
