### PR TITLE
Replace runtime.Rich* implicits on primitives by direct extension methods.

### LINKED ISSUE #24128: Scala 2 vs Scala 3 compiler regression when calling isNaN on a double
## Compiler version
2.13.x vs 3.x.x

## Minimized code
```scala
//> using scala 3.x.x

object Square {
  val d = 1.01
  d.isNaN
}

```

## Output
https://godbolt.org/z/xx4srTTh1

In Scala 3 the isNaN call is not optimized and there is a double2Double call which does boxing and triggers gc calls.

```
invokevirtual #36                 // Method scala/Predef$.double2Double:(D)Ljava/lang/Double;
invokevirtual #42                 // Method java/lang/Double.isNaN:()Z
```

## Expectation
In Scala 2 the compiled bytecode calls the static Double.isNaN

```
invokestatic  #29                 // Method java/lang/Double.isNaN:(D)Z
```

### PR DESCRIPTION
**Pull request by sjrd**
It has always been weird that the public API of primitive types, enriched by `Predef` depends on the `Rich*` classes, which are in the not-really-public `runtime` package.

Moreover, the design of those classes was overabstracted, with consequences on performance (unnecessary boxing) and quality of the API (including methods that do not make sense on some types). To mitigate that, the individual `Rich*` classes redefined some (but not all) of the methods, defeating the abstraction.

We solve both issues with a simple solution: define all those methods as simple `extension` methods. We do this directly in the companion objects of the primitive types.

---

This would be a required step before we do anything about #23824.

### CODE REVIEW

**Comment by hamzaremmal** [comment]
@sjrd you have beaten me to it 😄

**Comment by soronpo** [comment]
The problem is that extension methods are not equivalent to implicit classes/definition extensions. Without solving https://contributors.scala-lang.org/t/relaxed-extension-methods-sip-54-are-not-relaxed-enough/6585/1 this change will break everywhere that has methods in the same name in scope.

File: library/src/scala/Byte.scala [hunk 1]
```diff
@@ -485,5 +487,89 @@ object Byte extends AnyValCompanion {
...
   implicit def byte2float(x: Byte): Float = x.toFloat
   implicit def byte2double(x: Byte): Double = x.toDouble
-}
 
+  extension (self: Byte) {
+    /** Returns `'''true'''` if this number has no decimal component.
+      * Always `'''true'''` for `Byte`.
+      */
+    @deprecated("isWhole on Byte is always true", "2.12.15")
+    def isWhole: Boolean = true
```
Comment (hamzaremmal) [inline library/src/scala/Byte.scala:658]: I understand why this was done, but it feels weird to say that an extension method was deprecated since 2.12.15 😅

**Comment by sjrd** [comment]
> The problem is that extension methods are not equivalent to implicit classes/definition extensions. Without solving https://contributors.scala-lang.org/t/relaxed-extension-methods-sip-54-are-not-relaxed-enough/6585/1 this change will break everywhere that has methods in the same name in scope.

I don't see how that problem appears when defining extensions for *monomorphic* types. You wouldn't redefine another extension of `toHexString` for `Int` (or if you do, it's on you), so you won't have a clash like that. With polymorphic types there are reasons to define separate extensions for `Foo[Int]` and `Foo[String]`, but for a monomorphic type that's not the case.

**Comment by soronpo** [comment]
> > The problem is that extension methods are not equivalent to implicit classes/definition extensions. Without solving https://contributors.scala-lang.org/t/relaxed-extension-methods-sip-54-are-not-relaxed-enough/6585/1 this change will break everywhere that has methods in the same name in scope.
> 
> I don't see how that problem appears when defining extensions for _monomorphic_ types. You wouldn't redefine another extension of `toHexString` for `Int` (or if you do, it's on you), so you won't have a clash like that. With polymorphic types there are reasons to define separate extensions for `Foo[Int]` and `Foo[String]`, but for a monomorphic type that's not the case.

You are right. I thought the implementation used a typeclass approach + extension methods. My mistake.

File: library/src/scala/Byte.scala [hunk 2]
```diff
@@ -485,5 +487,89 @@ object Byte extends AnyValCompanion {
...
+      * - a negative value if `this < that`
+      * - `0` if `this == that`
+      */
+    def compare(that: Byte): Int = java.lang.Byte.compare(self, that)
+
+    /** A [[scala.collection.immutable.NumericRange]] from `this` up to but not including `end`.
+      *
+      * @param end The final bound of the range to make.
+      */
+    def until(end: Byte): NumericRange.Exclusive[Byte] = NumericRange(self, end, 1)
```
Comment (hamzaremmal) [inline library/src/scala/Byte.scala]: Since it is part of the very little subset where everyone agrees on it :). Same goes for `to`.
```suggestion
    infix def until(end: Byte): NumericRange.Exclusive[Byte] = NumericRange(self, end, 1)
```

File: library/src/scala/Byte.scala [hunk 3]
```diff
@@ -485,5 +487,89 @@ object Byte extends AnyValCompanion {
...
+    def isValidInt: Boolean = true
+
+    /** Returns the absolute value of `this`. */
+    def abs: Byte = java.lang.Math.abs(self.toInt).toByte
+
+    /** Returns `this` if `this > that` or `that` otherwise. */
+    def max(that: Byte): Byte = java.lang.Math.max(self.toInt, that.toInt).toByte
+
+    /** Returns `this` if `this < that` or `that` otherwise. */
+    def min(that: Byte): Byte = java.lang.Math.min(self.toInt, that.toInt).toByte
```
Comment (hamzaremmal) [inline library/src/scala/Byte.scala:690]: (my personal preferences here)
```suggestion
    infix def max(that: Byte): Byte = java.lang.Math.max(self.toInt, that.toInt).toByte

    /** Returns `this` if `this < that` or `that` otherwise. */
    infix def min(that: Byte): Byte = java.lang.Math.min(self.toInt, that.toInt).toByte
```

File: library/src/scala/Byte.scala (hunk 2 above)
Comment (sjrd) [reply library/src/scala/Byte.scala]: This PR is strictly a refactoring. Adding `infix` anywhere should be done separately.

Comment (hamzaremmal) [reply library/src/scala/Byte.scala]: If we view the PR this way, then okay.

**Comment by hamzaremmal** [comment]
@sjrd The test suite has been merged. It is missing the CB, sbt scripted test and Scala.js tests. I know this is waiting for the test suite, so you can consider rebasing this branch on top of https://github.com/scala/scala3/commit/6c86743ca85e6233c4d1170006d39b0b794a5330.

**Comment by tewecske** [comment]
Will this change be available in 3.3.x LTS?

**Comment by hamzaremmal** [comment]
> Will this change be available in 3.3.x LTS?

Unfortunately, it is not possible to be backported to 3.3.x.

**Comment by sjrd** [comment]
No.

**Comment by sjrd** [comment]
@WojciechMazur Would you mind running an open community build in this PR? It can affect source compatibility pretty strongly, so I'd like to gather cases where we can improve it.

**Comment by WojciechMazur** [comment]
The first run of OpenCB was ineffective - we've finally started to require to use new minimal JDK version, so ~300 projects failed with `8 is not a valid choice for -java-output-version`. 
I'll need to adjust OpenCB  to filter out or overwrite this flag (an its aliases) before running it again. I should have the results tomorrow.

**Comment by hamzaremmal** [comment]
> The first run of OpenCB was ineffective - we've finally started to require to use new minimal JDK version, so ~300 projects failed with `8 is not a valid choice for -java-output-version`. 
> 
> I'll need to adjust OpenCB  to filter out or overwrite this flag (an its aliases) before running it again. I should have the results tomorrow.  

We have been compiling the stdlib with Java 17 for two months now, it's just about compiling those projects with Java 17, not 8 (shouldn't be a problem unless weird project specific issues)

**Comment by WojciechMazur** [comment]
> We have been compiling the stdlib with Java 17 for two months now, it's just about compiling those projects with Java 17, not 8 (shouldn't be a problem unless weird project specific issues)

In OpenCommmunityBuild we've been compiling projects using JDK 17 since 3.7 so that's not an issue. JDK 8 is currently only used for the 3.3 LTS OpenCB builds. For nightlies we use either 17 or 21 - version is picked based on GitHub workflows defined for project. We'd be adding JDK 25 soon as well. 

What has changed recently is we've finally started to enforce the new minimal version in https://github.com/scala/scala3/pull/24146. Until that point `--java-output-version:8` was valid and as the results show it was pretty popular (~16% of projects was setting JDK compatibility for 16 or lower). 

The fix is on the way, I'm testing it locally, should be able to run OpenCB with it later today.

**Comment by WojciechMazur** [comment]
When compared with latest nightly 3.8.0-RC1-bin-20251010-7b7f2f1-NIGHTLY there are 7 projects affected by this change (there might be more but these were already failing when using latest nightly)

| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| akka/alpakka | 6.0.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458319552/job/52584532321) |  |
| avokka/avokka | 0.0.8 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458319552/job/52584532526) |  |
| business4s/decisions4s | 0.1.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458319552/job/52584532577) |  |
| herminiogg/shexml | 0.6.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458319552/job/52584531587) |  |
| indoorvivants/genovese | 0.0.3 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458320177/job/52584637532) |  |
| input-output-hk/scrypto | 3.1.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458319552/job/52584531749) |  |
| sirthias/parboiled2 | 2.5.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/18458319552/job/52584530362) |  |

**Comment by sjrd** [comment]
Thanks. There are definitely a few things to improve there.

**Comment by hamzaremmal** [comment]
@sjrd quick reminder about this PR if we were to merge it for `3.8.0`.

**Comment by Gedochao** [comment]
> @sjrd quick reminder about this PR if we were to merge it for `3.8.0`.

@sjrd bump, are we to merge it for 3.8.0?

**Comment by sjrd** [comment]
I had a look at the failures mentioned above. One is an easy fix (an omission, really). Some are expected source or macro breakages (like in parboiled, whose macro cannot recognize `to` and `until` ranges anymore). Some are more annoying.

Given everything else that is happening in 3.8.0, I don't think it's wise to subject our users to one *more* thing. But if you disagree, I can rebase and fix the missing thing, and then it's one more thing in the 3.8.0 ballot. :man_shrugging:

**Comment by hamzaremmal** [comment]
> I had a look at the failures mentioned above. One is an easy fix (an omission, really). Some are expected source or macro breakages (like in parboiled, whose macro cannot recognize `to` and `until` ranges anymore). Some are more annoying.
> 
> 
> 
> Given everything else that is happening in 3.8.0, I don't think it's wise to subject our users to one *more* thing. But if you disagree, I can rebase and fix the missing thing, and then it's one more thing in the 3.8.0 ballot. :man_shrugging: 

My vote goes to one more thing in 3.8.0. What about the others?

**Comment by soronpo** [comment]
I would not recommend to first introduce this change in 3.9LTS, so it's either for 3.8 or delayed to 3.10, IMO.

**Comment by sjrd** [comment]
> I would not recommend to first introduce this change in 3.9LTS, so it's either for 3.8 or delayed to 3.10, IMO.

Yes that's universally true. There's a feature freeze between 3.8 and 3.9. So if it doesn't go into 3.8, it won't get there earlier than 3.10.

**Comment by Gedochao** [comment]
> Given everything else that is happening in 3.8.0, I don't think it's wise to subject our users to one _more_ thing. But if you disagree, I can rebase and fix the missing thing, and then it's one more thing in the 3.8.0 ballot. 🤷‍♂️

I'd say we should get it in 3.8.0 if we can.

**Comment by sjrd** [comment]
Hum, actually the thing I thought was an omission is weird.

Scala 3.7.3:
```scala
scala> val y: Char = 'A'
val y: Char = A
                                                                                                              
scala> y.toHexString
-- [E008] Not Found Error: -----------------------------------------------------
1 |y.toHexString
  |^^^^^^^^^^^^^
  |value toHexString is not a member of Char.
  |An extension method was tried, but could not be fully constructed:
  |
  |    intWrapper(y)
1 error found
                                                                                                              
scala> '#'.toHexString
val res0: String = 23
```
Note how it works when it's a *literal* char? But not if it's a value of type `Char`.

After the changes in this PR, it doesn't work with the literal anymore, which aligns the behavior to the non-literal case. Instead, you have to write `'#'.toInt.toHexString`.

With this PR, we can either forbid it in all cases (current situation), or allow it even if it's a non-literal. I'm inclined to pick the former. Therefore I just rebased.

If people want to review for real, now is the time.

**Comment by hamzaremmal** [comment]
> With this PR, we can either forbid it in all cases (current situation), or allow it even if it's a non-literal. I'm inclined to pick the former. Therefore I just rebased

I think the current situation is the best.

File: library/src/scala/Boolean.scala [hunk 4]
```diff
@@ -138,5 +138,27 @@ object Boolean extends AnyValCompanion {
...
+
+    /** Compares `this` to `that` according to the standard total ordering.
+      *
+      * Returns:
+      * - a positive value if `this` is `true` and `that` is `false`
+      * - a negative value if `this` is `false` and `that` is `true`
+      * - `0` if `this == that`
+      */
+    def compare(that: Boolean): Int = java.lang.Boolean.compare(self, that)
+
```
Comment (hamzaremmal) [inline library/src/scala/Boolean.scala:159]: Technically, this method is missing too
```scala
def compareTo(that: Boolean): Int = self.compare(that)
```

Comment (hamzaremmal) [reply library/src/scala/Boolean.scala:159]: Also, all of these methods comes from the fact that `RichBoolean` inherits `scala.math.Ordered`.
I understand that we are porting what exists but at the same time, it's weird that we don't utilize the fact that `Boolean` is an `Ordering`.

File: library/src/scala/Byte.scala
Comment (hamzaremmal) [inline library/src/scala/Byte.scala:1]: Technically, these methods from `ScalaNumberProxy` are missing too:
```scala
  def doubleValue
  def floatValue
  def longValue
  def intValue
  def byteValue
  def shortValue
```

File: library/src/scala/Byte.scala (hunk 2 above)
Comment (hamzaremmal) [reply library/src/scala/Byte.scala]: If this PR is strictly refactoring, there are no methods `until` and `to` available for `Byte`.

```scala
val x: Byte = ???
val y = x to 9
```

It fails with the following:
```scala
value to is not a member of Byte.
An extension method was tried, but could not be fully constructed:

    intWrapper(x)
```

File: library/src/scala/Short.scala [hunk 5]
```diff
@@ -484,5 +486,117 @@ object Short extends AnyValCompanion {
   implicit def short2long(x: Short): Long = x.toLong
   implicit def short2float(x: Short): Float = x.toFloat
   implicit def short2double(x: Short): Double = x.toDouble
-}
 
+  extension (self: Short) {
```
Comment (hamzaremmal) [inline library/src/scala/Short.scala:652]: Technically, you can write:

```scala
val x: Byte = ???
val y = x.self
```

Comment (hamzaremmal) [reply library/src/scala/Short.scala:652]: Same, missing `compareTo`

File: library/src/scala/Long.scala
Comment (hamzaremmal) [inline library/src/scala/Long.scala:1]: Same here, you can't write `(x: Long).self`

**Review by hamzaremmal — DISMISSED** [review]
Some observations here. I see that some extensions are missing like `compareTo`, `doubleValue`, `self`. Does this PR relies on the fact that we will fallback to `Rich*` via the implicit conversion? If yes, it should clearly state that. If we don't, does that mean that these methods will not be available in source anymore? That sets precedence to removing things in source but not in the binary.
On the other hand, I see that this PR added `to` and `until` on `Byte` which didn't use to exist in the `Rich*` world. Since this is a *refactoring* PR, we shouldn't have additions. I'm requesting changes as I want to have an answer to these questions before approving.

File: library/src/scala/Boolean.scala (hunk 4 above)
Comment (sjrd) [reply library/src/scala/Boolean.scala:159]: You still get `compareTo` from auto-boxing `Boolean` to `java.lang.Boolean`.

File: library/src/scala/Byte.scala
Comment (sjrd) [reply library/src/scala/Byte.scala:1]: Same. These exist on `java.lang.Number`, and *a fortiori* on its subclasses, so you get them with auto-boxing.

File: library/src/scala/Short.scala (hunk 5 above)
Comment (sjrd) [reply library/src/scala/Short.scala:652]: > Technically, you can write:

Yes, and it's one of the open CB failures.

Do we want to reintroduce them as `@deprecated`?

**Comment by sjrd** [comment]
> Some observations here. I see that some extensions are missing like `compareTo`, `doubleValue`, `self`. Does this PR relies on the fact that we will fallback to `Rich*` via the implicit conversion? If yes, it should clearly state that. If we don't, does that mean that these methods will not be available in source anymore? That sets precedence to removing things in source but not in the binary.

As mentioned, you still get them through the Java boxed classes. This is where they were coming from before anyway, since that's a strong implicit.

> On the other hand, I see that this PR added `to` and `until` on `Byte` which didn't use to exist in the `Rich*` world. Since this is a _refactoring_ PR, we shouldn't have additions. I'm requesting changes as I want to have an answer to these questions before approving.

There were available before by widening of `Byte` and `Short` to `Int`. For some reason, this was allowed with the implicit classes. It is not working with the `extension`s anymore. Therefore, we add explicit source-compatible overloads. No source addition here. (Without them, `sjsJUnitTests/test` fails to compile, for example.)

File: library/src/scala/Short.scala (hunk 5 above)
Comment (hamzaremmal) [reply library/src/scala/Short.scala:652]: > Do we want to reintroduce them as @deprecated?

I would say no but are we breaking any of our guarantees by doing so?

**Comment by hamzaremmal** [comment]
> There were available before by widening of Byte and Short to Int. For some reason, this was allowed with the implicit classes. It is not working with the extensions anymore.

I tried it with 3.7.3 before commenting it and this snippet here (https://github.com/scala/scala3/pull/23872#discussion_r2468616212) didn't compile.

File: library/src/scala/Short.scala (hunk 5 above)
Comment (sjrd) [reply library/src/scala/Short.scala:652]: Not really. We don't promise source compat. If we did, this whole PR would be a big no-no.

**Comment by sjrd** [comment]
That's concerning. Because `range-mixed.scala` did not compile before I added these overloads (for `Short`). And that test comes directly from https://github.com/scala-js/scala-js/blob/3c7aa99cd648ca9816814fe30b03433283e35750/test-suite/js/src/test/scala/org/scalajs/testsuite/typedarray/TypedArrayConversionTest.scala#L124-L138, which refused to compile but is clearly working on `main`.

**Comment by hamzaremmal** [comment]
It is indeed concerning but it is not as bad as we expected (broken test suite and infra). The Scala.js test, as written compiles with Scala 3.7.3 but it does not generalize. In this snippet, `x` compiles but `y` doesn't.
```scala
val x = (Byte.MinValue to Byte.MaxValue) // ok (what Scala.js test does)

object Foo:
  val Min: Byte = 0
  val Max: Byte = 10

val y = (Foo.Min to Foo.Max) // doesn't compile with Scala 3.7.3
```

AST after typer.

```scala
-- [E008] Not Found Error: test.scala:8:17 -------------------------------------
8 |val y = (Foo.Min to Foo.Max) // doesn't compile with Scala 3.7.3
  |         ^^^^^^^^^^
  |        value to is not a member of Byte.
  |        An extension method was tried, but could not be fully constructed:
  |
  |            intWrapper(Foo.Min)
[[syntax trees at end of                     typer]] // test.scala
package <empty> {
  final lazy module val Foo: Foo = new Foo()
  final module class Foo() extends Object() { this: Foo.type =>
    val Min: Byte = 0
    val Max: Byte = 10
  }
  final lazy module val test$package: test$package = new test$package()
  final module class test$package() extends Object() {
    this: test$package.type =>
    val x: scala.collection.immutable.Range.Inclusive = intWrapper(-128).to(127)
    val y:
      
        <error value to is not a member of Byte.
An extension method was tried, but could not be fully constructed:

    intWrapper(Foo.Min)>
        
     = Foo.Min.to(Foo.Max)
  }
}

1 error found
```

File: library/src/scala/Byte.scala
Comment (hamzaremmal) [reply library/src/scala/Byte.scala:1]: I actually forgot about auto-boxing. I checked all the places I expected the remaining missing functions to be but in the boxed version in `java.lang`.

**Comment by sjrd** [comment]
So, is this another case of literal/constant expression versus arbitrary expression?

**Comment by hamzaremmal** [comment]
> So, is this another case of literal/constant expression versus arbitrary expression?

Not really, I don't know yet exactly what happens and I didn't (nor do) have the time at the moment to debug it in details.
Even if in my example we write `final val MinValue: Byte = 10`, it will not work.

This also doesn't work in Scala 3.7.3: `val y = ((0: Byte) to (10: Byte))`

**Comment by Gedochao** [comment]
I'll just link the issue here, so that the connection is easy to find.
The blocker seems to be:
- https://github.com/scala/scala3/issues/24321

**Comment by Gedochao** [comment]
@sjrd @hamzaremmal is https://github.com/scala/scala3/issues/24321 still a blocker here?
Since that'd require a SIP, I think we might need to postpone this or think of another scenario, if it still is.

**Comment by sjrd** [comment]
I thought we had already agreed to defer this PR to 3.10?

**Comment by hamzaremmal** [comment]
> I thought we had already agreed to defer this PR to 3.10?

We did.

**Comment by Gedochao** [comment]
Okay then.

**Comment by Gedochao** [comment]
@sjrd I guess this is worth a rebase, since we're entering 3.10?

**Comment by sjrd** [comment]
@Gedochao Rebased.

It still breaks Parboiled in the community build, since it has a macro that cannot recognize the new tree shape. What do we do about that?

**Comment by SethTisue** [comment]
> It still breaks Parboiled in the community build, since it has a macro that cannot recognize the new tree shape. What do we do about that?

@xuwei-k I see you've been doing the maintenance on parboiled, is it something you'd be interested in fixing?

**Comment by xuwei-k** [comment]
- https://github.com/sirthias/parboiled2/pull/708

**Comment by sjrd** [comment]
Yeah, this of is green now. Thanks a lot @xuwei-k for the parboiled changes!

@Gedochao this is ready for a real review now.

Note that I'll be on vacation for the next 3 weeks, so I might not be super responsive.

File: library/src/scala/Float.scala [hunk 6]
```diff
@@ -401,5 +401,103 @@ object Float extends AnyValCompanion {
...
+    /** Returns the sign of `this`.
+      *
+      * - `1.0f` if `this > 0.0f`;
+      * - `-1.0f` if `this < 0.0f`;
+      * - `this` otherwise (for zeros and `NaN`).
+      */
+    def sign: Float = java.lang.Math.signum(self)
+
+    /** Returns the signum of `this`. */
+    @deprecated("signum does not handle -0.0f or Double.NaN; use `sign` method instead", since = "2.13.0")
```
Comment (noti0na1) [inline library/src/scala/Float.scala]: Should this be `Float.NaN`?

File: library/src/scala/Int.scala
Comment (noti0na1) [inline library/src/scala/Int.scala:1]: The scaladoc still says:
```
 *  There is an implicit conversion from [[scala.Int]] => [[scala.runtime.RichInt]]
 *  which provides useful non-primitive operations.
```
, which should be updated with this PR.

File: library/src/scala/Byte.scala [hunk 7]
```diff
@@ -14,6 +14,8 @@ package scala
 
 import scala.language.`2.13`
 
+import scala.collection.immutable.NumericRange
```
Comment (noti0na1) [inline library/src/scala/Byte.scala]: Unused import? also in `Short` and `Double`

**Review by noti0na1 — CHANGES_REQUESTED** [review]
Otherwise, LGTM

**Comment by sjrd** [comment]
Thanks for the review. Updated.

**Review by noti0na1 — APPROVED** [review]
