### ISSUE TITLE
Scala test class and Java main class by the same name cause runtime error

### ISSUE THREAD

**Issue by charpov** [scala/scala3#22605]
## Compiler version

ThisBuild / scalaVersion := "3.6.3"

### in `src/main/java/p`:

```java
package p;

class Foo {
  public Foo(Object o) {}
}
```

```java
package p;

final class SomeClass {
  Foo foo() {
    return new Foo(this);
  }
}
```

### in `src/test/scala/p`
  
```Scala
package p

class Foo(n: Int)

@main def Test() = new SomeClass().foo
```

## Output

At runtime, the Java `Foo` constructor is not found:

```plain
> Test/runMain p.Test
[info] running p.Test 
Exception in thread "sbt-bg-threads-3" java.lang.NoSuchMethodError: 'void p.Foo.<init>(java.lang.Object)'
	at p.SomeClass.foo(SomeClass.java:5)
	at p.Foo$package$.Test(Foo.scala:5)
	at p.Test.main(Foo.scala:5)
        ...
```

## Expectation

A compile-time error instead of a `NoSuchMethodError` exception.

**Comment by sjrd** [comment]
This is expected. This is how classpaths work on the JVM. Things get shadowed when they're not part of the same compilation run (and Java and Scala are necessarily compiled separately, since they use different compilers).

**Comment by som-snytt** [comment]
In particular, it could be a "test" version of the class.

They could be distinguished by using a special classloader for Test; that would be a feature of the test runner.

The runner could help diagnose linkage errors by reporting shadowing of classes mentioned by the exception (including the stack trace).

Scala 2 recently got a similar hint https://github.com/scala/bug/issues/12289#issuecomment-2098838627

where the error condition is narrow (probably to be conservative) but maybe there are more errors where it's useful to add, "Did you intend to use this shadowed class?"

This could be quite broad; that is, broader than a missing class or method: suppose the breakage is that the shadowed class had a conversion. An error could check for shadowing of all classes involved in an expression, including args of an application.

That sounds like a job for the IDE, but often the IDE relies on the compiler for diagnostics (naturally) and it could be tricky to model the classpath precisely.

In the absence of a compiletime error, the compiler could offer an explicit mechanism.
```
compiletime.lint(SomeClass().foo) // error if supplemental hints or lints produce diagnostics
```

**Comment by charpov** [comment]
I'll let you be judge of what's technically feasible and what's not. Two comments:

1. It has nothing to do with some sources being in Java, as I initially thought. After I read your reply, I tried a pure Scala variant and I run into the same problem:

    in `src/main/java/p`:

    ```scala
    package p
    
    class Foo(o: AnyRef)
    
    class SomeClass:
       def foo: Foo = new Foo(this)
    ```

2. It may seem like a minor problem, but even on the small program where it happened, it took me a while to realize I had a class by the same name buried in my tests. Of course, now that I understand the issue, I could deal with it faster. But otherwise, it's not obvious that an error that looks like something is missing actually stems for having something defined twice!
