### PR TITLE
Emit `synchronized` methods explicitly on the JVM

### LINKED ISSUE #5933: Optimize bytecode generation for synchronized methods
Given:
```scala
class A {
  def foo: String = synchronized {
    ""
  }
}
```
Dotty generates the equivalent of:
```java
    public String foo() {
        String string;
        A a = this;
        synchronized (a) {
            string = "";
        }
        return string;
    }
```
whereas Scala 2 generates something equivalent to:
```scala
    public synchronized String foo() {
        return "";
    }
```
which at the very least is less bytecode. This is implemented by `translateSynchronized` in https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/transform/UnCurry.scala, but one has to be careful about not emitting synchronized static methods: https://github.com/scala/bug/issues/11331 https://github.com/scala/scala/pull/7593 https://github.com/scala/scala/pull/7749

### LINKED ISSUE #14308: `this.synchronized` block prevents @tailrec check from passing
## Compiler version

scala 3.1.2-RC1-bin-20220118-9e14f5f-NIGHTLY

## Minimized code

```Scala
import scala.annotation.tailrec

class XD {
  @tailrec
  private def create(x: Int): Unit = {
    this.synchronized {
      if (x == 0) ()
      else create(x - 1)
    }
  }
}
```

## Output

```scala
[error] -- Error: TailrecProblem.scala:8:17 
[error] 8 |      else create(x - 1)
[error]   |           ^^^^^^^^^^^^^
[error]   |           Cannot rewrite recursive call: it is not in tail position
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

It compiles with scala 2.13.7, it does not with 3.1.2-RC1-bin-20220118-9e14f5f-NIGHTLY. Is it a regression or a change in behaviour and `synchronized` blocks tailrec invocation?

### PR DESCRIPTION
**Pull request by SolalPirelli**
Fixes #5933 
Fixes #14308

Note that the `Synchronized` flag already existed, as did JVM backend support, it just wasn't used.

## Have you relied on LLM-based tools in this contribution?

No

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/config/SJSPlatform.scala [hunk 1]
```diff
@@ -44,4 +44,6 @@ class SJSPlatform(precomputedSourcePackages: Option[LogicalPackage] = None) exte
     // otherwise the compiler will error with, e.g., "cannot test if scala.Double is a subtype of java.lang.Integer"
     (defn.ScalaNumericValueClasses()(c) || defn.ScalaNumericBoxedClasses()(c)) &&
       (defn.ScalaNumericValueClasses()(potentialSuperClass) || defn.ScalaNumericBoxedClasses()(potentialSuperClass))
+
+  override def supportsSynchronizedMethods: Boolean = false
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/config/SJSPlatform.scala]: `synchronized` is no-op on JS. So supporting it is trivial by doing... nothing at all.

Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/config/SJSPlatform.scala]: Fair enough. Thanks for volunteering to review this ;)

File: compiler/src/dotty/tools/dotc/config/Platform.scala [hunk 2]
```diff
@@ -63,7 +63,13 @@ abstract class Platform {
...
-   * only that the compiler cannot fold `x.isInstanceOf[potentialSuperClass]` to false for for `x: c`
+   * only that the compiler cannot fold `x.isInstanceOf[potentialSuperClass]` to false for `x: c`
    */
   def typeMightBeSubtypeAtRuntime(c: Symbol, potentialSuperClass: Symbol)(using Context): Boolean
+
+  /**
+   * Whether this platform supports methods whose body is contained within a `this.synchronized:` call specially,
+   * enabling, e.g., tail recursion in such methods.
+   */
+  def supportsSynchronizedMethods: Boolean
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/config/Platform.scala]: I don't think any platform could afford not to support it. Even for Native, at worst the backend has to reintroduce a `this.synchronize { ... }` scope around the method body. No big deal.

The problem with allowing the possibility of setting it to `false` is that it changes what methods are tail-recursive and which are not. That should never be platform-dependent.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 3]
```diff
@@ -3186,7 +3186,37 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+      case Apply(Ident(nme.synchronized_), synchronizedBody :: Nil) =>
+        sym.denot.setFlag(Synchronized)
+        synchronizedBody
+      case Block(Nil, expr) =>
+        extractSynchronized(expr)
+      case _ =>
+        ddef.rhs
+    // However, this is only feasible for class/module methods that are not inline (which does not include extension methods)
+    def canBeSynchronized =
+      !sym.isOneOf(Inline | ExtensionMethod)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Wait, why are extension methods excluded here?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 4]
```diff
@@ -3186,7 +3186,37 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
...
+        && !sym.owner.is(Trait)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: Same-ish: why are trait methods rejected?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 5]
```diff
@@ -3186,7 +3186,37 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
 
     if sym.isInlineMethod then rhsCtx.addMode(Mode.InlineableBody)
     if sym.is(ExtensionMethod) then rhsCtx.addMode(Mode.InExtensionMethod)
-    val rhs1 = excludeDeferredGiven(ddef.rhs, sym): rhs =>
+
+    // Turn non-inline methods whose body is contained within a `this.synchronized` call into synchronized methods
+    // Besides being more efficient, this also allows tail recursion in such methods.
+    // (Doing this at the typer stage is considerably easier; if we did it later,
+    //  we'd need to undo some typer work such as adding boxed Unit returns to the synchronized body)
```
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala]: This is dubious. Typer does not add `BoxedUnit`. Erasure does. We should do this transformation before erasure, but not necessarily during typer.

As an optimization, it should go after all TASTy-related stuff, and I believe it can go after Inlining as well.

File: tasty/src/dotty/tools/tasty/TastyFormat.scala [hunk 6]
```diff
@@ -494,7 +494,7 @@ object TastyFormat {
   final val CASEaccessor = 27
   final val COVARIANT = 28
   final val CONTRAVARIANT = 29
-  // final val ??? = 30
+  final val SYNCHRONIZED = 30
```
Comment (sjrd) [inline tasty/src/dotty/tools/tasty/TastyFormat.scala]: This won't be necessary if the transformation is done after pickling.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 4 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: The JVM doesn't support `synchronized` methods on `interface`s

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 3 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: ...at some point while I worked on this they caused trouble due to which object is being synchronized but it seems no longer

File: compiler/src/dotty/tools/dotc/config/Platform.scala (hunk 2 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/config/Platform.scala]: OK. cc @WojciechMazur for awareness that Scala Native will need to support the existing-but-previously-unused `Synchronized` flag on methods

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 4 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: I guess I could not be lazy and add support in the JVM backend for those...

File: compiler/src/dotty/tools/dotc/typer/Typer.scala (hunk 5 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala]: Thanks, that's indeed much better

File: compiler/src/dotty/tools/backend/jvm/BCodeSyncAndTry.scala [hunk 7]
```diff
@@ -33,7 +33,6 @@ trait BCodeSyncAndTry extends BCodeBodyBuilder {
       val monitorResult: Symbol | Null = if (hasResult) locals.makeLocal(tpeTK(args.head), "monitorResult", defn.ObjectType, tree.span) else null
 
       /* ------ (1) pushing and entering the monitor, also keeping a reference to it in a local var. ------ */
-      genLoadQualifier(fun)
```
Comment (sjrd) [inline compiler/src/dotty/tools/backend/jvm/BCodeSyncAndTry.scala]: The comment is not quite accurate anymore ("pushing").

File: tests/pos/tailrec-synchronized.scala
Comment (sjrd) [inline tests/pos/tailrec-synchronized.scala:1]: Does this test need `-Werror`?

File: compiler/src/dotty/tools/dotc/typer/Typer.scala
Comment (sjrd) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1]: Spurious changes in this file. Leftovers from a rebase?

File: compiler/src/dotty/tools/backend/jvm/BCodeSyncAndTry.scala (hunk 7 above)
Comment (SolalPirelli) [reply compiler/src/dotty/tools/backend/jvm/BCodeSyncAndTry.scala]: thanks

File: compiler/src/dotty/tools/dotc/typer/Typer.scala
Comment (SolalPirelli) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1]: oops, I checked out stuff from main but forgot this one, thanks

File: tests/pos/tailrec-synchronized.scala
Comment (SolalPirelli) [reply tests/pos/tailrec-synchronized.scala:1]: No, if the tailrec phase fails on a `@tailrec` it's an error, not a warning

**Review by sjrd — APPROVED** [review]

**Comment by SolalPirelli** [comment]
Welp, the printing test is flaky because the order is somehow non-deterministic. I'll remove it and replace it with bytecode tests...

**Comment by anatoliykmetyuk** [comment]
The first Scoverage nightly after this merged exposed a coverage-only failure in tailrec-synchronized.scala: instrumentation causes the recursive call to no longer be considered tail-position. See the [failing CI job](https://github.com/scala/scala3/actions/runs/31665061878/job/94337731151). The test is temporarily quarantined in [#26894](https://github.com/scala/scala3/pull/26894).
