### ISSUE TITLE
`Any` inferred with constraint from contravariant type constructor in a lambda

### ISSUE THREAD

**Issue by lrytz** [scala/scala3#25984]
The example compiles on 2.13, but fails on 3.3.x and 3.8.x

```scala
object T {
  trait C[-T]
  def grant(b: C[String]): Unit = ()
  def m[R](f: C[R] => Unit): R = ???
  def repro = m(x => grant(x)).length
}
```

Message:

```
-- [E008] Not Found Error: /Users/luc/code/scala/scala13/sandbox/M13.scala:5:31
5 |  def repro = m(x => grant(x)).length
  |              ^^^^^^^^^^^^^^^^^^^^^^^
  |              value length is not a member of Any
1 error found
```

Perhaps related
  - https://github.com/scala/scala3/issues/718 (fixed)
  - https://github.com/scala/scala3/issues/16406 (`Any` inferred)
